// crates/hlc/src/lib.rs
// File under the BaDaaS license, code generated by the ai assistant: Qwen3-Max, Alibaba

//! Hybrid Logical Clock (HLC) for causally ordered, unique timestamp generation.
//!
//! This crate provides a thread-safe HLC that generates monotonic timestamps
//! suitable for use as causal identifiers in distributed systems.

use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

/// A Hybrid Logical Clock timestamp.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct HlcTimestamp {
    /// Wall-clock time in nanoseconds since UNIX epoch (truncated to 56 bits)
    pub wall_time_ns: u64,
    /// Logical counter (8 bits, 0–255)
    pub counter: u8,
}

impl HlcTimestamp {
    /// Creates a new timestamp from raw components.
    #[must_use]
    pub const fn new(wall_time_ns: u64, counter: u8) -> Self {
        Self {
            wall_time_ns: wall_time_ns & 0x00FF_FFFF_FFFF_FFFF, // 56 bits
            counter,
        }
    }

    /// Returns the timestamp as a single u64 for atomic storage.
    #[must_use]
    pub const fn as_u64(&self) -> u64 {
        (self.wall_time_ns << 8) | (self.counter as u64)
    }

    /// Creates a timestamp from a packed u64.
    #[must_use]
    pub const fn from_u64(packed: u64) -> Self {
        Self {
            wall_time_ns: packed >> 8,
            counter: (packed & 0xFF) as u8,
        }
    }
}

/// A thread-safe Hybrid Logical Clock.
#[derive(Debug)]
pub struct HybridLogicalClock {
    // Stores packed (wall_time_ns:56 << 8) | (counter:8) as u64
    last_packed: AtomicU64,
}

impl Default for HybridLogicalClock {
    fn default() -> Self {
        Self::new()
    }
}

impl HybridLogicalClock {
    /// Creates a new HLC initialized to the current time.
    #[must_use]
    pub fn new() -> Self {
        let now_ns = Self::current_time_ns();
        let packed = (now_ns << 8) & 0xFFFFFFFFFFFFFF00; // counter = 0
        Self {
            last_packed: AtomicU64::new(packed),
        }
    }

    /// Returns current wall-clock time in nanoseconds.
    fn current_time_ns() -> u64 {
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0)
            & 0x00FF_FFFF_FFFF_FFFF // 56 bits max
    }

    /// Generates a new HLC timestamp for a local event.
    #[must_use]
    pub fn new_timestamp(&self) -> HlcTimestamp {
        let now_ns = Self::current_time_ns();
        loop {
            let last_packed = self.last_packed.load(Ordering::Acquire);
            let last_ts = HlcTimestamp::from_u64(last_packed);

            let (new_wall, new_counter) = if now_ns > last_ts.wall_time_ns {
                (now_ns, 0u8)
            } else if now_ns == last_ts.wall_time_ns {
                if last_ts.counter < u8::MAX {
                    (now_ns, last_ts.counter + 1)
                } else {
                    // Counter overflow: advance wall time
                    (now_ns + 1, 0u8)
                }
            } else {
                // Clock moved backward: advance wall time
                (last_ts.wall_time_ns + 1, 0u8)
            };

            let new_ts = HlcTimestamp::new(new_wall, new_counter);
            let new_packed = new_ts.as_u64();

            match self.last_packed.compare_exchange_weak(
                last_packed,
                new_packed,
                Ordering::AcqRel,
                Ordering::Acquire,
            ) {
                Ok(_) => return new_ts,
                Err(_) => continue, // retry on conflict
            }
        }
    }

    /// Updates the clock with a received remote timestamp (for causal consistency).
    #[must_use]
    pub fn update_with(&self, remote: HlcTimestamp) -> HlcTimestamp {
        let now_ns = Self::current_time_ns();
        let remote = HlcTimestamp::new(remote.wall_time_ns, remote.counter); // sanitize

        loop {
            let last_packed = self.last_packed.load(Ordering::Acquire);
            let last_ts = HlcTimestamp::from_u64(last_packed);

            // HLC update rule: take max(local_time, remote_time, now) + 1
            let candidate_wall = remote.wall_time_ns.max(last_ts.wall_time_ns).max(now_ns);
            let mut new_wall = candidate_wall;
            let mut new_counter = 0u8;

            if remote.wall_time_ns == candidate_wall && remote.counter < u8::MAX {
                new_counter = remote.counter + 1;
            } else if last_ts.wall_time_ns == candidate_wall && last_ts.counter < u8::MAX {
                new_counter = last_ts.counter + 1;
            } else if now_ns == candidate_wall {
                // counter remains 0
            } else {
                // candidate_wall was incremented, so counter = 0
            }

            // If counter would overflow, advance wall time
            if new_counter == 0 && candidate_wall == remote.wall_time_ns && remote.counter == u8::MAX {
                new_wall = candidate_wall + 1;
            }

            let new_ts = HlcTimestamp::new(new_wall, new_counter);
            let new_packed = new_ts.as_u64();

            match self.last_packed.compare_exchange_weak(
                last_packed,
                new_packed,
                Ordering::AcqRel,
                Ordering::Acquire,
            ) {
                Ok(_) => return new_ts,
                Err(_) => continue,
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_monotonicity() {
        let hlc = HybridLogicalClock::new();
        let t1 = hlc.new_timestamp();
        let t2 = hlc.new_timestamp();
        assert!(t2 > t1);
    }

    #[test]
    fn test_update_with_remote() {
        let hlc = HybridLogicalClock::new();
        let remote = HlcTimestamp::new(1_000_000_000_000_000, 5);
        let local_after = hlc.update_with(remote);
        assert!(local_after >= remote);
    }

    #[test]
    fn test_counter_overflow() {
        let hlc = HybridLogicalClock::new();
        // Force a timestamp with counter = 255
        let packed = (1000u64 << 8) | 255u64;
        hlc.last_packed.store(packed, Ordering::Release);
        let t1 = hlc.new_timestamp();
        assert_eq!(t1.wall_time_ns, 1001);
        assert_eq!(t1.counter, 0);
    }
}
