// cdqn/crates/hlc/src/lib.rs
// File under the BaDaaS license, code generated by ai assistant: Gemini 2.5 Pro, Google

use chrono::{DateTime, Utc};
use cryptocore::NodeId;
use serde::{Deserialize, Serialize};
use std::cmp::Ordering;
use std::fmt;

/// A Hybrid Logical Clock timestamp.
/// It combines physical time (UTC) with a logical counter to ensure a total ordering
/// of events, even if they occur at the same physical time. It also includes the
/// NodeId to prevent collisions in a distributed system.
#[derive(Serialize, Deserialize, Clone, Debug, Eq, PartialEq)]
pub struct Hlc {
    timestamp: DateTime<Utc>,
    counter: u16,
    node_id: NodeId,
}

impl Hlc {
    /// Creates a new HLC instance for a specific node.
    pub fn new(node_id: NodeId) -> Self {
        Self {
            timestamp: Utc::now(),
            counter: 0,
            node_id,
        }
    }

    /// Advances the clock's time. This is the primary method for generating a new timestamp.
    /// It ensures that each generated timestamp is unique and causally later than the previous one.
    pub fn new_timestamp(&mut self) -> Self {
        let physical_time = Utc::now();

        if physical_time > self.timestamp {
            // The physical clock has advanced, so we can reset the counter.
            self.timestamp = physical_time;
            self.counter = 0;
        } else {
            // The physical clock has not advanced (or went backward), so we increment the counter
            // to ensure the new timestamp is logically greater.
            self.counter = self
                .counter
                .checked_add(1)
                .expect("HLC counter overflow");
        }

        Hlc {
            timestamp: self.timestamp,
            counter: self.counter,
            node_id: self.node_id,
        }
    }
}

/// Implement Ord to allow HLCs to be compared, which is their primary purpose.
/// The comparison order is: timestamp -> counter -> node_id.
impl Ord for Hlc {
    fn cmp(&self, other: &Self) -> Ordering {
        self.timestamp
            .cmp(&other.timestamp)
            .then_with(|| self.counter.cmp(&other.counter))
            .then_with(|| self.node_id.as_bytes().cmp(other.node_id.as_bytes()))
    }
}

impl PartialOrd for Hlc {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

/// A human-readable display format for the HLC.
impl fmt::Display for Hlc {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // A format similar to ISO 8601 but with the counter and a part of the node_id.
        // We will need to add the `hex` crate to our dev-dependencies for this.
        write!(
            f,
            "{}-{:04x}-{}",
            self.timestamp.to_rfc3339(),
            self.counter,
            hex::encode(&self.node_id.as_bytes()[..4])
        )
    }
}

// --- Unit Tests ---
#[cfg(test)]
mod tests {
    use super::*;
    use cryptocore::{CryptoOperations, NodeKeys};
    use std::thread;
    use std::time::Duration;

    #[test]
    fn test_hlc_ordering_same_node() {
        let node_keys = NodeKeys::new();
        let mut hlc = Hlc::new(*node_keys.node_id());

        let t1 = hlc.new_timestamp();
        // Ensure a small delay to allow the physical clock to potentially advance.
        thread::sleep(Duration::from_micros(10));
        let t2 = hlc.new_timestamp();

        assert!(
            t2 > t1,
            "A later timestamp should be greater than an earlier one."
        );
    }

    #[test]
    fn test_hlc_ordering_different_nodes() {
        let node_a_keys = NodeKeys::new();
        let node_b_keys = NodeKeys::new();

        let mut hlc_a = Hlc::new(*node_a_keys.node_id());
        let mut hlc_b = Hlc::new(*node_b_keys.node_id());

        // Generate timestamps at roughly the same time.
        let t_a = hlc_a.new_timestamp();
        let t_b = hlc_b.new_timestamp();

        // They should not be equal because their node_ids are different.
        assert_ne!(
            t_a, t_b,
            "Timestamps from different nodes should not be equal."
        );
    }

    #[test]
    fn test_counter_increments_on_same_timestamp() {
        let node_keys = NodeKeys::new();
        let mut hlc = Hlc::new(*node_keys.node_id());

        let t1 = hlc.new_timestamp();

        // Manually set the clock's internal state to the same time as t1
        // to simulate a rapid sequence of events within the same clock tick.
        hlc.timestamp = t1.timestamp;
        hlc.counter = t1.counter;

        let t2 = hlc.new_timestamp();

        assert_eq!(
            t2.timestamp, t1.timestamp,
            "Timestamp should not have advanced."
        );
        assert_eq!(
            t2.counter,
            t1.counter + 1,
            "Counter should have incremented."
        );
        assert!(
            t2 > t1,
            "t2 should be logically greater than t1 due to the counter."
        );
    }
}
