// crates/chronosa/src/dispatcher.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! The central, non-blocking CDU Dispatcher.
//!
//! This module implements a custom Multi-Producer, Multi-Consumer (MPMC) channel
//! using `crossbeam` to form the backbone of Chronosa's asynchronous runtime.

use cdqn_cdu::Cdu;
use std::sync::Arc;
use crossbeam::channel::{self, Sender, Receiver, TrySendError};

// The capacity of the channel.
const DISPATCHER_CAPACITY: usize = 1024;

/// The central MPMC channel for broadcasting new CDUs to all Chronosa roles.
/// NOTE: This is a simple MPMC channel, not a broadcast channel. Roles must
/// be manually managed to ensure all receive the message.
pub struct CduDispatcher {
    /// The sender half of the channel.
    sender: Sender<Arc<Cdu>>,
    /// The receiver half of the channel (used to clone new receivers).
    receiver: Receiver<Arc<Cdu>>,
}

impl CduDispatcher {
    /// Creates a new CduDispatcher.
    #[must_use]
    pub fn new() -> Self {
        let (sender, receiver) = channel::bounded(DISPATCHER_CAPACITY);
        CduDispatcher { sender, receiver }
    }

    /// Publishes a new CDU to the channel.
    ///
    /// The CDU is wrapped in an Arc to ensure it is immutable and cheaply cloneable.
    /// Returns an error if the channel is full.
    pub fn publish(&self, cdu: Cdu) -> Result<(), TrySendError<Arc<Cdu>>> {
        let arc_cdu = Arc::new(cdu);
        self.sender.try_send(arc_cdu)?;
        Ok(())
    }

    /// Creates a new receiver for a Chronosa role to subscribe to the CDU stream.
    #[must_use]
    pub fn subscribe(&self) -> Receiver<Arc<Cdu>> {
        self.receiver.clone()
    }
}

impl Default for CduDispatcher {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cdqn_cdu::payloads::GenesisPayload;
    use cdqn_hlc::HybridLogicalClock;
    use cdqn_cryptocore::hash_sha3_256;
    use std::thread;
    use std::time::Duration;

    // Helper to create a minimal CDU
    fn create_test_cdu(statement: &str) -> Cdu {
        let hlc = HybridLogicalClock::new();
        let node_id = hash_sha3_256(b"test_node").to_vec();
        let payload = GenesisPayload {
            hardware_fingerprint: [0u8; 32],
            os: "test".to_string(),
            timestamp: 0,
            location: statement.to_string(),
        };
        Cdu::create_genesis_cdu(payload, node_id, &hlc)
    }

    #[test]
    fn test_dispatcher_publish_and_subscribe() {
        let dispatcher = CduDispatcher::new();
        let rx1 = dispatcher.subscribe();
        let rx2 = dispatcher.subscribe();

        let cdu1 = create_test_cdu("Message 1");
        let cdu2 = create_test_cdu("Message 2");

        // Publish CDU 1
        dispatcher.publish(cdu1.clone()).unwrap();

        // Check if one receiver got CDU 1 (it's a queue, so only one gets it)
        let received1 = rx1.recv().unwrap();
        assert_eq!(received1.id_hlc, cdu1.id_hlc);

        // Publish CDU 2
        dispatcher.publish(cdu2.clone()).unwrap();

        // Check if the second receiver got CDU 2
        let received2 = rx2.recv().unwrap();
        assert_eq!(received2.id_hlc, cdu2.id_hlc);
    }

    #[test]
    fn test_dispatcher_non_blocking_try_send() {
        let dispatcher = CduDispatcher::new();
        let cdu = create_test_cdu("Test");

        // Fill the channel to capacity
        for _ in 0..DISPATCHER_CAPACITY {
            dispatcher.publish(cdu.clone()).unwrap();
        }

        // The next send should fail immediately (non-blocking)
        let result = dispatcher.publish(cdu.clone());
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), TrySendError::Full(_)));
    }
}
