// crates/chronosa/src/dispatcher.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! The central, non-blocking CDU Dispatcher (Causal Event Bus).
//!
//! This module implements a shared, indexed log using only `std::sync::Mutex`
//! to enforce the Event Sourcing principle where the HLc defines the causal order.

use cdqn_cdu::Cdu;
use std::sync::{Arc, Mutex};
use std::collections::VecDeque;

// The capacity of the log (for memory management).
const DISPATCHER_CAPACITY: usize = 1024;

// --- Core Log Structure ---
/// The shared, immutable log of all CDUs, ordered by HLc.
type CausalLog = VecDeque<Arc<Cdu>>;

/// The central Causal Event Bus.
pub struct CduDispatcher {
    log: Arc<Mutex<CausalLog>>,
}

impl CduDispatcher {
    /// Creates a new CduDispatcher.
    #[must_use]
    pub fn new() -> Self {
        CduDispatcher {
            log: Arc::new(Mutex::new(VecDeque::with_capacity(DISPATCHER_CAPACITY))),
        }
    }

    /// Publishes a new CDU to the log (Send-and-Forget).
    ///
    /// This is a non-blocking operation. Returns an error if the log is full.
    pub fn publish(&self, cdu: Cdu) -> Result<(), String> {
        let arc_cdu = Arc::new(cdu);
        let mut log = self.log.lock().map_err(|_| "Dispatcher lock poisoned")?;

        if log.len() >= DISPATCHER_CAPACITY {
            // NOTE: In a real system, this would trigger a persistence/archival process.
            return Err("Causal Log is full (Archival needed)".to_string());
        }

        // NOTE: The log is implicitly ordered by the HLC of the incoming messages.
        log.push_back(arc_cdu);
        
        Ok(())
    }

    /// Retrieves a CDU from the log based on an index (Watermark).
    /// This is the core read operation for Agents.
    pub fn get_cdu_by_index(&self, index: usize) -> Result<Arc<Cdu>, String> {
        let log = self.log.lock().map_err(|_| "Dispatcher lock poisoned")?;

        log.get(index)
            .cloned()
            .ok_or_else(|| format!("Causal Log index {} out of bounds", index))
    }

    /// Returns the current length of the log (the next index to read).
    #[must_use]
    pub fn log_len(&self) -> usize {
        self.log.lock().map(|l| l.len()).unwrap_or(0)
    }

    /// Creates a clone of the dispatcher for another Agent to use.
    #[must_use]
    pub fn clone_for_agent(&self) -> Self {
        CduDispatcher {
            log: self.log.clone(),
        }
    }
}

impl Default for CduDispatcher {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cdqn_cdu::GenesisPayload;
    use cdqn_hlc::HybridLogicalClock;
    use cdqn_cryptocore::hash_sha3_256;

    // Helper to create a minimal CDU
    fn create_test_cdu(statement: &str) -> Cdu {
        let hlc = HybridLogicalClock::new();
        let node_id = hash_sha3_256(b"test_node").to_vec();
        let payload = GenesisPayload {
            hardware_fingerprint: [0u8; 32],
            os: "test".to_string(),
            timestamp: 0,
            location: statement.to_string(),
        };
        Cdu::create_genesis_cdu(payload, node_id, &hlc)
    }

    #[test]
    fn test_dispatcher_publish_and_indexed_read() {
        let dispatcher = CduDispatcher::new();
        let cdu1 = create_test_cdu("Event 1");
        let cdu2 = create_test_cdu("Event 2");

        // 1. Publish CDU 1
        dispatcher.publish(cdu1.clone()).unwrap();
        assert_eq!(dispatcher.log_len(), 1);

        // 2. Publish CDU 2
        dispatcher.publish(cdu2.clone()).unwrap();
        assert_eq!(dispatcher.log_len(), 2);

        // 3. Read by index (Causal Order Check)
        let received1 = dispatcher.get_cdu_by_index(0).unwrap();
        let received2 = dispatcher.get_cdu_by_index(1).unwrap();
        
        assert_eq!(received1.id_hlc, cdu1.id_hlc);
        assert_eq!(received2.id_hlc, cdu2.id_hlc);
        
        // 4. Check out of bounds
        assert!(dispatcher.get_cdu_by_index(2).is_err());
    }

    #[test]
    fn test_dispatcher_non_blocking_full() {
        let dispatcher = CduDispatcher::new();
        let cdu = create_test_cdu("Test");

        // Fill the queue to capacity
        for _ in 0..DISPATCHER_CAPACITY {
            dispatcher.publish(cdu.clone()).unwrap();
        }

        // The next send should fail immediately (non-blocking)
        let result = dispatcher.publish(cdu.clone());
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Log is full"));
    }
}
