// crates/chronosa/src/entity.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! Defines the Sovereign Entity Hierarchy: Worker, Bot, and Agent.
//!
//! This model replaces the traditional Actor Model, separating stateless execution
//! (Worker) from stateful task management (Bot) and autonomous planning (Agent).

// FIX: Removed unused imports
use std::thread::{self, JoinHandle};

// --- Type Aliases ---
pub type EntityId = String;
pub type TaskResult = Result<(), String>;

/// 1. The Worker: A stateless entity that manages the threads queue.
/// It executes a single, short-lived, non-blocking task.
pub struct Worker;

impl Worker {
    /// Executes a task on a new thread.
    /// NOTE: This is a simple thread spawn. A true thread pool is deferred.
    pub fn spawn<F, T>(f: F) -> JoinHandle<T>
    where
        F: FnOnce() -> T + Send + 'static,
        T: Send + 'static,
    {
        thread::spawn(f)
    }
}

/// 2. The Bot: A stateful entity that is birth on a trigger event.
/// It manages Workers for workflows or long/complex tasks.
pub struct Bot {
    pub id: EntityId,
    // State is managed internally by the Bot for its specific task.
    // For example, a Bot might hold a counter or a temporary data structure.
    state: String,
}

impl Bot {
    /// Creates a new Bot instance for a specific task.
    #[must_use]
    pub fn new(task_name: &str) -> Self {
        // NOTE: In a real system, the ID would be a hash of the task_name + HLC timestamp.
        let id = format!("Bot:{}:{}", task_name, std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_millis());
        Bot {
            id,
            state: "initialized".to_string(),
        }
    }

    /// Executes a task using a Worker and waits for the result.
    pub fn execute_task<F, T>(&mut self, task_name: &str, f: F) -> Result<T, String>
    where
        F: FnOnce() -> T + Send + 'static,
        T: Send + 'static + std::fmt::Debug,
    {
        self.state = format!("running: {}", task_name);
        let handle = Worker::spawn(f);
        
        match handle.join() {
            Ok(result) => {
                self.state = format!("completed: {}", task_name);
                Ok(result)
            },
            Err(_) => {
                self.state = format!("failed: {}", task_name);
                Err(format!("Worker thread for {} panicked.", task_name))
            }
        }
    }
}

/// 3. The Agent: An autonomous, long-lived entity linked to a Chronosa's role.
/// It maintains long-term state, plans, and manages Bots/Workers.
pub struct Agent {
    pub id: EntityId,
    // Long-term state specific to the Agent's role (e.g., a cache, a reputation score).
    pub role_state: String,
}

impl Agent {
    /// Creates a new Agent instance for a specific role.
    #[must_use]
    pub fn new(role_name: &str) -> Self {
        let id = format!("Agent:{}", role_name);
        Agent {
            id,
            role_state: "ready".to_string(),
        }
    }

    /// The main loop for the Agent (e.g., subscribing to the CDU Dispatcher).
    pub fn run_loop<F>(&mut self, _loop_fn: F)
    where
        F: FnMut(&mut Self) -> TaskResult + Send + 'static,
    {
        // NOTE: The actual loop implementation is deferred to the specific role (e.g., VerifierAgent).
        // This method serves as the conceptual entry point for the Agent's autonomy.
        self.role_state = "running".to_string();
        // In a real implementation, this would be a thread that continuously calls loop_fn.
    }
}
