// crates/chronosa/src/entity.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! Defines the Sovereign Entity Hierarchy: Worker, Bot, and Agent.
//!
//! This model replaces the traditional Actor Model, separating stateless execution
//! (Worker) from stateful task management (Bot) and autonomous planning (Agent).

use std::thread::{self, JoinHandle};
use cdqn_hlc::HlcTimestamp;
use crate::dispatcher::CduDispatcher; // FIX: Removed unused LockValue import

// --- Type Aliases ---
pub type EntityId = String;
pub type TaskResult = Result<(), String>;

/// 1. The Worker: A stateless entity that manages the threads queue.
/// It executes a single, short-lived, non-blocking task.
pub struct Worker;

impl Worker {
    /// Executes a task on a new thread.
    /// NOTE: This is a simple thread spawn. A true thread pool is deferred.
    pub fn spawn<F, T>(f: F) -> JoinHandle<T>
    where
        F: FnOnce() -> T + Send + 'static,
        T: Send + 'static,
    {
        thread::spawn(f)
    }
}

/// 2. The Bot: A stateful entity that is birth on a trigger event.
/// It manages Workers for workflows or long/complex tasks.
pub struct Bot {
    pub id: EntityId,
    // FIX: The Causal ID of the task, derived from the source CDU's HLc.
    pub causal_task_id: String, 
    // State is managed internally by the Bot for its specific task.
    state: String,
}

impl Bot {
    /// Creates a new Bot instance for a specific task.
    /// FIX: Accepts the source CDU's HlcTimestamp for causal linking.
    #[must_use]
    pub fn new(task_name: &str, source_hlc: HlcTimestamp) -> Self {
        // FIX: Use stable API for thread ID and HLC for Causal Task ID
        let causal_task_id = format!(
            "Task:{}:{}:{}", 
            source_hlc.as_u64(), 
            format!("{:?}", thread::current().id()), // Stable, unique thread ID string
            task_name
        );
        
        let id = format!("Bot:{}", task_name);
        Bot {
            id,
            causal_task_id,
            state: "initialized".to_string(),
        }
    }

    /// Executes a task using a Worker and waits for the result.
    /// The closure must return a Result<T, String>.
    /// FIX: Added dispatcher and cdu_id for CTL
    pub fn execute_task<F, T>(&mut self, task_type: &str, cdu_id: Vec<u8>, dispatcher: &CduDispatcher, f: F) -> Result<T, String>
    where
        F: FnOnce() -> Result<T, String> + Send + 'static,
        T: Send + 'static + std::fmt::Debug,
    {
        let lock_value = (thread::current().id(), self.causal_task_id.clone());
        let task_type_string = task_type.to_string();

        // 1. Acquire Causal Task Lock (CTL)
        dispatcher.acquire_lock(cdu_id.clone(), task_type_string.clone(), lock_value.clone())
            .map_err(|e| format!("CTL Acquisition Failed: {}", e))?;

        self.state = format!("running: {}", task_type);
        println!("BOT START: {} (Causal ID: {})", self.id, self.causal_task_id);
        
        let handle = Worker::spawn(f);
        
        let result = match handle.join() {
            Ok(inner_result) => {
                match inner_result {
                    Ok(val) => {
                        self.state = format!("completed: {}", task_type);
                        println!("BOT END: {} (Causal ID: {}) -> Success", self.id, self.causal_task_id);
                        Ok(val)
                    }
                    Err(e) => {
                        self.state = format!("failed: {}", task_type);
                        eprintln!("BOT END: {} (Causal ID: {}) -> Failure: {}", self.id, self.causal_task_id, e);
                        Err(e)
                    }
                }
            },
            Err(_) => {
                self.state = format!("failed: {}", task_type);
                eprintln!("BOT END: {} (Causal ID: {}) -> Thread Panic", self.id, self.causal_task_id);
                Err(format!("Worker thread for {} panicked.", task_type))
            }
        };

        // 2. Release Causal Task Lock (CTL)
        dispatcher.release_lock(cdu_id, task_type_string, &lock_value) // FIX: Pass reference
            .map_err(|e| format!("CTL Release Failed: {}", e))?;

        result
    }
}

/// 3. The Agent: An autonomous, long-lived entity linked to a Chronosa's role.
/// It maintains long-term state, plans, and manages Bots/Workers.
pub struct Agent {
    pub id: EntityId,
    // Long-term state specific to the Agent's role (e.g., a cache, a reputation score).
    pub role_state: String,
}

impl Agent {
    /// Creates a new Agent instance for a specific role.
    #[must_use]
    pub fn new(role_name: &str) -> Self {
        let id = format!("Agent:{}", role_name);
        Agent {
            id,
            role_state: "ready".to_string(),
        }
    }

    /// The main loop for the Agent (e.g., subscribing to the CDU Dispatcher).
    pub fn run_loop<F>(&mut self, _loop_fn: F)
    where
        F: FnMut(&mut Self) -> TaskResult + Send + 'static,
    {
        // NOTE: The actual loop implementation is deferred to the specific role (e.g., VerifierAgent).
        // This method serves as the conceptual entry point for the Agent's autonomy.
        self.role_state = "running".to_string();
        // In a real implementation, this would be a thread that continuously calls loop_fn.
    }
}
