// crates/chronosa/src/lib.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! Chronosa: the sovereign cognitive architecture of the CDQN node.
//!
//! Implements the custom Entity Model (Worker, Bot, Agent) and the core
//! reasoning roles (Verifier, Policy, etc.) that operate on the Manifold.

// Core Modules
mod dispatcher;
mod entity;
// mod runtime; // FIX: Removed, now in cdqn-runtime crate

// Chronosa Roles (Agents)
mod roles;

// Re-export public types
pub use dispatcher::CduDispatcher;
pub use entity::{Worker, Bot, Agent};
pub use roles::verifier::VerifierAgent;
pub use roles::evolution::EvolutionAgent; // FIX: Added EvolutionAgent re-export

// Placeholder for the main Chronosa runtime struct
pub struct ChronosaNode;
