// crates/cdu/src/types/constructors.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use super::core::{Cdu, Payload, Metadata};
use crate::payloads::{ConfigPayload, GenesisPayload, AxiomPayload};
use crate::worlds::World;
use cdqn_cryptocore::hash_sha3_256;
use cdqn_hlc::{HlcTimestamp, HybridLogicalClock};
use std::collections::{HashSet, HashMap}; // FIX: Added HashMap

impl Cdu {
    /// Creates a new CDU with a given payload and metadata, generating its ID.
    #[must_use]
    pub fn new(
        payload: Payload,
        mut metadata: Metadata,
        hlc: &HybridLogicalClock,
        node_id: &[u8],
    ) -> Self {
        let payload_hash = payload.hash();
        let hlc_ts = hlc.new_timestamp();
        metadata.hlc_timestamp = hlc_ts;

        let mut id_input = hlc_ts.as_u64().to_be_bytes().to_vec();
        id_input.extend_from_slice(node_id);
        id_input.extend_from_slice(&payload_hash);

        let id_hlc = hash_sha3_256(&id_input).to_vec();

        Self {
            id_hlc,
            payload_hash,
            payload,
            metadata,
            signatures: Vec::new(),
        }
    }

    /// Creates the sovereign Genesis CDU for a node.
    /// This CDU is unique and serves as the root of trust.
    #[must_use]
    pub fn create_genesis_cdu(
        genesis_payload: GenesisPayload,
        author_node: Vec<u8>,
        hlc: &HybridLogicalClock,
    ) -> Self {
        let payload = genesis_payload.into_payload();
        let metadata = Metadata {
            author_node: author_node.clone(),
            context_refs: vec![],
            state: "active".to_string(),
            weight: 1.0,
            r_coordinate: 0.0,
            world_context: World::CdqnWorld,
            hlc_timestamp: HlcTimestamp::new(0, 0),
            symmetric_counterpart: None,
            validated_worlds: HashSet::new(),
            task_footprints: HashMap::new(), // FIX: Initialize new field
        };

        Self::new(payload, metadata, hlc, &author_node)
    }

    /// Creates the foundational Axiom CDU that represents the node's own existence.
    /// This Axiom is a child of the Genesis CDU and is immediately validated
    /// in the three worlds where the Genesis CDU is "present".
    #[must_use]
    pub fn create_foundational_axiom_for(
        genesis_cdu_id: &[u8],
        author_node: Vec<u8>,
        hlc: &HybridLogicalClock,
    ) -> Self {
        let axiom_payload = AxiomPayload {
            statement: "This node exists and its reasoning is sovereign.".to_string(),
        };
        let payload = axiom_payload.into_payload();

        let mut validated_worlds = HashSet::new();
        validated_worlds.insert(World::UserWorld);
        validated_worlds.insert(World::LangCodingWorld);
        validated_worlds.insert(World::CdqnWorld);

        let metadata = Metadata {
            author_node,
            context_refs: vec![genesis_cdu_id.to_vec()], // Links to its parent, the Genesis CDU.
            state: "active".to_string(),
            weight: 1.0,
            r_coordinate: 2.0, // A positive, foundational axiom.
            world_context: World::UserWorld, // The primary context for this axiom.
            hlc_timestamp: HlcTimestamp::new(0, 0),
            symmetric_counterpart: None,
            validated_worlds,
            task_footprints: HashMap::new(), // FIX: Initialize new field
        };

        Self::new(payload, metadata, hlc, &[])
    }

    /// Creates a new Semi-Axiom CDU.
    /// The semi-axiom is initially only validated in its own world.
    #[must_use]
    pub fn new_semi_axiom(
        statement: String,
        origin_world: World,
        author_node: Vec<u8>,
        hlc: &HybridLogicalClock,
    ) -> Self {
        let axiom_payload = AxiomPayload { statement };
        let payload = axiom_payload.into_payload();
        let payload_hash = payload.hash();
        let hlc_ts = hlc.new_timestamp();

        let mut id_input = hlc_ts.as_u64().to_be_bytes().to_vec();
        id_input.extend_from_slice(&author_node);
        id_input.extend_from_slice(&payload_hash);
        let id_hlc = hash_sha3_256(&id_input).to_vec();

        let mut validated_worlds = HashSet::new();
        validated_worlds.insert(origin_world);

        let metadata = Metadata {
            author_node,
            context_refs: vec![],
            state: "active".to_string(),
            weight: 1.0,
            r_coordinate: 0.0,
            world_context: origin_world,
            hlc_timestamp: hlc_ts,
            symmetric_counterpart: None,
            validated_worlds,
            task_footprints: HashMap::new(), // FIX: Initialize new field
        };

        Self {
            id_hlc,
            payload_hash,
            payload,
            metadata,
            signatures: Vec::new(),
        }
    }

    /// A performance-oriented convenience constructor for creating a `ConfigCDU`.
    #[must_use]
    pub fn new_config(
        settings: std::collections::HashMap<String, serde_json::Value>,
        author_node: Vec<u8>,
        hlc: &HybridLogicalClock,
        parent_id: &[u8],
    ) -> Self {
        let config_payload = ConfigPayload { settings };
        let payload = config_payload.into_payload();
        let payload_hash = payload.hash();
        let hlc_ts = hlc.new_timestamp();

        let mut id_input = hlc_ts.as_u64().to_be_bytes().to_vec();
        id_input.extend_from_slice(&author_node);
        id_input.extend_from_slice(&payload_hash);
        let id_hlc = hash_sha3_256(&id_input).to_vec();

        let metadata = Metadata {
            author_node,
            context_refs: vec![parent_id.to_vec()],
            state: "active".to_string(),
            weight: 1.0,
            r_coordinate: 0.0,
            world_context: World::UserWorld,
            hlc_timestamp: hlc_ts,
            symmetric_counterpart: None,
            validated_worlds: HashSet::new(),
            task_footprints: HashMap::new(), // FIX: Initialize new field
        };

        Self {
            id_hlc,
            payload_hash,
            payload,
            metadata,
            signatures: Vec::new(),
        }
    }
}
