// crates/cdu/src/types/core.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use crate::worlds::World;
use cdqn_cryptocore::hash_sha3_256;
use cdqn_hlc::HlcTimestamp;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;

/// The immutable core content of a CDU.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Payload {
    /// The raw byte data of the payload.
    pub data: Vec<u8>,
    /// A string identifier for the payload's type (e.g., "genesis/v1").
    pub payload_type: String,
}

impl Payload {
    /// Computes the SHA3-256 hash of the payload's canonical representation.
    #[must_use]
    pub fn hash(&self) -> [u8; 32] {
        let mut canonical = self.payload_type.as_bytes().to_vec();
        canonical.extend_from_slice(&self.data);
        hash_sha3_256(&canonical)
    }
}

/// The mutable context surrounding a CDU's payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Metadata {
    /// The ID of the node that created the CDU.
    pub author_node: Vec<u8>,
    /// A list of `id_hlc`s of causal parent CDUs.
    pub context_refs: Vec<Vec<u8>>,
    /// The current state of the CDU (e.g., "active", "merged").
    pub state: String,
    /// The influence and trustworthiness score of the CDU.
    pub weight: f64,
    /// The CDU's position in the RWorld mathematical space.
    pub r_coordinate: f64,
    /// The logical partition (e.g., UserWorld) the CDU belongs to.
    pub world_context: World,
    /// The raw HLC timestamp used for ID generation.
    pub hlc_timestamp: HlcTimestamp,
    /// Optional field to link to a symmetric counterpart, used for Semi-Axioms.
    pub symmetric_counterpart: Option<Vec<u8>>,
    /// A set of worlds where this CDU has been validated as a semi-axiom.
    pub validated_worlds: HashSet<World>,
}

/// An entry in the append-only signature log of a CDU.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signature {
    /// The identifier of the entity that signed the CDU.
    pub signer_entity: String,
    /// The timestamp of when the signature was created.
    pub timestamp: HlcTimestamp,
    /// The raw signature bytes.
    pub signature: Vec<u8>,
}

/// The complete Causal Data Unit, the atom of knowledge.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Cdu {
    /// The unique, deterministic, and permanent identifier.
    pub id_hlc: Vec<u8>,
    /// The immutable core content.
    pub payload: Payload,
    /// The cryptographic hash of the payload's canonical bytes.
    pub payload_hash: [u8; 32],
    /// The mutable context.
    pub metadata: Metadata,
    /// An append-only log of signatures.
    pub signatures: Vec<Signature>,
}
