// crates/cdu/src/types/integrity.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use super::core::{Cdu, Payload, Metadata}; // FIX: Added Metadata import
use crate::payloads::{ConfigPayload, GenesisPayload, AxiomPayload};
use crate::worlds::World;
use cdqn_cryptocore::SignerEntity;
use cdqn_hlc::HybridLogicalClock;
use serde::Serialize;

impl Cdu {
    /// Generates the canonical byte representation of the CDU for signing.
    /// This excludes the `signatures` field itself, as the signature is over the content.
    #[must_use]
    pub fn canonical_bytes_for_signing(&self) -> Vec<u8> {
        // Create a temporary struct that mirrors CDU but omits the signatures field.
        #[derive(Serialize)]
        struct CduForSigning<'a> {
            id_hlc: &'a Vec<u8>,
            payload: &'a Payload,
            payload_hash: &'a [u8; 32],
            metadata: &'a Metadata,
        }

        let temp_cdu = CduForSigning {
            id_hlc: &self.id_hlc,
            payload: &self.payload,
            payload_hash: &self.payload_hash,
            metadata: &self.metadata,
        };

        // Use a deterministic serialization format (standard JSON is used here)
        serde_json::to_vec(&temp_cdu).expect("Failed to serialize CDU for signing")
    }

    /// Signs the CDU using the provided SignerEntity and adds the signature to the audit trail.
    pub fn sign(&mut self, signer: &SignerEntity, hlc: &HybridLogicalClock) -> Result<(), &'static str> {
        let message = self.canonical_bytes_for_signing();
        let signature_bytes = signer.sign_message(&message)?;

        let signature_entry = super::core::Signature {
            signer_entity: signer.entity_id.clone(),
            timestamp: hlc.new_timestamp(),
            signature: signature_bytes,
        };

        self.signatures.push(signature_entry);
        Ok(())
    }

    /// Verifies all signatures on the CDU.
    /// NOTE: This is a simplified check that assumes the signer_entity string contains the public key hash.
    pub fn verify_signatures(&self) -> Result<(), String> {
        let _message = self.canonical_bytes_for_signing(); // FIX: Added underscore to allow dead_code
        
        for sig_entry in &self.signatures {
            // In a real system, we would look up the public key from the signer_entity ID.
            // For this test, we assume the signer_entity is a known, trusted ID.
            
            // Placeholder: We cannot verify without the actual public key, so we only check the signature format.
            // The full verification logic is deferred to the Verifier Agent.
            if sig_entry.signature.len() != 64 {
                return Err(format!("Signature verification failed for {}: Invalid length.", sig_entry.signer_entity));
            }
        }
        Ok(())
    }

    /// Validates this Semi-Axiom CDU in another world.
    /// Returns `true` if the world was newly added, `false` if it was already present.
    pub fn validate_in_world(&mut self, world: World) -> bool {
        self.metadata.validated_worlds.insert(world)
    }

    /// Determines if a CDU has achieved the status of a full Axiom.
    /// An Axiom is a Semi-Axiom that is validated in the UserWorld and at least
    /// two other worlds.
    #[must_use]
    pub fn is_axiom(&self) -> bool {
        if self.payload.payload_type != "axiom/v1" {
            return false;
        }
        let is_valid_in_user_world = self.metadata.validated_worlds.contains(&World::UserWorld);
        let count_other_worlds = self.metadata.validated_worlds.len()
            - if is_valid_in_user_world { 1 } else { 0 };

        is_valid_in_user_world && count_other_worlds >= 2
    }

    /// Returns true if this CDU is the Genesis CDU of the node.
    #[must_use]
    pub fn is_genesis(&self) -> bool {
        if self.payload.payload_type != "genesis/v1" {
            return false;
        }
        true
    }

    /// Attempts to interpret the CDU as a `ConfigCDU`.
    pub fn as_config(&self) -> Option<ConfigPayload> {
        if self.payload.payload_type != "config/v1" {
            return None;
        }
        serde_json::from_slice(&self.payload.data).ok()
    }

    /// Attempts to interpret the CDU as an `AxiomCDU`.
    pub fn as_axiom(&self) -> Option<AxiomPayload> {
        if self.payload.payload_type != "axiom/v1" {
            return None;
        }
        serde_json::from_slice(&self.payload.data).ok()
    }

    /// Attempts to interpret the CDU as a `GenesisPayload`.
    pub fn as_genesis(&self) -> Option<GenesisPayload> {
        if self.payload.payload_type != "genesis/v1" {
            return None;
        }
        serde_json::from_slice(&self.payload.data).ok()
    }
}
