// crates/cdu/src/types/mod.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

mod core;
mod constructors;
mod integrity;

// Re-export the core types
pub use core::{Cdu, Metadata, Payload, Signature};
