// crates/cryptocore/src/lib.rs
// File under the BaDaaS license, code generated by the ai assistant: Qwen3-Max, Alibaba

//! Minimal, auditable cryptographic core for the CDQN ecosystem.
//!
//! Provides:
//! - SHA3-256 hashing
//! - HKDF-based key derivation (using byte slices as salt)
//! - ChaCha20Poly1305 for authenticated encryption
//! - Secure zeroization of secrets

pub use chacha20poly1305::{AeadCore, AeadInPlace, ChaCha20Poly1305, Key, Nonce};
pub use hkdf::Hkdf;
pub use sha3::{Digest, Sha3_256};
pub use zeroize::Zeroize;
