// cdqn/crates/cryptocore/src/lib.rs
// File under the BaDaaS license, code generated by ai assistant: Gemini 2.5 Pro, Google

use ed25519_dalek::{Signature, Signer, Verifier, VerifyingKey, SigningKey};
use rand::rngs::OsRng;
use sha3::{Digest, Sha3_256};
use serde::{Serialize, Deserialize};

/// A unique, unforgeable identifier for a CDQN Node, which is its public key.
/// We re-export `VerifyingKey` as `NodeId` to provide semantic clarity throughout the ecosystem.
pub type NodeId = VerifyingKey;

/// The standard output of our hashing function (SHA3-256 -> 32 bytes).
pub type HashDigest = [u8; 32];

/// Defines the essential, non-negotiable cryptographic capabilities for a CDQN node.
/// This trait serves as the public API for the cryptocore module, ensuring modularity.
pub trait CryptoOperations {
    /// Returns the node's unique, cryptographic identifier (its public key).
    fn node_id(&self) -> &NodeId;

    /// Generates a SHA3-256 hash of a canonical byte slice.
    /// This is a pure function, guaranteeing deterministic output for a given input.
    fn hash(data: &[u8]) -> HashDigest;

    /// Signs a given hash (not the raw data) with the node's private signing key.
    /// This enforces a pattern of "hash-then-sign".
    fn sign(&self, hash: &HashDigest) -> Signature;

    /// Verifies a signature against a hash using a given public key (NodeId).
    /// This is a pure function.
    fn verify(node_id: &NodeId, hash: &HashDigest, signature: &Signature) -> bool;
}

/// A concrete implementation of `CryptoOperations` that holds a node's keypair.
#[derive(Serialize, Deserialize)]
pub struct NodeKeys {
    // The private part of the keypair, used for signing.
    // WARNING: This must be kept secret and handled securely.
    signing_key: SigningKey,
}

impl NodeKeys {
    /// Generates a new, cryptographically secure keypair for a new node.
    /// Uses the operating system's entropy source for randomness.
    pub fn new() -> Self {
        let mut csprng = OsRng;
        let signing_key = SigningKey::generate(&mut csprng);
        Self { signing_key }
    }
}

impl Default for NodeKeys {
    /// Provides a default constructor for convenience.
    fn default() -> Self {
        Self::new()
    }
}

impl CryptoOperations for NodeKeys {
    fn node_id(&self) -> &NodeId {
        // The public key is derived from the signing key.
        self.signing_key.verifying_key()
    }

    fn hash(data: &[u8]) -> HashDigest {
        let mut hasher = Sha3_256::new();
        hasher.update(data);
        hasher.finalize().into()
    }

    fn sign(&self, hash: &HashDigest) -> Signature {
        self.signing_key.sign(hash)
    }

    fn verify(node_id: &NodeId, hash: &HashDigest, signature: &Signature) -> bool {
        node_id.verify(hash, signature).is_ok()
    }
}


// --- Unit Tests ---
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hash_consistency() {
        let data1 = b"Chronosa is a Self-Correcting Causal Organism";
        let data2 = b"Chronosa is a Self-Correcting Causal Organism";
        
        let hash1 = NodeKeys::hash(data1);
        let hash2 = NodeKeys::hash(data2);

        assert_eq!(hash1, hash2, "Hashing the same data should produce the same hash.");
    }

    #[test]
    fn test_hash_uniqueness() {
        let data1 = b"data";
        let data2 = b"data."; // Note the extra period

        let hash1 = NodeKeys::hash(data1);
        let hash2 = NodeKeys::hash(data2);

        assert_ne!(hash1, hash2, "Hashing different data should produce different hashes.");
    }

    #[test]
    fn test_sign_verify_roundtrip_success() {
        let node = NodeKeys::new();
        let data = b"This data must be signed and verified correctly.";
        
        let hash = NodeKeys::hash(data);
        let signature = node.sign(&hash);
        
        let is_valid = NodeKeys::verify(node.node_id(), &hash, &signature);

        assert!(is_valid, "A valid signature should be verified successfully by its own public key.");
    }

    #[test]
    fn test_verify_fails_on_tampered_data() {
        let node = NodeKeys::new();
        let original_data = b"This is the original, untampered data.";
        let tampered_data = b"This is the tampered data!";

        let original_hash = NodeKeys::hash(original_data);
        let tampered_hash = NodeKeys::hash(tampered_data);
        
        let signature = node.sign(&original_hash);
        
        // Verification should fail because the signature was for the original hash, not the tampered one.
        let is_valid = NodeKeys::verify(node.node_id(), &tampered_hash, &signature);

        assert!(!is_valid, "Verification must fail if the data hash does not match the signed hash.");
    }

    #[test]
    fn test_verify_fails_on_wrong_key() {
        let node_a = NodeKeys::new();
        let node_b = NodeKeys::new(); // A different node with a different keypair.
        let data = b"Data signed by Node A.";

        let hash = NodeKeys::hash(data);
        let signature_from_a = node_a.sign(&hash);

        // Try to verify Node A's signature using Node B's public key.
        let is_valid = NodeKeys::verify(node_b.node_id(), &hash, &signature_from_a);

        assert!(!is_valid, "Verification must fail if performed with a public key that does not match the signing key.");
    }
}
