// crates/chronosa/src/roles/mod.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

// Declare all Chronosa Role Agents
pub mod verifier;
pub mod evolution; // FIX: Added new evolution module
// pub mod policy; // Deferred
// pub mod consolidator; // Deferred

// Re-export public types
pub use verifier::VerifierAgent;
pub use evolution::EvolutionAgent; // FIX: Export new Agent
