// crates/chronosa/src/roles/mod.rs
// File under the BaDaaS license, code generated by the ai model: Claude-Opus-4-search, Anthropic

// Declare all Chronosa Role Agents
pub mod verifier;
pub mod evolution;
// pub mod policy; // Deferred
// pub mod consolidator; // Deferred

// NOTE: VerifierAgent and EvolutionAgent are already re-exported
// from the lib.rs file, so we don't need to re-export them here
