// crates/chronosa/src/dispatcher/bus.rs
// File under the BaDaaS license, code generated by the ai model: Claude-Opus-4-search, Anthropic

use super::core::{CduDispatcher, DISPATCHER_CAPACITY};
use cdqn_cdu::Cdu;
use std::sync::Arc;

impl CduDispatcher {
    /// Publishes a new CDU to the log (Send-and-Forget).
    ///
    /// This is a non-blocking operation. Returns an error if the log is full.
    pub fn publish(&self, cdu: Cdu) -> Result<(), String> {
        let arc_cdu = Arc::new(cdu);
        let mut shared = self.shared.lock().map_err(|_| "Dispatcher lock poisoned")?;

        if shared.log.len() >= DISPATCHER_CAPACITY {
            return Err("Causal Log is full (Archival needed)".to_string());
        }

        shared.log.push_back(arc_cdu);
        
        // Signal all waiting Agents that a new CDU is available
        self.new_cdu_signal.notify_all();
        
        Ok(())
    }

    /// Blocks the current thread until a new CDU is available in the log.
    /// This is the zero-CPU-cost waiting mechanism for Agents.
    pub fn wait_for_new_cdu(&self, last_known_len: usize) -> Result<(), String> {
        let mut shared = self.shared.lock().map_err(|_| "Dispatcher lock poisoned")?;

        // Wait until the log length is greater than the last known length
        while shared.log.len() <= last_known_len {
            shared = self.new_cdu_signal.wait(shared).map_err(|_| "Condvar wait failed")?;
        }
        
        Ok(())
    }

    /// Retrieves a CDU from the log based on an index (Watermark).
    pub fn get_cdu_by_index(&self, index: usize) -> Result<Arc<Cdu>, String> {
        let log = self.shared.lock().map_err(|_| "Dispatcher lock poisoned")?;

        log.log.get(index)
            .cloned()
            .ok_or_else(|| format!("Causal Log index {} out of bounds", index))
    }
}
