// crates/chronosa/src/dispatcher/core.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use cdqn_cdu::Cdu;
use std::sync::{Arc, Mutex, Condvar};
use std::collections::{VecDeque, HashMap};
use std::thread::ThreadId;

// The capacity of the log (for memory management).
pub const DISPATCHER_CAPACITY: usize = 1024;

// --- Type Aliases for CTL ---
pub type CduId = Vec<u8>;
pub type TaskType = String;
pub type LockKey = (CduId, TaskType);
pub type LockValue = (ThreadId, String); // (ThreadId, CausalTaskId)

/// The core state shared between all Senders and Receivers.
pub struct DispatcherState {
    pub log: VecDeque<Arc<Cdu>>,
    pub task_locks: HashMap<LockKey, LockValue>,
}

/// The central Causal Event Bus.
pub struct CduDispatcher {
    pub shared: Arc<Mutex<DispatcherState>>,
    pub new_cdu_signal: Condvar, 
}

impl CduDispatcher {
    /// Creates a new CduDispatcher.
    #[must_use]
    pub fn new() -> Self {
        CduDispatcher {
            shared: Arc::new(Mutex::new(DispatcherState {
                log: VecDeque::with_capacity(DISPATCHER_CAPACITY),
                task_locks: HashMap::new(),
            })),
            new_cdu_signal: Condvar::new(),
        }
    }

    /// Returns the current length of the log (the next index to read).
    #[must_use]
    pub fn log_len(&self) -> usize {
        self.shared.lock().map(|l| l.log.len()).unwrap_or(0)
    }

    /// Creates a clone of the dispatcher for another Agent to use.
    #[must_use]
    pub fn clone_for_agent(&self) -> Self {
        CduDispatcher {
            shared: self.shared.clone(),
            new_cdu_signal: self.new_cdu_signal.clone(),
        }
    }
}
