// crates/chronosa/src/dispatcher/ctl.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use super::core::{CduDispatcher, CduId, TaskType, LockValue};

impl CduDispatcher {
    /// Attempts to acquire a Causal Task Lock (CTL) for a specific CDU and Task.
    /// Returns Ok(()) if the lock is acquired, or Err if it is already held.
    pub fn acquire_lock(&self, cdu_id: CduId, task_type: TaskType, lock_value: LockValue) -> Result<(), String> {
        let mut shared = self.shared.lock().map_err(|_| "Dispatcher lock poisoned")?;
        let lock_key = (cdu_id, task_type);

        if shared.task_locks.contains_key(&lock_key) {
            return Err("Lock already held".to_string());
        }

        shared.task_locks.insert(lock_key, lock_value);
        Ok(())
    }

    /// Releases a Causal Task Lock (CTL). Only the holder can release the lock.
    pub fn release_lock(&self, cdu_id: CduId, task_type: TaskType, lock_value: &LockValue) -> Result<(), String> {
        let mut shared = self.shared.lock().map_err(|_| "Dispatcher lock poisoned")?;
        let lock_key = (cdu_id, task_type);

        match shared.task_locks.get(&lock_key) {
            Some(current_value) if current_value == lock_value => {
                shared.task_locks.remove(&lock_key);
                Ok(())
            }
            Some(_) => Err("Lock held by another thread/task".to_string()),
            None => Err("Lock not found".to_string()),
        }
    }
}
