// crates/chronosa/src/dispatcher/mod.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

mod core;
mod ctl;
mod bus;

#[cfg(test)]
mod tests; // FIX: Declared test module

// Re-export the core dispatcher struct and types
pub use core::{CduDispatcher, CduId, TaskType, LockValue}; // FIX: Cleaned up unused imports
