// crates/chronosa/src/dispatcher/mod.rs
// File under the BaDaaS license, code generated by the ai model: Claude-Opus-4-search, Anthropic

mod core;
mod ctl;
mod bus;

#[cfg(test)]
mod tests;

// Re-export only the actually used dispatcher struct
pub use core::CduDispatcher;
