// crates/chronosa/src/dispatcher/tests.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use super::core::DISPATCHER_CAPACITY;
use crate::dispatcher::{CduDispatcher, LockValue};
use cdqn_cdu::GenesisPayload;
use cdqn_hlc::HybridLogicalClock;
use cdqn_cryptocore::hash_sha3_256;
use std::thread;
use std::time::Duration;
use std::sync::Arc;

// Helper to create a minimal CDU
fn create_test_cdu(statement: &str) -> cdqn_cdu::Cdu {
    let hlc = HybridLogicalClock::new();
    let node_id = hash_sha3_256(b"test_node").to_vec();
    let payload = GenesisPayload {
        hardware_fingerprint: [0u8; 32],
        os: "test".to_string(),
        timestamp: 0,
        location: statement.to_string(),
    };
    cdqn_cdu::Cdu::create_genesis_cdu(payload, node_id, &hlc)
}

#[test]
fn test_dispatcher_publish_and_indexed_read() {
    let dispatcher = CduDispatcher::new();
    let cdu1 = create_test_cdu("Event 1");
    let cdu2 = create_test_cdu("Event 2");

    // 1. Publish CDU 1
    dispatcher.publish(cdu1.clone()).unwrap();
    assert_eq!(dispatcher.log_len(), 1);

    // 2. Publish CDU 2
    dispatcher.publish(cdu2.clone()).unwrap();
    assert_eq!(dispatcher.log_len(), 2);

    // 3. Read by index (Causal Order Check)
    let received1 = dispatcher.get_cdu_by_index(0).unwrap();
    let received2 = dispatcher.get_cdu_by_index(1).unwrap();
    
    assert_eq!(received1.id_hlc, cdu1.id_hlc);
    assert_eq!(received2.id_hlc, cdu2.id_hlc);
    
    // 4. Check out of bounds
    assert!(dispatcher.get_cdu_by_index(2).is_err());
}

#[test]
fn test_dispatcher_non_blocking_full() {
    let dispatcher = CduDispatcher::new();
    let cdu = create_test_cdu("Test");

    // Fill the queue to capacity
    for _ in 0..DISPATCHER_CAPACITY {
        dispatcher.publish(cdu.clone()).unwrap();
    }

    // The next send should fail immediately (non-blocking)
    let result = dispatcher.publish(cdu.clone());
    assert!(result.is_err());
    assert!(result.unwrap_err().contains("Log is full"));
}

#[test]
fn test_dispatcher_ctl_acquire_and_release() {
    let dispatcher = CduDispatcher::new();
    let cdu = create_test_cdu("Test");
    let cdu_id = cdu.id_hlc.clone();
    let task_type = "fetch_cdu".to_string();
    let lock_value = (thread::current().id(), "Task:123".to_string());

    // 1. Acquire Lock
    assert!(dispatcher.acquire_lock(cdu_id.clone(), task_type.clone(), lock_value.clone()).is_ok());

    // 2. Attempt to re-acquire (should fail)
    assert!(dispatcher.acquire_lock(cdu_id.clone(), task_type.clone(), lock_value.clone()).is_err());

    // 3. Attempt to release with wrong value (should fail)
    let wrong_value = (thread::current().id(), "Task:456".to_string());
    assert!(dispatcher.release_lock(cdu_id.clone(), task_type.clone(), &wrong_value).is_err());

    // 4. Release Lock
    assert!(dispatcher.release_lock(cdu_id.clone(), task_type.clone(), &lock_value).is_ok());

    // 5. Attempt to re-acquire (should succeed)
    assert!(dispatcher.acquire_lock(cdu_id, task_type, lock_value).is_ok());
}

#[test]
fn test_dispatcher_wait_for_new_cdu() {
    let dispatcher = Arc::new(CduDispatcher::new());
    let dispatcher_clone = dispatcher.clone();
    let cdu = create_test_cdu("Wait Test");
    let initial_len = dispatcher.log_len();

    // Thread 1: Wait for a new CDU
    let waiter_handle = thread::spawn(move || {
        // This will block until a CDU is published
        dispatcher_clone.wait_for_new_cdu(initial_len).unwrap();
        dispatcher_clone.log_len()
    });

    // Thread 2: Publish a CDU after a short delay
    thread::sleep(Duration::from_millis(10));
    dispatcher.publish(cdu).unwrap();

    // The waiter thread should unblock and return the new length (1)
    let final_len = waiter_handle.join().unwrap();
    assert_eq!(final_len, initial_len + 1);
}
