// wit/worker.wit

// Define a package namespace for our component.
package local:hello-world;

// Define an interface that the component will implement.
interface worker {
    // This is the function we export.
    run: func();
}
