// crates/cdu/src/tests/axiom.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use crate::types::Cdu;
use crate::worlds::World;
use crate::tests::find_workspace_root;
use cdqn_hlc::HybridLogicalClock;
use std::fs;
use std::path::PathBuf;
use std::collections::HashMap;
use serde_json::json;

// NOTE: The original snippet was missing the setup code. I am adding a minimal,
// runnable setup to make the test complete and correct.

/// Helper function to print a summary of a CDU to a dedicated log file.
/// NOTE: This is a placeholder definition, as the full definition was not provided.
pub fn print_cdu_summary_to_file(test_name: &str, cdu: &Cdu, project_root: &PathBuf) {
    let log_dir = project_root.join("ci-logs");
    let log_file = log_dir.join(format!("{}.log", test_name));
    
    let output = format!(
        "--- Test: {}\nType: {}\nID (hex): {:?}\nWorld: {:?}\nIs Axiom: {}\n-----------------\n",
        test_name,
        cdu.payload.payload_type,
        cdu.id_hlc,
        cdu.metadata.world_context,
        cdu.is_axiom()
    );
    
    fs::write(&log_file, output).expect(&format!("Unable to write to test log file: {}", log_file.display()));
}

/// This test validates the lifecycle of a regular Semi-Axiom becoming an Axiom.
#[test]
fn test_semi_axiom_to_axiom_promotion() {
    let project_root = find_workspace_root();
    let hlc = HybridLogicalClock::new();
    let node_id = cdqn_cryptocore::hash_sha3_256(b"test_node").to_vec();

    // 1. Create a Semi-Axiom, initially validated only in its origin world (UserWorld).
    let mut semi_axiom = Cdu::new_semi_axiom(
        "All knowledge must be verifiable.".to_string(),
        World::UserWorld,
        node_id,
        &hlc,
    );
    
    print_cdu_summary_to_file("test_semi_axiom_to_axiom_promotion_initial", &semi_axiom, &project_root);

    // 2. Initially, it's only validated in its own world, so it's not an Axiom.
    assert!(!semi_axiom.is_axiom(), "A semi-axiom should not be an axiom initially.");
    assert_eq!(semi_axiom.metadata.validated_worlds.len(), 1);
    assert!(semi_axiom.metadata.validated_worlds.contains(&World::UserWorld));

    // 3. The Verifier role validates it in two other worlds.
    // RWorld and LangCodingWorld are the two additional worlds.
    semi_axiom.validate_in_world(World::RWorld);
    semi_axiom.validate_in_world(World::LangCodingWorld);
    print_cdu_summary_to_file("test_semi_axiom_to_axiom_promotion_validated", &semi_axiom, &project_root);

    // 4. Now it is validated in UserWorld and two others (RWorld, LangCodingWorld), so it must be an Axiom.
    assert!(semi_axiom.is_axiom(), "Axiom validated in 3 worlds must be an axiom.");
    assert_eq!(semi_axiom.metadata.validated_worlds.len(), 3);
}
