// crates/cdu/src/tests/axiom.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, an AI assistant from chat.z.ai

use crate::types::Cdu;
use crate::worlds::World;
use crate::super::find_workspace_root;
use cdqn_hlc::HybridLogicalClock;
use std::fs;
use std::path::PathBuf;

/// This test validates the lifecycle of a regular Semi-Axiom becoming an Axiom.
#[test]
fn test_semi_axiom_to_axiom_promotion() {
    let project_root = find_workspace_root();
    let log_dir = print_cdu_summary_to_file("test_semi_axiom_to_axiom_promotion_initial", &semi_axiom, &project_root);

    // 2. Initially, it's only validated in its own world, so it's not an Axiom.
    assert!(!semi_axiom.is_axiom(), "A semi-axiom should not be an axiom initially.");
    assert_eq!(semi_axiom.metadata.validated_worlds.len(), 1);

    // 3. The Verifier role validates it in two other worlds.
    semi_axiom.validate_in_world(World::RWorld);
    semi_axiom.validate_in_world(World::LangCodingWorld);
    print_cdu_summary_to_file("test_semi_axiom_to_axiom_promotion_validated", &semi_axiom, &project_root);

    // 4. Now it is validated in UserWorld and two others, so it must be an Axiom.
    assert!(semi_axiom.is_axiom(), "Axiom validated in 3 worlds must be an axiom.");
    assert_eq!(semi_axiom.is_axiom());
    assert_eq!(semi_axiom.metadata.validated_worlds.len(), 3);
}
