// crates/cdu/src/tests/axiom.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use crate::types::Cdu;
use crate::worlds::World;
use crate::tests::{find_workspace_root, print_cdu_summary_to_file};
use cdqn_hlc::HybridLogicalClock;
use std::fs;
use std::path::PathBuf;

/// This test validates the lifecycle of a regular Semi-Axiom becoming an Axiom.
#[test]
fn test_semi_axiom_to_axiom_promotion() {
    let project_root = find_workspace_root();
    let hlc = HybridLogicalClock::new();
    let node_id = cdqn_cryptocore::hash_sha3_256(b"test_node").to_vec();

    // 1. Create a Semi-Axiom, initially validated only in its origin world (UserWorld).
    let mut semi_axiom = Cdu::new_semi_axiom(
        "All knowledge must be verifiable.".to_string(),
        World::UserWorld,
        node_id,
        &hlc,
    );
    
    print_cdu_summary_to_file("test_semi_axiom_to_axiom_promotion_initial", &semi_axiom, &project_root);

    // 2. Initially, it's only validated in its own world, so it's not an Axiom.
    assert!(!semi_axiom.is_axiom(), "A semi-axiom should not be an axiom initially.");
    assert_eq!(semi_axiom.metadata.validated_worlds.len(), 1);
    assert!(semi_axiom.metadata.validated_worlds.contains(&World::UserWorld));

    // 3. The Verifier role validates it in two other worlds.
    semi_axiom.validate_in_world(World::RWorld);
    semi_axiom.validate_in_world(World::LangCodingWorld);
    print_cdu_summary_to_file("test_semi_axiom_to_axiom_promotion_validated", &semi_axiom, &project_root);

    // 4. Now it is validated in UserWorld and two others (RWorld, LangCodingWorld), so it must be an Axiom.
    assert!(semi_axiom.is_axiom(), "Axiom validated in 3 worlds must be an axiom.");
    assert_eq!(semi_axiom.metadata.validated_worlds.len(), 3);
}
