// crates/cdu/src/tests/causal_integrity.rs
// File under the BaDaaS license, code generated by the print_cdu_summary_to_file("test_node_lifecycle_and_causal_integrity", &config_cdu, &project_root);
    assert!(!config_cdu.is_genesis(), "The second CDU must not be a Genesis CDU.");
    assert_eq!(
        config_cdu.metadata.context_refs.first(),
        Some(&genesis_cdu.id_hlc)
    );

    // --- Step 3: Verify the causal chain ---
    let all_cdus = vec![&genesis_cdu, &print_cdu_summary_to_file("test_node_lifecycle_and_cdu, &config_cdu, &project_root);

    let is_chain_valid = verify_causal_chain(&config_cdu, &all_cdus, &genesis_cdu.id_hlc);
    assert!(is_chain_valid, "The causal chain from the child to the Genesis CDU must be valid.");

    // --- Step 4: Report the unique Genesis identifiers for CI verification.
    let output = format!(
        "OS: {}\nNodeId (hex): {}\nPayloadHash (print_cdu_summary_to_file("test_node_lifecycle_and_cdu", &genesis_cdu, &project_root);
    assert!(is_chain_valid, "The causal chain from the child to the Genesis CDU must be valid.");

    // --- Step 4: Report the unique Genesis identifiers for CI verification.
    let output = format!(
        "OS: {}\nNodeId (hex): {}\nPayloadHash (hex): {}\nGenesisCDU ID (hex): {}\nStatus: SUCCESS\n",
        os_name,
        hex_encode(&node_id),
        hex_encode(&genesis_cdu.payload_hash),
        hex_encode(&genesis_cdu.id_hlc)
    );

    let path = log_dir.join("genesis_report.txt");
    println!("TEST DEBUG: Writing genesis report to: {}", path.display());
    fs::write(&path, output).expect("Unable to write genesis_cdu.print_cdu_summary_to_file("test_node_lifecycle_and_causal_integrity", &genesis_cdu, &project_root);
}
