// crates/cdu/src/tests/causal_integrity.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use crate::types::Cdu;
use crate::payloads::{GenesisPayload, ConfigPayload};
use crate::tests::{find_workspace_root, print_cdu_summary_to_file, hex_encode, verify_causal_chain};
use cdqn_hlc::HybridLogicalClock;
use cdqn_cryptocore::SignerEntity;
use std::collections::HashMap;
use std::fs;
use std::time::{SystemTime, UNIX_EPOCH};
use serde_json::json;

/// This test validates the full node lifecycle from Genesis to a child CDU,
/// and verifies the causal chain integrity and ephemeral signing.
#[test]
fn test_node_lifecycle_and_causal_integrity() {
    let project_root = find_workspace_root();
    let hlc = HybridLogicalClock::new();
    let os_name = std::env::consts::OS;
    
    // --- Ephemeral Signer Setup ---
    let node_signer = SignerEntity::new_random("NodeId"); // Ephemeral Key
    let node_id = cdqn_cryptocore::hash_sha3_256(node_signer.verification_key().as_bytes()).to_vec();
    
    // --- Step 1: Create Genesis CDU (Root of Trust) ---
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let seed = format!("cdqn-genesis-{}-{}", os_name, timestamp);
    let hardware_fp = cdqn_cryptocore::hash_sha3_256(seed.as_bytes());

    let genesis_payload = GenesisPayload {
        hardware_fingerprint: hardware_fp,
        os: os_name.to_string(),
        timestamp: (timestamp / 1_000_000_000) as u64,
        location: "CI Runner".to_string(),
    };
    let mut genesis_cdu = Cdu::create_genesis_cdu(genesis_payload, node_id.clone(), &hlc);
    
    // FIX: Sign the Genesis CDU
    genesis_cdu.sign(&node_signer, &hlc).expect("Genesis CDU signing failed");
    genesis_cdu.verify_signatures().expect("Genesis CDU signature verification failed");

    print_cdu_summary_to_file("test_node_lifecycle_and_causal_integrity_genesis", &genesis_cdu, &project_root);
    assert!(genesis_cdu.is_genesis(), "The first CDU must be a Genesis CDU.");

    // --- Step 2: Create a Config CDU (Child of Genesis) ---
    let mut settings = HashMap::new();
    settings.insert("privacy_level".to_string(), json!("high"));
    
    let mut config_cdu = Cdu::new_config(
        settings,
        node_id.clone(),
        &hlc,
        &genesis_cdu.id_hlc, // Causal link to parent
    );
    
    // FIX: Sign the Config CDU
    config_cdu.sign(&node_signer, &hlc).expect("Config CDU signing failed");
    config_cdu.verify_signatures().expect("Config CDU signature verification failed");

    print_cdu_summary_to_file("test_node_lifecycle_and_causal_integrity_config", &config_cdu, &project_root);
    assert!(!config_cdu.is_genesis(), "The second CDU must not be a Genesis CDU.");
    assert_eq!(
        config_cdu.metadata.context_refs.first(),
        Some(&genesis_cdu.id_hlc),
        "Config CDU must reference Genesis CDU as its parent."
    );

    // --- Step 3: Verify the causal chain ---
    let all_cdus = vec![&genesis_cdu, &config_cdu];

    let is_chain_valid = verify_causal_chain(&config_cdu, &all_cdus, &genesis_cdu.id_hlc);
    assert!(is_chain_valid, "The causal chain from the child to the Genesis CDU must be valid.");

    // --- Step 4: Report the unique Genesis identifiers for CI verification.
    let output = format!(
        "\n--- START: TEST REPORT (test_node_lifecycle_and_causal_integrity) ---\n\
        OS: {}\n\
        NodeId (hex): {}\n\
        Ephemeral Signer ID: {}\n\
        GenesisCDU ID (hex): {}\n\
        Causal Chain Valid: {}\n\
        Status: SUCCESS\n\
        --- END: TEST REPORT (test_node_lifecycle_and_causal_integrity) ---\n",
        os_name,
        hex_encode(&node_id),
        node_signer.entity_id, // FIX: Print the Ephemeral Signer ID
        hex_encode(&genesis_cdu.id_hlc),
        is_chain_valid
    );

    let path = project_root.join("ci-logs").join("genesis_report.txt");
    println!("TEST DEBUG: Writing genesis report to: {}", path.display());
    
    fs::write(&path, output).expect(&format!("Unable to write genesis_report.txt to: {}", path.display()));
}
