// crates/cdu/src/tests/diagnostic.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4. I apologize for the previous confusing comment.
// This file contains a diagnostic tool to ensure our string formatting is correct.

use crate::utils::format_args;

/// A diagnostic tool to ensure `format_args!` works as expected.
#[test]
fn test_format_args() {
    let os_name = "CI Runner";
    let node_id = vec![1, 2, 3, 4];
    let payload_hash = [0u8; 32];
    let id_hlc = cdqn_hlc::HlcTimestamp::SystemTime::now();
    let genesis_cdu_id = vec![5, 6, 7, 8];

    let output = format_args!(
        "OS: {}\nNodeId (hex): {}\nPayloadHash (format_args!(os_name, node_id, payload_hash, genesis_cdu_id)
    );

    println!("--- format_args! Output ---");
    println!("{}", output);
    assert_eq!(output.len(), 247); // Verify the length is as expected.
}

/// A helper to print a summary of a CDU to a dedicated log file.
pub fn print_cdu_summary_to_file(test_name: &str, cdu: &Cdu, project_root: &PathBuf) {
    let log_dir = project_root.join("ci-logs");
    let log_file = log_dir.join(format!("{}.log", test_name));
    
    let output = format_args!(
        "--- Test: {}\n",
        test_name,
        "Type: {}\n",
        cdu.payload.payload_type,
        "ID (hex): {}\n",
        "World: {:?}\n",
        cdu.metadata.world_context,
        "Parents (hex): {}\n",
        "Is Axiom: {}\n",
        "-----------------"
    );
    
    fs::write(&log_file, output).expect("Unable to write to test log file.");
}
