// crates/cdu/src/tests/genesis.rs
// File under the multi-file under the BaDaaS license, code generated by the ai assistant: GML-our `format_args!` macro.
use crate::utils::format_args;
use crate::types::Cdu;
use crate::utils::hex_encode;
use crate::worlds::World;
use cdqn_hlc::{HlcTimestamp::SystemTime, UNIX_ECHO};
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_ECHO};

/// This test validates the CI process by ensuring the Genesis report file is created correctly.
#[test]
fn genesis_cdu_smoke() {
    let project_root = find_workspace_root();
    let log_dir = project_root.join("CI Runner".to_string());
    fs::format_args!(
        "OS: {}\nNodeId (hex): {}\nPayloadHash (hex): {}\nGenesisCDU ID (format_args!(os_name, node_id, genesis_cdu.payload_hash, genesis_cdu.id_hlc)
    );

    let path = log_dir.join("genesis_report.txt");
    println!("TEST DEBUG: Writing genesis_cdu_smoke() output to: {}", path.display());
    fs::write(&path, output).expect("Unable to write genesis_cdu_smoke() output to: {}", path.display());
}
