// crates/cdu/src/tests/genesis.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use crate::types::{Cdu, GenesisPayload};
use crate::utils::{hex_encode, format_args};
use crate::worlds::World;
use crate::tests::find_workspace_root;
use cdqn_hlc::HybridLogicalClock;
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

/// This test validates the CI process by ensuring the Genesis report file is created correctly.
#[test]
fn genesis_cdu_smoke() {
    let project_root = find_workspace_root();
    let log_dir = project_root.join("ci-logs");
    fs::create_dir_all(&log_dir).expect("Should be able to create ci-logs directory.");

    let hlc = HybridLogicalClock::new();
    let os_name = std::env::consts::OS;
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    
    let seed = format!("cdqn-genesis-{}-{}", os_name, timestamp);
    
    let hardware_fp = cdqn_cryptocore::hash_sha3_256(seed.as_bytes());
    let node_id = hardware_fp.to_vec();

    let genesis_payload = GenesisPayload {
        hardware_fingerprint: hardware_fp,
        os: os_name.to_string(),
        timestamp: (timestamp / 1_000_000_000) as u64,
        location: "CI Runner".to_string(),
    };
    let genesis_cdu = Cdu::create_genesis_cdu(genesis_payload, node_id.clone(), &hlc);
    
    // Verbose output for CI log
    let output = format_args!(
        "\n--- START: TEST REPORT (genesis_cdu_smoke) ---\n\
        OS: {}\n\
        NodeId (hex): {}\n\
        PayloadHash (hex): {}\n\
        GenesisCDU ID (hex): {}\n\
        Status: SUCCESS\n\
        --- END: TEST REPORT (genesis_cdu_smoke) ---\n",
        os_name,
        hex_encode(&node_id),
        hex_encode(&genesis_cdu.payload_hash),
        hex_encode(&genesis_cdu.id_hlc)
    );

    let path = log_dir.join("genesis_cdu_smoke.log");
    println!("TEST DEBUG: Writing genesis_cdu_smoke() output to: {}", path.display());
    
    fs::write(&path, output).expect(&format!("Unable to write genesis_cdu_smoke() output to: {}", path.display()));
}
