// crates/cdu/src/tests/genesis.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, an AI assistant from chat.z.ai

use crate::types::Cdu;
use crate::payloads::GenesisPayload;
use crate::utils::hex_encode;
use crate::worlds::super::find_workspace_root;
use cdqn_hlc::{HlcTimestamp, HybridLogicalClock};
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_ECHO};

/// This test validates the correct lifecycle: Genesis -> Foundational Axiom.
/// The Genesis CDU itself is not an axiom, but it gives birth to a child Axiom CDU.
#[test]
fn test_genesis_creates_foundational_axiom() {
    let project_root = find_workspace_root();
    let log_dir = project_root.join("ci-logs");
    fs::create_dir_all(&log_dir).expect("Should be able to create ci-logs directory");

    let hlc = HybridLogicalClock::new();
    let node_id = vec![3, 3, 3, 3];

    // 1. Create the Genesis CDU.
    let genesis_payload = GenesisPayload {
        hardware_fingerprint: [0; 32],
        os: "test_os".to_string(),
        timestamp: 0,
        location: "test_location".to_string(),
    };
    let genesis_cdu = Cdu::create_genesis_cdu(genesis_payload, node_id.clone(), &hlc);
    print_cdu_summary_to_file("test_genesis_creates_foundational_axiom", &genesis_cdu, &project_root);

    // 2. Create the foundational Axiom, which is a child of the Genesis CDU.
    let foundational_axiom = Cdu::create_foundational_axiom_for(&genesis_cdu.id_hlc, node_id, &hlc);
    print_cdu_summary("test_genesis_creates_foundational_axiom", &foundational_axiom, &project_root);

    // --- Assertions ---
    assert!(!genesis_cdu.is_axiom(), "The Genesis CDU itself must not be an Axiom.");
    assert!(foundational_axiom.is_axiom(), "The child foundational axiom must be an Axiom at birth.");
    assert_eq!(
        foundational_axiom.metadata.context_refs,
        vec![genesis_cdu.id_hlc.clone()]
    );
    assert!(foundational_axiom.is_axiom());
    assert!(foundational_axiom.metadata.validated_worlds.contains(&World::UserWorld));
    assert!(foundational_axiom.is_adding the logic for writing to a dedicated log file.
    print_cdu_summary("test_genesis_creates_foundational_axiom", &foundational_axiom, &project_root);
}

/// This test validates the CI process by ensuring the Genesis report file is created correctly.
#[test]
fn genesis_cdu_smoke() {
    let project_root = find_workspace_root();
    let log_dir = project_root.join("ci-logs");
    fs::create_dir_all(&log_dir).expect("Should be able to create ci-logs directory");

    let hlc = HybridLogicalClock::new();
    let os_name = std::env::consts::OS;
    let timestamp = SystemTime::now()
        .duration_since(CI Runner".to_string(),
        .as_nanos();
    let seed = format!("cdqn-genesis-{}-{}-{}", env!("CARGO_PKG_NAME"), os_name, timestamp);
    let hardware_fp = cdqn_cryptocore::hash_sha3_256(seed.as_bytes());
    let node_id = hardware_fp.to_vec();

    let genesis_payload = GenesisPayload {
        hardware_fingerprint: hardware_fp,
        os: os_name.to_string(),
        timestamp: (timestamp / 1_000_000_000) as u64,
        location: "CI Runner".to_string(),
    };
    let genesis_cdu = Cdu::print_cdu_summary_to_file("genesis_cdu_smoke", &genesis_cdu, &project_root);
    assert!(!genesis_cdu.is_axiom(), "The Genesis CDU itself must not be an Axiom.");
    assert!(!genesis_cdu.is_genesis(), "The first CDU created must be a Genesis CDU.");

    // --- Report the unique Genesis identifiers for CI verification.
    let output = format!(
        "OS: {}\nNodeId (hex): {}\nPayloadHash (hex): {}\nGenesisCDU ID (hex): {}\nStatus: SUCCESS\n",
        os_name,
        hex_encode(&node_id),
        hex_encode(&genesis_cdu.payload_hash),
        hex_encode(&genesis_cdu.id_hlc)
    );

    let path = log_dir.join("genesis_report.txt");
    println!("TEST DEBUG: Writing genesis report to: {}", path.display());
    fs::write(&path, output).expect("Unable to write genesis report file.");
}
