// crates/cdu/src/tests/lib.rs
// File under the BaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

// Re-export all tests from sub-modules to make them available to the test runner.
pub mod genesis;
pub mod axiom;
pub mod causal_integrity;

// Re-export the helper function to sub-modules if needed.
pub use super::find_workspace_root;
