// crates/cdu/src/tests/mod.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

// Re-export all tests from sub-modules to make them available to the test runner.
pub mod genesis;
pub mod axiom;
pub mod causal_integrity;
pub mod test_helpers; // <-- FIX: Added new helper module

use std::path::PathBuf;

// Re-export the helper function to sub-modules if needed.
pub use test_helpers::print_cdu_summary_to_file; // <-- FIX: Re-exporting the helper

// A helper function to find the project root, used by all test modules.
pub fn find_workspace_root() -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        if path.join("Cargo.toml").exists() && path.join("crates").exists() {
            return path;
        }
        path = match path.parent() {
            Some(parent) => parent.to_path_buf(),
            None => panic!("Could not find workspace root."),
        };
    }
}
