// crates/cdu/src/tests/test_helpers.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use crate::types::Cdu;
use std::fs;
use std::path::PathBuf;

/// A simple utility to encode bytes as a hexadecimal string.
#[must_use]
pub fn hex_encode(bytes: &[u8]) -> String {
    const HEX_CHARS: &[u8] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for &b in bytes {
        output.push(HEX_CHARS[(b >> 4) as usize] as char);
        output.push(HEX_CHARS[(b & 0x0F) as usize] as char);
    }
    output
}

/// A simple, in-memory verification function for testing causal chains.
#[must_use]
pub fn verify_causal_chain(
    cdu: &Cdu,
    all_cdus: &[&Cdu],
    expected_genesis_id: &[u8],
) -> bool {
    if cdu.is_genesis() {
        return cdu.id_hlc == expected_genesis_id;
    }

    for parent_id in &cdu.metadata.context_refs {
        if let Some(parent_cdu) = all_cdus.iter().find(|&p| p.id_hlc == *parent_id) {
            if !verify_causal_chain(parent_cdu, all_cdus, expected_genesis_id) {
                return false;
            }
        } else {
            // Parent not found in the provided set, chain is broken.
            return false;
        }
    }
    true
}

/// A helper to print a summary of a CDU to a dedicated log file.
/// This is used by multiple tests for CI reporting.
#[allow(dead_code)]
pub fn print_cdu_summary_to_file(test_name: &str, cdu: &Cdu, project_root: &PathBuf) {
    let log_dir = project_root.join("ci-logs");
    let log_file = log_dir.join(format!("{}.log", test_name));
    
    let output = format!(
        "--- Test: {}\n\
        Type: {}\n\
        ID (hex): {}\n\
        World: {:?}\n\
        Is Axiom: {}\n\
        -----------------\n",
        test_name,
        cdu.payload.payload_type,
        hex_encode(&cdu.id_hlc),
        cdu.metadata.world_context,
        cdu.is_axiom()
    );
    
    fs::write(&log_file, output).expect(&format!("Unable to write to test log file: {}", log_file.display()));
}

/// A diagnostic tool to ensure string formatting is correct.
#[test]
fn test_diagnostic_formatting() {
    let os_name = "CI Runner";
    let node_id = vec![1, 2, 3, 4];
    let payload_hash = [0u8; 32];
    let genesis_cdu_id = vec![5, 6, 7, 8];

    let output = format!(
        "OS: {}\nNodeId (hex): {}\nPayloadHash (hex): {}\nGenesisCDU ID (hex): {}\nStatus: SUCCESS\n",
        os_name,
        hex_encode(&node_id),
        hex_encode(&payload_hash),
        hex_encode(&genesis_cdu_id)
    );

    println!("--- format! Output ---");
    println!("{}", output);
    assert!(output.contains("CI Runner"));
}
