// crates/cdu/src/tests/theorem_and_deferral.rs
// File under the BaDaaS license, code generated by the ai model: Gemini-2.5-pro-grounding, Google

//! Tests for the new Theorem and ImpossibilityDeferral CDU payloads.
//! This validates the core data structures for the advanced reasoning cycle.

use crate::payloads::{TheoremPayload, ImpossibilityDeferralPayload, ReasoningStep};
use crate::worlds::World;
use cdqn_cryptocore::hash_sha3_256;

#[test]
fn test_theorem_payload_creation_and_serialization() {
    println!("\n--- THEOREM & DEFERRAL TEST: Testing TheoremPayload ---");

    // 1. Create a sample TheoremPayload
    let foundation_axiom_id = hash_sha3_256(b"axiom_1").to_vec();
    let theorem_payload = TheoremPayload {
        foundation_axiom_ids: vec![foundation_axiom_id.clone()],
        reasoning_path: vec![
            ReasoningStep {
                transformation: "Step 1: Apply Modus Ponens".to_string(),
                applied_rule_id: Some(foundation_axiom_id),
                input_pattern: "If P then Q, and P".to_string(),
                output_pattern: "Therefore, Q".to_string(),
            }
        ],
        goal_statement: "Conclusion Q is reached.".to_string(),
        category_signature: "logic/deduction/modus_ponens".to_string(),
        valid_in_worlds: vec![World::RWorld, World::LangCodingWorld],
        reuse_count: 0,
        efficiency_gain_ns: None,
    };

    // 2. Convert it to a generic Payload
    let generic_payload = theorem_payload.clone().into_payload();

    // 3. Assert the payload type is correct
    assert_eq!(generic_payload.payload_type, "theorem/v1");
    println!("Payload type is correct: {}", generic_payload.payload_type);

    // 4. Test the category matching logic
    assert!(theorem_payload.matches_category("logic/deduction"));
    assert!(!theorem_payload.matches_category("logic/induction"));
    println!("Category matching logic is working as expected.");

    // 5. Verify deserialization (optional but good practice)
    let deserialized_payload = TheoremPayload::from_payload(&generic_payload).expect("Deserialization failed");
    assert_eq!(deserialized_payload.goal_statement, "Conclusion Q is reached.");
    println!("Serialization and deserialization successful.");
    println!("-----------------------------------------------------\n");
}

#[test]
fn test_impossibility_deferral_payload_creation() {
    println!("\n--- THEOREM & DEFERRAL TEST: Testing ImpossibilityDeferralPayload ---");

    // 1. Create a sample ImpossibilityDeferralPayload
    let source_cdu_id = hash_sha3_256(b"contradictory_cdu").to_vec();
    let deferral_payload = ImpossibilityDeferralPayload {
        source_cdu_id: source_cdu_id.clone(),
        contradiction_description: "Paradox detected: A and not A".to_string(),
        waiting_in_world: World::UserWorld,
        needed_axiom_hint: "Requires axiom defining relationship between A and B".to_string(),
        attempt_count: 1,
        retry_after_timestamp: 1234567890,
    };

    // 2. Convert it to a generic Payload
    let generic_payload = deferral_payload.into_payload();

    // 3. Assert the payload type is correct
    assert_eq!(generic_payload.payload_type, "impossibility-deferral/v1");
    println!("Payload type is correct: {}", generic_payload.payload_type);
    println!("-------------------------------------------------------------\n");
}
