// crates/manifold/src/integrity.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use crate::types::{Manifold, CduId, MerkleRoot};
use cdqn_cdu::Cdu;
use cdqn_cryptocore::{Sha3_256, Digest};
use std::collections::HashSet;

impl Manifold {
    /// Implements Workflow 5: The Sovereign Integrity Cycle.
    /// Traverses the context_refs backward to the Genesis CDU.
    /// NOTE: This checks the initial CDU's properties before starting the graph traversal.
    pub fn verify_cdu_chain(&self, cdu: &Cdu) -> Result<(), String> {
        if cdu.is_genesis() {
            return Ok(()); // Genesis is the root of trust.
        }

        // 1. Initial Check: Must have parents if it's not Genesis
        if cdu.metadata.context_refs.is_empty() {
            return Err(format!("Broken Chain: CDU ID {:?} is an orphan (no context_refs) and is not Genesis.", cdu.id_hlc));
        }

        let mut current_cdu_id: CduId;
        let mut visited_ids = HashSet::new();

        // Start traversal from the CDU's parents
        // We use the first parent as the starting point for the chain check.
        let mut next_id_to_check = cdu.metadata.context_refs[0].clone();

        // Loop until we reach the Genesis CDU or hit an error
        loop {
            current_cdu_id = next_id_to_check;

            // 2. Cycle Detection
            if !visited_ids.insert(current_cdu_id.clone()) {
                return Err(format!("Broken Chain: Cycle detected at CDU ID {:?}", current_cdu_id));
            }

            // 3. Check if Parent Exists in Manifold
            let current_cdu = self.get_cdu(&current_cdu_id)
                .ok_or_else(|| format!("Broken Chain: Parent CDU ID {:?} not found in Manifold.", current_cdu_id))?;

            // 4. Check for Genesis Root
            if current_cdu_id == self.genesis_id {
                return Ok(()); // Chain successfully traced back to Genesis!
            }

            // 5. Continue traversal to the next parent
            if current_cdu.metadata.context_refs.is_empty() {
                // A non-Genesis CDU in the chain must have parents.
                return Err(format!("Broken Chain: Intermediate CDU ID {:?} is an orphan.", current_cdu_id));
            }
            next_id_to_check = current_cdu.metadata.context_refs[0].clone();
        }
    }

    /// Computes the cryptographic fingerprint of the Manifold's entire state.
    /// This is the core of the Global Integrity Schema.
    #[must_use]
    pub fn calculate_merkle_root(&self) -> MerkleRoot {
        let ids_reader = self.active_ids.read().expect("Manifold read lock poisoned");
        let mut sorted_ids: Vec<CduId> = ids_reader.iter().cloned().collect();

        // 1. Canonical Ordering: Sort all active CduIds (id_hlc)
        // This ensures the root is deterministic regardless of ingestion order.
        sorted_ids.sort();

        if sorted_ids.is_empty() {
            return [0u8; 32];
        }

        // 2. Merkle Tree Construction (Simplified: Hash of concatenated, sorted IDs)
        // In a full implementation, this would be a proper Merkle Tree.
        let mut hasher = Sha3_256::new();
        for id in sorted_ids {
            hasher.update(id);
        }
        hasher.finalize().into()
    }

    /// Atomically updates the global_merkle_root.
    pub fn update_merkle_root(&self) {
        let new_root = self.calculate_merkle_root();
        *self.global_merkle_root.write().expect("Manifold write lock poisoned") = new_root;
    }

    /// Retrieves the current global Merkle Root.
    #[must_use]
    pub fn get_merkle_root(&self) -> MerkleRoot {
        *self.global_merkle_root.read().expect("Manifold read lock poisoned")
    }
}
