// crates/manifold/src/lib.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! Emergent in-memory projection of the sovereign knowledge graph.
//!
//! The Manifold is not stored—it is built on-demand from CDU metadata.
//! This crate provides indexing, causal traversal, and consistency verification
//! using only internal CDQN primitives.

mod types;
mod integrity;
mod storage;

#[cfg(test)]
mod tests;

pub use types::{Manifold, CduId, MerkleRoot};

use cdqn_cdu::Cdu;
use std::sync::Arc;
use std::path::PathBuf;
use std::collections::{HashMap, HashSet}; // <-- FIX: Added HashSet import

impl Manifold {
    /// Creates a new Manifold, initialized with the Genesis CDU.
    #[must_use]
    pub fn new(genesis_cdu: Cdu, storage_path: PathBuf) -> Self {
        let genesis_id = genesis_cdu.id_hlc.clone();
        let mut cdus = HashMap::new();
        let mut active_ids = HashSet::new();

        // Insert the Genesis CDU as the first element
        cdus.insert(genesis_id.clone(), Arc::new(genesis_cdu));
        active_ids.insert(genesis_id.clone());

        // Ensure the storage directory exists
        std::fs::create_dir_all(&storage_path).expect("Failed to create Manifold storage directory");

        let manifold = Manifold {
            cdus: std::sync::RwLock::new(cdus),
            active_ids: std::sync::RwLock::new(active_ids),
            global_merkle_root: std::sync::RwLock::new([0u8; 32]), // Placeholder
            genesis_id,
            storage_path,
        };

        // Calculate the initial Merkle Root
        manifold.update_merkle_root();
        manifold
    }

    /// Ingests a new, verified CDU into the Manifold.
    /// This is a write operation, requiring a lock.
    pub fn ingest_cdu(&self, cdu: Cdu) -> Result<(), String> {
        let id = cdu.id_hlc.clone();
        let arc_cdu = Arc::new(cdu);

        // Acquire write locks
        let mut cdus_writer = self.cdus.write().expect("Manifold write lock poisoned");
        let mut ids_writer = self.active_ids.write().expect("Manifold write lock poisoned");

        if cdus_writer.contains_key(&id) {
            return Err(format!("CDU with ID {:?} already exists.", id));
        }

        // 1. Insert the new CDU
        cdus_writer.insert(id.clone(), arc_cdu);
        ids_writer.insert(id);

        // 2. Update the Global Merkle Root
        self.update_merkle_root();

        Ok(())
    }
}
