// crates/manifold/src/tests.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use crate::{Manifold, CduId};
use cdqn_cdu::{Cdu, payloads::GenesisPayload, worlds::World};
use cdqn_cryptocore::hash_sha3_256;
use cdqn_hlc::HybridLogicalClock;
use std::time::{SystemTime, UNIX_EPOCH};
use std::collections::HashMap;
use tempfile::tempdir;

// Helper function to create a unique Genesis CDU for testing
fn create_test_genesis() -> Cdu {
    let hlc = HybridLogicalClock::new();
    let timestamp = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();
    let seed = format!("test-genesis-{}", timestamp);
    let hardware_fp = hash_sha3_256(seed.as_bytes());
    let node_id = hardware_fp.to_vec();

    let payload = GenesisPayload {
        hardware_fingerprint: hardware_fp,
        os: "test_os".to_string(),
        timestamp: (timestamp / 1_000_000_000) as u64,
        location: "test_loc".to_string(),
    };
    Cdu::create_genesis_cdu(payload, node_id, &hlc)
}

// Helper to hex encode a Merkle Root for printing
fn hex_encode_root(root: &crate::MerkleRoot) -> String {
    root.iter().map(|b| format!("{:02x}", b)).collect()
}

#[test]
fn test_manifold_initialization_and_merkle_root() {
    let temp_dir = tempdir().unwrap();
    let genesis = create_test_genesis();
    let manifold = Manifold::new(genesis.clone(), temp_dir.path().to_path_buf());

    // 1. Check initial state
    assert_eq!(manifold.cdus.read().unwrap().len(), 1);
    assert_eq!(manifold.active_ids.read().unwrap().len(), 1);
    assert_eq!(manifold.genesis_id, genesis.id_hlc);

    // 2. Check Merkle Root calculation (should not be all zeros)
    let root = manifold.get_merkle_root();
    
    // VERBOSE OUTPUT: Print the initial Merkle Root
    println!("\n--- VERIFIABLE MANIFOLD TEST: INITIALIZATION ---");
    println!("Genesis CDU ID: {}", hex_encode_root(&genesis.id_hlc.as_slice().try_into().unwrap()));
    println!("Initial Merkle Root: {}", hex_encode_root(&root));
    println!("------------------------------------------------");

    assert_ne!(root, [0u8; 32]);

    // 3. Check Merkle Root determinism (re-calculate)
    let new_root = manifold.calculate_merkle_root();
    assert_eq!(root, new_root);
}

#[test]
fn test_cdu_ingestion_and_merkle_root_update() {
    let temp_dir = tempdir().unwrap();
    let genesis = create_test_genesis();
    let manifold = Manifold::new(genesis.clone(), temp_dir.path().to_path_buf());
    let initial_root = manifold.get_merkle_root();

    // Create a child CDU
    let hlc = HybridLogicalClock::new();
    let child_cdu = Cdu::create_foundational_axiom_for(
        &genesis.id_hlc,
        genesis.metadata.author_node.clone(),
        &hlc,
    );

    // Ingest the child
    manifold.ingest_cdu(child_cdu.clone()).unwrap();

    // 1. Check state update
    assert_eq!(manifold.cdus.read().unwrap().len(), 2);
    assert_eq!(manifold.active_ids.read().unwrap().len(), 2);
    
    // 2. Check Merkle Root update
    let final_root = manifold.get_merkle_root();
    
    // VERBOSE OUTPUT: Print the Merkle Root change
    println!("\n--- VERIFIABLE MANIFOLD TEST: INGESTION ---");
    println!("Initial Merkle Root: {}", hex_encode_root(&initial_root));
    println!("Child CDU ID: {}", hex_encode_root(&child_cdu.id_hlc.as_slice().try_into().unwrap()));
    println!("Final Merkle Root: {}", hex_encode_root(&final_root));
    println!("------------------------------------------");

    assert_ne!(initial_root, final_root, "Merkle root must change after ingestion.");
}

#[test]
fn test_verify_cdu_chain_valid() {
    let temp_dir = tempdir().unwrap();
    let genesis = create_test_genesis();
    let manifold = Manifold::new(genesis.clone(), temp_dir.path().to_path_buf());
    let hlc = HybridLogicalClock::new();

    // Child 1 (Axiom)
    let cdu_a = Cdu::create_foundational_axiom_for(
        &genesis.id_hlc,
        genesis.metadata.author_node.clone(),
        &hlc,
    );
    manifold.ingest_cdu(cdu_a.clone()).unwrap();

    // Child 2 (Config) -> Cdu A
    let cdu_b = Cdu::new_config(
        HashMap::new(),
        genesis.metadata.author_node.clone(),
        &hlc,
        &cdu_a.id_hlc,
    );
    manifold.ingest_cdu(cdu_b.clone()).unwrap();

    // VERBOSE OUTPUT: Print the causal links
    println!("\n--- VERIFIABLE MANIFOLD TEST: CAUSALITY ---");
    println!("Genesis ID: {}", hex_encode_root(&genesis.id_hlc.as_slice().try_into().unwrap()));
    println!("CDU A (Axiom) ID: {}", hex_encode_root(&cdu_a.id_hlc.as_slice().try_into().unwrap()));
    println!("CDU B (Config) ID: {}", hex_encode_root(&cdu_b.id_hlc.as_slice().try_into().unwrap()));
    println!("CDU B Parent Ref: {}", hex_encode_root(&cdu_b.metadata.context_refs[0].as_slice().try_into().unwrap()));
    println!("-------------------------------------------");

    // Verification should pass
    assert!(manifold.verify_cdu_chain(&cdu_b).is_ok(), "Valid chain should pass verification.");
}

#[test]
fn test_verify_cdu_chain_broken_orphan() {
    let temp_dir = tempdir().unwrap();
    let genesis = create_test_genesis();
    let manifold = Manifold::new(genesis.clone(), temp_dir.path().to_path_buf());
    let hlc = HybridLogicalClock::new();

    // Orphan CDU (no context_refs)
    let orphan_cdu = Cdu::new_semi_axiom(
        "I am an orphan.".to_string(),
        World::UserWorld,
        genesis.metadata.author_node.clone(),
        &hlc,
    );
    
    // Verification should fail because it's not Genesis and has no parents.
    let result = manifold.verify_cdu_chain(&orphan_cdu);
    assert!(result.is_err());
    assert!(result.unwrap_err().contains("is an orphan"));
}

#[test]
fn test_persist_cdu() {
    let temp_dir = tempdir().unwrap();
    let genesis = create_test_genesis();
    let manifold = Manifold::new(genesis.clone(), temp_dir.path().to_path_buf());

    // Persist the Genesis CDU (it's already in the Manifold, but we test the persistence logic)
    manifold.persist_cdu(&genesis).unwrap();

    // Check if the file exists on disk
    let file_path = manifold.storage_path.join(format!("{}.cdu", crate::storage::hex::encode(&genesis.id_hlc)));
    assert!(file_path.exists(), "The CDU file must exist on disk after persistence.");
}
