// crates/manifold/src/types.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use cdqn_cdu::Cdu;
use std::collections::{HashMap, HashSet};
use std::sync::{Arc, RwLock};
use std::path::PathBuf;

// --- Type Aliases ---
pub type CduId = Vec<u8>; // The id_hlc
pub type MerkleRoot = [u8; 32]; // SHA3-256 hash

/// The Manifold: A dynamic emergent space projection and sovereign knowledge base.
/// Uses RwLock for concurrent read/write access.
pub struct Manifold {
    /// The in-memory graph: CduId -> CDU object.
    /// RwLock allows multiple readers or a single writer.
    pub cdus: RwLock<HashMap<CduId, Arc<Cdu>>>,
    /// A set of all active CduIds for quick membership checks and Merkle root calculation.
    pub active_ids: RwLock<HashSet<CduId>>,
    /// The cryptographic fingerprint of the Manifold's entire state.
    pub global_merkle_root: RwLock<MerkleRoot>,
    /// The ID of the Genesis CDU, the root of trust.
    pub genesis_id: CduId,
    /// The path to the on-disk storage for encrypted CDUs.
    pub storage_path: PathBuf,
}

impl Manifold {
    /// Retrieves a CDU by its ID from the in-memory projection.
    #[must_use]
    pub fn get_cdu(&self, id: &CduId) -> Option<Arc<Cdu>> {
        let reader = self.cdus.read().expect("Manifold read lock poisoned");
        reader.get(id).cloned()
    }
}
