// crates/runtime/src/executor.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! The Sovereign Asynchronous Executor.
//!
//! This module implements a minimal, single-threaded executor using only `std::sync`
//! primitives to run `Future`s, adhering to the "No External Crates" constraint.

use std::future::Future;
use std::pin::Pin;
use std::task::{Context, Poll, Waker}; // FIX: Removed unused Poll
use std::sync::{Arc, Mutex};
use std::collections::VecDeque;
use std::thread::{self, ThreadId}; // FIX: Removed unused ThreadId

// --- Type Aliases ---
// A boxed, sendable future that can be polled.
type BoxFuture = Pin<Box<dyn Future<Output = ()> + Send>>;

// --- 1. The Ready Queue ---

/// The shared, thread-safe queue for tasks ready to be polled.
pub struct ReadyQueue {
    queue: Mutex<VecDeque<Arc<Task>>>,
}

impl ReadyQueue {
    #[must_use]
    pub fn new() -> Self {
        ReadyQueue {
            queue: Mutex::new(VecDeque::new()),
        }
    }

    /// Pushes a task onto the ready queue.
    pub fn push(&self, task: Arc<Task>) {
        self.queue.lock().unwrap().push_back(task);
    }

    /// Pops a task from the ready queue.
    pub fn pop(&self) -> Option<Arc<Task>> {
        self.queue.lock().unwrap().pop_front()
    }
}

// --- 2. The Task ---

/// A single unit of work (a Future) managed by the Executor.
pub struct Task {
    /// The future itself. Must be boxed and pinned.
    future: Mutex<BoxFuture>,
    /// A clone of the ReadyQueue to push itself back onto when woken.
    ready_queue: Arc<ReadyQueue>,
}

impl Task {
    /// Creates a new Task and returns a Spawner to submit it.
    #[must_use]
    pub fn new<F>(future: F, ready_queue: Arc<ReadyQueue>) -> Arc<Self>
    where
        F: Future<Output = ()> + Send + 'static,
    {
        Arc::new(Task {
            future: Mutex::new(Box::pin(future)),
            ready_queue,
        })
    }

    /// Polls the future.
    pub fn poll(self: Arc<Self>) {
        // FIX: Clone the Arc before calling waker, which consumes the Arc.
        let waker = Task::waker(self.clone()); 
        let mut context = Context::from_waker(&waker);

        // Poll the future
        let mut future = self.future.lock().unwrap();
        let _ = future.as_mut().poll(&mut context);
        
        // NOTE: We ignore the Poll::Ready result here. The future's output is ()
        // and its completion is handled by the future itself (e.g., logging).
    }

    /// Creates a Waker that, when woken, reschedules this task.
    fn waker(self: Arc<Self>) -> Waker {
        // Create a RawWakerVTable that uses our custom wake function.
        let raw_waker = std::task::RawWaker::new(
            Arc::into_raw(self) as *const (),
            &VTABLE,
        );
        unsafe { Waker::from_raw(raw_waker) }
    }
}

// --- 3. The Custom Waker VTable ---

/// The VTable defines the functions the Waker will call.
const VTABLE: std::task::RawWakerVTable = std::task::RawWakerVTable::new(
    // clone
    clone_raw,
    // wake
    wake_raw,
    // wake_by_ref
    wake_by_ref_raw,
    // drop
    drop_raw,
);

/// Clones the Arc<Task>
unsafe fn clone_raw(ptr: *const ()) -> std::task::RawWaker {
    let arc_task = Arc::from_raw(ptr as *const Task);
    let _ = Arc::clone(&arc_task);
    std::mem::forget(arc_task);
    std::task::RawWaker::new(ptr, &VTABLE)
}

/// Wakes the task by pushing it back onto the ReadyQueue.
unsafe fn wake_raw(ptr: *const ()) {
    let arc_task = Arc::from_raw(ptr as *const Task);
    arc_task.ready_queue.push(arc_task.clone());
}

/// Wakes the task by reference (same as wake_raw for our simple executor).
unsafe fn wake_by_ref_raw(ptr: *const ()) {
    let arc_task = Arc::from_raw(ptr as *const Task);
    arc_task.ready_queue.push(arc_task.clone());
    std::mem::forget(arc_task); // Don't drop the Arc
}

/// Drops the Arc<Task>.
unsafe fn drop_raw(ptr: *const ()) {
    let _ = Arc::from_raw(ptr as *const Task);
}

// --- 4. The Executor (The Runtime) ---

/// The main Executor that runs the futures.
pub struct Executor {
    ready_queue: Arc<ReadyQueue>,
    thread_handle: Option<thread::JoinHandle<()>>,
}

impl Executor {
    #[must_use]
    pub fn new() -> Self {
        let ready_queue = Arc::new(ReadyQueue::new());
        let ready_queue_clone = ready_queue.clone();

        // Spawn the single-threaded executor loop
        let thread_handle = thread::spawn(move || {
            // The Executor loop: continuously pull and poll tasks
            while let Some(task) = ready_queue_clone.pop() {
                task.poll();
            }
        });

        Executor {
            ready_queue,
            thread_handle: Some(thread_handle),
        }
    }

    /// Submits a new future to the executor.
    pub fn spawn<F>(&self, future: F)
    where
        F: Future<Output = ()> + Send + 'static,
    {
        let task = Task::new(future, self.ready_queue.clone());
        self.ready_queue.push(task);
    }
}
