// crates/runtime/src/lib.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! The CDQN Runtime: The sovereign guardrail and orchestration layer.
//!
//! This module initializes the Manifold, the Dispatcher, and spawns the Chronosa Agent threads.
//! It is architecturally separate from the Chronosa cognitive engine.

use cdqn_chronosa::{CduDispatcher, VerifierAgent, EvolutionAgent};
use cdqn_cdu::{Cdu, GenesisPayload};
use cdqn_manifold::Manifold;
use cdqn_hlc::HybridLogicalClock;
use cdqn_cryptocore::{hash_sha3_256, hex_encode};
use std::sync::{Arc, Barrier};
use std::thread::{self, JoinHandle};
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

#[cfg(test)]
mod tests;

// FIX: Declare the new executor module
mod executor; 
use executor::Executor;

/// The main CDQN Runtime struct (The Guardrail).
pub struct CdqnRuntime {
    pub manifold: Arc<Manifold>,
    pub dispatcher: CduDispatcher,
    pub agent_handles: Vec<JoinHandle<()>>,
    agent_startup_barrier: Arc<Barrier>, 
    // FIX: The Sovereign Executor
    executor: Executor,
}

impl CdqnRuntime {
    /// Initializes the CDQN Runtime.
    /// 1. Creates the Genesis CDU and Manifold.
    /// 2. Creates the CDU Dispatcher.
    /// 3. Spawns all core Chronosa Agent threads.
    #[must_use]
    pub fn new(storage_path: PathBuf) -> Self {
        println!("--- CDQN Runtime Initialization (The Guardrail) ---");

        // 1. Initialize Core Components
        let hlc = HybridLogicalClock::new();
        let genesis_cdu = Self::create_genesis_cdu(&hlc);
        let manifold = Arc::new(Manifold::new(genesis_cdu, storage_path));
        let dispatcher = CduDispatcher::new();

        println!("Manifold Initialized. Genesis ID: {}", hex_encode(&manifold.genesis_id));
        println!("CDU Dispatcher Ready.");

        // FIX: Initialize Executor and Barrier
        let executor = Executor::new();
        let num_agents = 2; // Verifier + Evolution
        let agent_startup_barrier = Arc::new(Barrier::new(num_agents + 1));

        let mut runtime = CdqnRuntime {
            manifold,
            dispatcher,
            agent_handles: Vec::new(),
            agent_startup_barrier,
            executor,
        };

        // 2. Spawn Core Agents (The Chronosa Intelligence)
        runtime.spawn_verifier_agent();
        runtime.spawn_evolution_agent();

        println!("--- Runtime Ready ---");
        runtime
    }

    /// Creates the sovereign Genesis CDU for the node.
    fn create_genesis_cdu(hlc: &HybridLogicalClock) -> Cdu {
        let os_name = std::env::consts::OS;
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        
        // NOTE: NodeId is derived from a hash of the Genesis data for sovereignty.
        let seed = format!("cdqn-genesis-{}-{}", os_name, timestamp);
        let hardware_fp = hash_sha3_256(seed.as_bytes());
        let node_id = hardware_fp.to_vec();

        let payload = GenesisPayload {
            hardware_fingerprint: hardware_fp,
            os: os_name.to_string(),
            timestamp: (timestamp / 1_000_000_000) as u64,
            location: "RuntimeInit".to_string(),
        };
        
        Cdu::create_genesis_cdu(payload, node_id, hlc)
    }

    /// Spawns the Verifier Agent thread.
    fn spawn_verifier_agent(&mut self) {
        let manifold_clone = self.manifold.clone();
        let dispatcher_clone = self.dispatcher.clone_for_agent();
        let barrier_clone = self.agent_startup_barrier.clone();

        let handle = thread::spawn(move || {
            let mut verifier = VerifierAgent::new(&dispatcher_clone, manifold_clone);
            // FIX: Wait on the Barrier before running
            barrier_clone.wait(); 
            verifier.run(None); 
        });

        self.agent_handles.push(handle);
        println!("Agent Spawned: VerifierAgent");
    }

    /// Spawns the Evolution Agent thread.
    fn spawn_evolution_agent(&mut self) {
        let manifold_clone = self.manifold.clone();
        let dispatcher_clone = self.dispatcher.clone_for_agent();
        let barrier_clone = self.agent_startup_barrier.clone();

        let handle = thread::spawn(move || {
            let mut evolution = EvolutionAgent::new(&dispatcher_clone, manifold_clone);
            // FIX: Wait on the Barrier before running
            barrier_clone.wait(); 
            evolution.run(None); 
        });

        self.agent_handles.push(handle);
        println!("Agent Spawned: EvolutionAgent");
    }

    /// The main loop to keep the runtime alive.
    pub fn run_forever(self) {
        // FIX: Wait on the Barrier to ensure all Agents are ready before proceeding
        self.agent_startup_barrier.wait(); 
        
        println!("CDQN Runtime (Guardrail) is running. Press Ctrl+C to stop.");
        
        // Block the main thread, waiting for all agent threads to finish.
        for handle in self.agent_handles {
            handle.join().expect("Agent thread panicked");
        }
    }
}

// NOTE: Local hex utility for printing IDs
mod hex {
    pub fn encode(bytes: &[u8]) -> String {
        bytes.iter().map(|b| format!("{:02x}", b)).collect()
    }
}
