// crates/runtime/src/lib.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini 2.5 Pro Grounding, Google

//! The CDQN Runtime: The sovereign guardrail and orchestration layer.
//!
//! This module initializes the Manifold, the Dispatcher, and spawns the Chronosa Agent threads.
//! It is architecturally separate from the Chronosa cognitive engine.

use cdqn_chronosa::{CduDispatcher, VerifierAgent, EvolutionAgent};
use cdqn_cdu::{Cdu, GenesisPayload};
use cdqn_manifold::Manifold;
use cdqn_hlc::HybridLogicalClock;
use cdqn_cryptocore::{hash_sha3_256};
use std::sync::{Arc, Barrier, mpsc};
use std::thread::{self, JoinHandle};
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

#[cfg(test)]
mod tests;

mod executor; 
pub use executor::Executor; // FIX: Make executor public for test access

/// The main CDQN Runtime struct (The Guardrail).
pub struct CdqnRuntime {
    pub manifold: Arc<Manifold>,
    pub dispatcher: CduDispatcher,
    pub agent_handles: Vec<JoinHandle<()>>,
    agent_startup_barrier: Arc<Barrier>, 
    pub executor: Executor, // FIX: Make executor public for test access
}

impl CdqnRuntime {
    /// Initializes the CDQN Runtime for production use.
    #[must_use]
    pub fn new(storage_path: PathBuf) -> Self {
        // FIX: Call the main constructor with no test channels.
        Self::new_with_test_channels(storage_path, None, None)
    }

    /// Initializes the CDQN Runtime with optional test channels for deterministic testing.
    #[must_use]
    pub fn new_with_test_channels(
        storage_path: PathBuf,
        verifier_tx: Option<mpsc::Sender<String>>,
        evolution_tx: Option<mpsc::Sender<String>>,
    ) -> Self {
        println!("--- CDQN Runtime Initialization (The Guardrail) ---");

        // 1. Initialize Core Components
        let hlc = HybridLogicalClock::new();
        let genesis_cdu = Self::create_genesis_cdu(&hlc);
        let manifold = Arc::new(Manifold::new(genesis_cdu, storage_path));
        let dispatcher = CduDispatcher::new();

        println!("Manifold Initialized. Genesis ID: {}", cdqn_cryptocore::hex_encode(&manifold.genesis_id));
        println!("CDU Dispatcher Ready.");

        let executor = Executor::new();
        let num_agents = 2; // Verifier + Evolution
        let agent_startup_barrier = Arc::new(Barrier::new(num_agents + 1));

        let mut runtime = CdqnRuntime {
            manifold,
            dispatcher,
            agent_handles: Vec::new(),
            agent_startup_barrier,
            executor,
        };

        // 2. Spawn Core Agents (The Chronosa Intelligence) with test channels
        runtime.spawn_verifier_agent(verifier_tx);
        runtime.spawn_evolution_agent(evolution_tx);

        println!("--- Runtime Ready ---");
        runtime
    }

    /// Creates the sovereign Genesis CDU for the node.
    fn create_genesis_cdu(hlc: &HybridLogicalClock) -> Cdu {
        let os_name = std::env::consts::OS;
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        
        let seed = format!("cdqn-genesis-{}-{}", os_name, timestamp);
        let hardware_fp = hash_sha3_256(seed.as_bytes());
        let node_id = hardware_fp.to_vec();

        let payload = GenesisPayload {
            hardware_fingerprint: hardware_fp,
            os: os_name.to_string(),
            timestamp: (timestamp / 1_000_000_000) as u64,
            location: "RuntimeInit".to_string(),
        };
        
        Cdu::create_genesis_cdu(payload, node_id, hlc)
    }

    /// Spawns the Verifier Agent thread, passing an optional test channel.
    fn spawn_verifier_agent(&mut self, test_tx: Option<mpsc::Sender<String>>) {
        let manifold_clone = self.manifold.clone();
        let dispatcher_clone = self.dispatcher.clone_for_agent();
        let barrier_clone = self.agent_startup_barrier.clone();

        let handle = thread::spawn(move || {
            let mut verifier = VerifierAgent::new(&dispatcher_clone, manifold_clone);
            barrier_clone.wait(); 
            verifier.run(test_tx); // FIX: Pass the channel to the agent's run loop
        });

        self.agent_handles.push(handle);
        println!("Agent Spawned: VerifierAgent");
    }

    /// Spawns the Evolution Agent thread, passing an optional test channel.
    fn spawn_evolution_agent(&mut self, test_tx: Option<mpsc::Sender<String>>) {
        let manifold_clone = self.manifold.clone();
        let dispatcher_clone = self.dispatcher.clone_for_agent();
        let barrier_clone = self.agent_startup_barrier.clone();

        let handle = thread::spawn(move || {
            let mut evolution = EvolutionAgent::new(&dispatcher_clone, manifold_clone);
            barrier_clone.wait(); 
            evolution.run(test_tx); // FIX: Pass the channel to the agent's run loop
        });

        self.agent_handles.push(handle);
        println!("Agent Spawned: EvolutionAgent");
    }

    /// The main loop to keep the runtime alive.
    pub fn run_forever(mut self) {
        self.agent_startup_barrier.wait(); 
        
        println!("CDQN Runtime (Guardrail) is running. Press Ctrl+C to stop.");
        
        // Block the main thread, waiting for all agent threads to finish.
        // We must drain the handles to join them.
        for handle in self.agent_handles.drain(..) {
            handle.join().expect("Agent thread panicked");
        }
    }
}
