// crates/runtime/src/lib.rs
// File under the BaDaaS license, code generated by the ai assistant: Claude-Opus-4-1-search, Anthropic

//! The CDQN Runtime: The sovereign guardrail and orchestration layer.
//!
//! This module initializes the Manifold, the Dispatcher, and spawns the Chronosa Agent threads.
//! It is architecturally separate from the Chronosa cognitive engine.

use cdqn_chronosa::{CduDispatcher, VerifierAgent, EvolutionAgent};
use cdqn_cdu::{Cdu, GenesisPayload};
use cdqn_manifold::Manifold;
use cdqn_hlc::HybridLogicalClock;
use cdqn_cryptocore::{hash_sha3_256};
use std::sync::{Arc, mpsc};
use std::thread::{self, JoinHandle};
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

#[cfg(test)]
mod tests;

mod executor; 
pub use executor::Executor;

/// The main CDQN Runtime struct (The Guardrail).
/// FIX: Removed blocking Barrier - agents start immediately in async fashion
pub struct CdqnRuntime {
    pub manifold: Arc<Manifold>,
    pub dispatcher: CduDispatcher,
    pub agent_handles: Vec<JoinHandle<()>>,
    pub executor: Executor,
}

impl CdqnRuntime {
    /// Initializes the CDQN Runtime for production use.
    #[must_use]
    pub fn new(storage_path: PathBuf) -> Self {
        Self::new_with_test_channels(storage_path, None, None)
    }

    /// Initializes the CDQN Runtime with optional test channels for deterministic testing.
    /// FIX: Truly async initialization - no blocking barriers
    #[must_use]
    pub fn new_with_test_channels(
        storage_path: PathBuf,
        verifier_tx: Option<mpsc::Sender<String>>,
        evolution_tx: Option<mpsc::Sender<String>>,
    ) -> Self {
        println!("--- CDQN Runtime Initialization (The Guardrail) ---");

        // 1. Initialize Core Components
        let hlc = HybridLogicalClock::new();
        let genesis_cdu = Self::create_genesis_cdu(&hlc);
        let manifold = Arc::new(Manifold::new(genesis_cdu, storage_path));
        let dispatcher = CduDispatcher::new();

        println!("Manifold Initialized. Genesis ID: {}", cdqn_cryptocore::hex_encode(&manifold.genesis_id));
        println!("CDU Dispatcher Ready.");

        // 2. Initialize the async Executor
        let executor = Executor::new();

        let mut runtime = CdqnRuntime {
            manifold,
            dispatcher,
            agent_handles: Vec::new(),
            executor,
        };

        // 3. Spawn Core Agents asynchronously - they start immediately
        // FIX: No barrier needed - agents use dispatcher's wait_for_new_cdu() for async coordination
        runtime.spawn_verifier_agent(verifier_tx);
        runtime.spawn_evolution_agent(evolution_tx);

        println!("--- Runtime Ready (Async, Non-Blocking) ---");
        runtime
    }

    /// Creates the sovereign Genesis CDU for the node.
    fn create_genesis_cdu(hlc: &HybridLogicalClock) -> Cdu {
        let os_name = std::env::consts::OS;
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        
        let seed = format!("cdqn-genesis-{}-{}", os_name, timestamp);
        let hardware_fp = hash_sha3_256(seed.as_bytes());
        let node_id = hardware_fp.to_vec();

        let payload = GenesisPayload {
            hardware_fingerprint: hardware_fp,
            os: os_name.to_string(),
            timestamp: (timestamp / 1_000_000_000) as u64,
            location: "RuntimeInit".to_string(),
        };
        
        Cdu::create_genesis_cdu(payload, node_id, hlc)
    }

    /// Spawns the Verifier Agent thread asynchronously.
    /// FIX: Agent starts immediately - no barrier blocking
    fn spawn_verifier_agent(&mut self, test_tx: Option<mpsc::Sender<String>>) {
        let manifold_clone = self.manifold.clone();
        let dispatcher_clone = self.dispatcher.clone_for_agent();

        let handle = thread::spawn(move || {
            let mut verifier = VerifierAgent::new(&dispatcher_clone, manifold_clone);
            println!("VerifierAgent: Started async processing loop");
            // FIX: Start immediately - agent uses dispatcher.wait_for_new_cdu() internally
            verifier.run(test_tx);
        });

        self.agent_handles.push(handle);
        println!("Agent Spawned: VerifierAgent (async, non-blocking)");
    }

    /// Spawns the Evolution Agent thread asynchronously.
    /// FIX: Agent starts immediately - no barrier blocking
    fn spawn_evolution_agent(&mut self, test_tx: Option<mpsc::Sender<String>>) {
        let manifold_clone = self.manifold.clone();
        let dispatcher_clone = self.dispatcher.clone_for_agent();

        let handle = thread::spawn(move || {
            let mut evolution = EvolutionAgent::new(&dispatcher_clone, manifold_clone);
            println!("EvolutionAgent: Started async processing loop");
            // FIX: Start immediately - agent uses dispatcher.wait_for_new_cdu() internally
            evolution.run(test_tx);
        });

        self.agent_handles.push(handle);
        println!("Agent Spawned: EvolutionAgent (async, non-blocking)");
    }

    /// The main loop to keep the runtime alive.
    /// FIX: No barrier needed - just wait for agents to complete
    pub fn run_forever(mut self) {
        println!("CDQN Runtime is running (fully async). Press Ctrl+C to stop.");
        
        // Simply wait for all agent threads to finish
        // Agents coordinate through the dispatcher's async mechanisms
        for handle in self.agent_handles.drain(..) {
            handle.join().expect("Agent thread panicked");
        }
    }

    /// Test helper: Checks if all agents are ready to process
    /// Uses the dispatcher's async mechanisms instead of blocking
    #[cfg(test)]
    pub fn is_ready(&self) -> bool {
        // Agents are always ready in async design - they wait on dispatcher.wait_for_new_cdu()
        true
    }
}
