// crates/runtime/src/tests.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! Integration tests for the CDQN Runtime and Chronosa Agent execution.
//!
//! These tests verify the full Cognitive Cycle (Dispatcher -> Agent -> Logic).

use crate::CdqnRuntime;
use cdqn_cdu::{Cdu, AxiomPayload, World};
use cdqn_hlc::HybridLogicalClock;
use cdqn_cryptocore::hash_sha3_256;
use std::path::PathBuf;
use std::thread;
use std::time::Duration;
use std::fs;
use std::env;
use std::sync::mpsc;

// Helper function to create a sovereign temporary directory
fn create_sovereign_temp_dir() -> PathBuf {
    let temp_dir = env::temp_dir().join(format!("cdqn_test_manifold_{}", std::process::id()));
    fs::create_dir_all(&temp_dir).expect("Failed to create sovereign temp directory");
    temp_dir
}

// Helper function to clean up the sovereign temporary directory
fn cleanup_sovereign_temp_dir(path: &PathBuf) {
    if path.exists() {
        fs::remove_dir_all(path).expect("Failed to clean up sovereign temp directory");
    }
}

// Helper function to create a test CDU for the simulation
fn create_test_cdu(statement: &str, r_coordinate: f64, genesis_id: &[u8], node_signer: &cdqn_cryptocore::SignerEntity) -> Cdu {
    let hlc = HybridLogicalClock::new();
    
    // NodeId is derived from the signer's public key hash
    let node_id = hash_sha3_256(node_signer.verification_key().as_bytes()).to_vec();
    
    let axiom_payload = AxiomPayload {
        statement: statement.to_string(),
    };
    let payload = axiom_payload.into_payload();

    let metadata = cdqn_cdu::Metadata {
        author_node: node_id.clone(),
        // FIX: Link to the Genesis CDU
        context_refs: vec![genesis_id.to_vec()], 
        state: "draft".to_string(),
        weight: 1.0,
        r_coordinate,
        world_context: World::UserWorld,
        hlc_timestamp: hlc.new_timestamp(),
        symmetric_counterpart: None,
        validated_worlds: std::collections::HashSet::new(),
    };

    let mut cdu = Cdu::new(payload, metadata, &hlc, &node_id);
    
    // FIX: Sign the CDU to satisfy the "No Anonymous Entities" rule
    cdu.sign(node_signer, &hlc).expect("CDU signing failed in test helper");
    
    cdu
}

/// This test verifies the full Cognitive Cycle by injecting CDUs and checking the Agent's output.
#[test]
fn test_full_cognitive_cycle_verifier() {
    let storage_path = create_sovereign_temp_dir();
    
    // 1. Initialize the CDQN Runtime (The Guardrail)
    let runtime = CdqnRuntime::new(storage_path.clone());
    
    // 2. Setup deterministic communication channel
    let (tx, rx) = mpsc::channel();
    
    // 3. Start the Verifier Agent on a separate thread
    let dispatcher_clone = runtime.dispatcher.clone_for_agent();
    let manifold_clone = runtime.manifold.clone();
    let genesis_id = runtime.manifold.genesis_id.clone();
    
    // FIX: Create a dedicated ephemeral signer for the test
    let test_signer = cdqn_cryptocore::SignerEntity::new_random("TestNodeSigner");

    let _agent_handle = thread::spawn(move || {
        let mut verifier = cdqn_chronosa::VerifierAgent::new(&dispatcher_clone, manifold_clone);
        verifier.run(Some(tx)); // Pass the sender to the Agent
    });

    // NOTE: We must wait briefly for the VerifierAgent thread to start its polling loop.
    thread::sleep(Duration::from_millis(10));
    
    // --- SIMULATION: Injecting Test CDUs ---
    
    // 4. Inject a Valid CDU (r_coordinate > 1.0)
    println!("\nSIMULATION STEP 1: Injecting Valid CDU (R=2.5)");
    let valid_cdu = create_test_cdu("Valid Axiom", 2.5, &genesis_id, &test_signer);
    runtime.dispatcher.publish(valid_cdu).expect("Failed to publish Valid CDU");

    // 5. Inject a Contradictory CDU (r_coordinate in Impossibility Zone [0.5])
    println!("SIMULATION STEP 2: Injecting Contradictory CDU (R=0.5)");
    let contradictory_cdu = create_test_cdu("Contradictory Fact", 0.5, &genesis_id, &test_signer);
    runtime.dispatcher.publish(contradictory_cdu).expect("Failed to publish Contradictory CDU");

    // --- DETERMINISTIC VERIFICATION ---
    let timeout = Duration::from_millis(500);

    // 6. Wait for both CDU results (Order is not guaranteed)
    // FIX: Explicitly annotate the type as String
    let result1: String = rx.recv_timeout(timeout).expect("Agent failed to report first CDU result");
    let result2: String = rx.recv_timeout(timeout).expect("Agent failed to report second CDU result");

    // --- ASSERTIONS ---
    // FIX: Assertions are now order-agnostic.
    let outcomes = vec![result1, result2];
    
    // VERBOSE LOGGING: Print the received order for CI clarity
    println!("\nVERIFICATION RESULTS (Order Received):");
    println!("Result 1: {}", outcomes[0]);
    println!("Result 2: {}", outcomes[1]);
    println!("--------------------------------------");

    // Assertion 1: Check for the successful verification (RWorld > 1.0)
    assert!(
        outcomes.iter().any(|s| s.contains("VERIFIED (RWorld: 2.5)")),
        "Verifier failed to confirm the Valid CDU. Outcomes: {:?}", outcomes
    );

    // Assertion 2: Check for the contradiction detection (RWorld in [-1, 1])
    assert!(
        outcomes.iter().any(|s| s.contains("CONTRADICTION (RWorld: 0.5)")),
        "Verifier failed to detect the Contradictory CDU. Outcomes: {:?}", outcomes
    );

    // FIX: Clean up the temporary directory
    cleanup_sovereign_temp_dir(&storage_path);
}
