// crates/runtime/src/tests.rs
// File under the BaDaaS license, code generated by the ai assistant: o3-search, OpenAi

//! Integration tests for the CDQN Runtime and Chronosa Agent execution.
//!
//! These tests verify the full Cognitive Cycle (Dispatcher → Agent → Logic).

use crate::CdqnRuntime;
use cdqn_cdu::{Cdu, AxiomPayload, World};
use cdqn_hlc::HybridLogicalClock;
use cdqn_cryptocore::hash_sha3_256;
use std::path::PathBuf;
use std::fs;
use std::env;
use std::sync::mpsc;
use std::collections::HashMap;

// ---------- helpers ---------------------------------------------------------

fn create_sovereign_temp_dir() -> PathBuf {
    let dir = env::temp_dir().join(format!("cdqn_test_manifold_{}", std::process::id()));
    fs::create_dir_all(&dir).expect("Failed to create temp dir");
    dir
}

fn cleanup_sovereign_temp_dir(dir: &PathBuf) {
    if dir.exists() {
        fs::remove_dir_all(dir).expect("Failed to clean temp dir");
    }
}

fn create_test_cdu(
    statement: &str,
    r_coordinate: f64,
    genesis_id: &[u8],
    signer: &cdqn_cryptocore::SignerEntity,
) -> Cdu {
    let hlc = HybridLogicalClock::new();
    let node_id = hash_sha3_256(signer.verification_key().as_bytes()).to_vec();

    let payload = AxiomPayload {
        statement: statement.to_string(),
    }
    .into_payload();

    let metadata = cdqn_cdu::Metadata {
        author_node: node_id.clone(),
        context_refs: vec![genesis_id.to_vec()],
        state: "draft".to_string(),
        weight: 1.0,
        r_coordinate,
        world_context: World::UserWorld,
        hlc_timestamp: hlc.new_timestamp(),
        symmetric_counterpart: None,
        validated_worlds: std::collections::HashSet::new(),
        task_footprints: HashMap::new(),
    };

    let mut cdu = Cdu::new(payload, metadata, &hlc, &node_id);
    cdu.sign(signer, &hlc).expect("CDU signing failed");
    cdu
}

// ---------- test ------------------------------------------------------------

#[test]
fn test_full_cognitive_cycle_verifier() {
    let storage = create_sovereign_temp_dir();

    // deterministic agent-report channels
    let (tx_verifier, rx_verifier) = mpsc::channel();
    let (tx_evolution, rx_evolution) = mpsc::channel();

    // runtime with injected channels
    let runtime = CdqnRuntime::new_with_test_channels(
        storage.clone(),
        Some(tx_verifier),
        Some(tx_evolution),
    );

    // signer and genesis ID for test CDUs
    let test_signer = cdqn_cryptocore::SignerEntity::new_random("TestNodeSigner");
    let genesis_id = runtime.manifold.genesis_id.clone();

    // inject one valid and one contradictory CDU
    let valid_cdu = create_test_cdu("Valid Axiom", 2.5, &genesis_id, &test_signer);
    runtime.dispatcher.publish(valid_cdu).unwrap();

    let bad_cdu = create_test_cdu("Contradictory Fact", 0.5, &genesis_id, &test_signer);
    runtime.dispatcher.publish(bad_cdu).unwrap();

    // collect verifier & evolution outputs (blocking – agents send when ready)
    let v1: String = rx_verifier.recv().expect("no verifier msg #1");
    let v2: String = rx_verifier.recv().expect("no verifier msg #2");
    let evo: String = rx_evolution.recv().expect("no evolution msg");

    let verifier_outcomes = vec![v1, v2];

    println!("\nVERIFICATION RESULTS:");
    println!("  outcome #1: {}", verifier_outcomes[0]);
    println!("  outcome #2: {}", verifier_outcomes[1]);
    println!("  evolution : {}", evo);
    println!("--------------------------------------");

    // assertions
    assert!(
        verifier_outcomes
            .iter()
            .any(|s| s.contains("VERIFIED (RWorld: 2.5)")),
        "Valid CDU not verified: {:?}", verifier_outcomes
    );

    assert!(
        verifier_outcomes
            .iter()
            .any(|s| s.contains("CONTRADICTION (RWorld: 0.5)")),
        "Contradictory CDU not detected: {:?}", verifier_outcomes
    );

    assert!(
        evo.contains("RESOLVED: Resolved with Hash:"),
        "Evolution agent did not resolve contradiction: {}", evo
    );

    cleanup_sovereign_temp_dir(&storage);
}
