// File under BaDaaS license and generated by the vibe coding engine GLM-4.6 from chat.z.ai
// File path: src/reasoning/mod.rs

//! The reasoning module for Chronosa.
//!
//! This module contains the core components of Chronosa's reasoning model,
//! including prime elements, semi-axioms, and the reasoning projector.

pub mod prime_element;
pub mod semi_axiom;
pub mod reasoning_projector;

// Re-export for easier access
pub use prime_element::PrimeElement;
pub use semi_axiom::SemiAxiom;
pub use reasoning_projector::ReasoningProjector;
