// File under BaDaaS license and generated by the vibe coding engine GLM-4.6 from chat.z.ai
// File path: src/reasoning/prime_element.rs

use crate::cdu::{Cdu, CduId, CduMetadata, CduPayload, CduType};
use crate::hlc::Hlc;
use std::collections::HashMap;

/// Represents a prime element in Chronosa's reasoning model
#[derive(Debug, Clone)]
pub struct PrimeElement {
    /// Unique identifier for the prime element
    pub id: String,
    /// World context this prime element belongs to
    pub world: String,
    /// Mathematical representation as a real number
    pub representation: f64,
    /// Conceptual description
    pub description: String,
    /// Proof of irreducibility
    pub irreducibility_proof: String,
    /// Relationships to other prime elements
    pub relationships: HashMap<String, String>,
}

impl PrimeElement {
    /// Create a new prime element
    pub fn new(
        id: String,
        world: String,
        representation: f64,
        description: String,
        irreducibility_proof: String,
    ) -> Self {
        Self {
            id,
            world,
            representation,
            description,
            irreducibility_proof,
            relationships: HashMap::new(),
        }
    }

    /// Add a relationship to another prime element
    pub fn add_relationship(&mut self, target_id: String, relationship_type: String) {
        self.relationships.insert(target_id, relationship_type);
    }

    /// Convert to CDU
    pub fn to_cdu(&self) -> Cdu {
        let payload = CduPayload::PrimeElement(self.clone());
        let metadata = CduMetadata::new(
            Hlc::now(),
            format!("prime.element.{}", self.world),
        );
        Cdu::new(payload, metadata)
    }
}

/// Manager for prime elements
#[derive(Debug)]
pub struct PrimeElementManager {
    /// Storage for prime elements by ID
    elements: HashMap<String, PrimeElement>,
    /// Index of elements by world
    world_index: HashMap<String, Vec<String>>,
}

impl PrimeElementManager {
    /// Create a new prime element manager
    pub fn new() -> Self {
        Self {
            elements: HashMap::new(),
            world_index: HashMap::new(),
        }
    }

    /// Add a prime element
    pub fn add_element(&mut self, element: PrimeElement) {
        let world = element.world.clone();
        let id = element.id.clone();
        
        // Add to main storage
        self.elements.insert(id.clone(), element);
        
        // Update world index
        if !self.world_index.contains_key(&world) {
            self.world_index.insert(world.clone(), Vec::new());
        }
        self.world_index.get_mut(&world).unwrap().push(id);
    }

    /// Get a prime element by ID
    pub fn get_element(&self, id: &str) -> Option<&PrimeElement> {
        self.elements.get(id)
    }

    /// Get all prime elements for a specific world
    pub fn get_elements_by_world(&self, world: &str) -> Vec<&PrimeElement> {
        if let Some(ids) = self.world_index.get(world) {
            ids.iter()
                .filter_map(|id| self.elements.get(id))
                .collect()
        } else {
            Vec::new()
        }
    }

    /// Check if an element is prime (irreducible)
    pub fn is_prime(&self, id: &str) -> bool {
        self.elements.contains_key(id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prime_element_creation() {
        let element = PrimeElement::new(
            "test_element".to_string(),
            "test_world".to_string(),
            42.0,
            "A test element".to_string(),
            "Cannot be decomposed".to_string(),
        );

        assert_eq!(element.id, "test_element");
        assert_eq!(element.world, "test_world");
        assert_eq!(element.representation, 42.0);
    }

    #[test]
    fn test_prime_element_manager() {
        let mut manager = PrimeElementManager::new();
        
        let element = PrimeElement::new(
            "test_element".to_string(),
            "test_world".to_string(),
            42.0,
            "A test element".to_string(),
            "Cannot be decomposed".to_string(),
        );
        
        manager.add_element(element);
        
        assert!(manager.is_prime("test_element"));
        assert!(manager.get_element("test_element").is_some());
        
        let world_elements = manager.get_elements_by_world("test_world");
        assert_eq!(world_elements.len(), 1);
    }
}
