// File under BaDaaS license, vibe coding engine: Gemini 2.5 Pro, Google
// File path: src/reasoning/reasoning_projector.rs

//! The ReasoningProjector for Chronosa's advanced reasoning model.
//! This projector acts as an orchestrator for a pipeline of reasoning strategies.

use crate::cdu::Cdu;
use crate::engine::Projector;
use crate::reasoning::knowledge_base::KnowledgeBase;
use crate::reasoning::strategy::{
    AxiomEvaluationStrategy, ConstraintStrategy, DecompositionStrategy, ReasoningContext,
    ReasoningStrategy, TheoremStrategy,
};
use crate::state::ChronosaState;

/// The ReasoningProjector orchestrates a sequence of reasoning strategies.
pub struct ReasoningProjector {
    strategies: Vec<Box<dyn ReasoningStrategy + Send + Sync>>,
}

impl ReasoningProjector {
    /// Creates a new ReasoningProjector with the default strategy pipeline.
    pub fn new() -> Self {
        Self {
            strategies: vec![
                Box::new(DecompositionStrategy),
                Box::new(TheoremStrategy),
                Box::new(ConstraintStrategy),
                Box::new(AxiomEvaluationStrategy),
            ],
        }
    }
}

impl Default for ReasoningProjector {
    fn default() -> Self {
        Self::new()
    }
}

impl Projector for ReasoningProjector {
    /// Projects the input CDU by running it through the strategy pipeline.
    fn project(&self, state: &ChronosaState, input: &Cdu) -> Vec<Cdu> {
        // 1. Create a snapshot of the current knowledge.
        let kb = KnowledgeBase::from_state(state);

        // 2. Create a mutable context to be passed through the pipeline.
        let mut context = ReasoningContext::new(&kb, input);

        // 3. Execute each strategy in order.
        for strategy in &self.strategies {
            strategy.execute(&mut context);

            // If a strategy is conclusive (e.g., a theorem was found),
            // we can terminate the pipeline early.
            if context.is_conclusive {
                break;
            }
        }

        // 4. Return the final list of new CDUs generated by the pipeline.
        context.new_cdus
    }
}

// The previous test module has been removed as it is no longer relevant
// to the current foundational focus of the project.
