// File under BaDaaS license, vibe coding engine: Gemini 2.5 Pro, Google
// File path: src/reasoning/reasoning_projector.rs

//! The ReasoningProjector for Chronosa's advanced reasoning model.
//! This projector acts as an orchestrator for a pipeline of reasoning strategies.

use crate::cdu::Cdu;
use crate::engine::Projector;
use crate::reasoning::knowledge_base::KnowledgeBase;
use crate::reasoning::strategy::{
    AxiomEvaluationStrategy, ConstraintStrategy, ReasoningContext, ReasoningStrategy,
    TheoremStrategy,
};
use crate::state::ChronosaState;

/// The ReasoningProjector orchestrates a sequence of reasoning strategies.
pub struct ReasoningProjector {
    strategies: Vec<Box<dyn ReasoningStrategy + Send + Sync>>,
}

impl ReasoningProjector {
    /// Creates a new ReasoningProjector with the default strategy pipeline.
    pub fn new() -> Self {
        Self {
            strategies: vec![
                Box::new(TheoremStrategy),
                Box::new(ConstraintStrategy),
                Box::new(AxiomEvaluationStrategy),
            ],
        }
    }
}

impl Default for ReasoningProjector {
    fn default() -> Self {
        Self::new()
    }
}

impl Projector for ReasoningProjector {
    /// Projects the input CDU by running it through the strategy pipeline.
    fn project(&self, state: &ChronosaState, input: &Cdu) -> Vec<Cdu> {
        // 1. Create a snapshot of the current knowledge.
        let kb = KnowledgeBase::from_state(state);

        // 2. Create a mutable context to be passed through the pipeline.
        let mut context = ReasoningContext::new(&kb, input);

        // 3. Execute each strategy in order.
        for strategy in &self.strategies {
            strategy.execute(&mut context);

            // If a strategy is conclusive (e.g., a theorem was found),
            // we can terminate the pipeline early.
            if context.is_conclusive {
                break;
            }
        }

        // 4. Return the final commands generated by the pipeline.
        context.commands
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cdu::{Constraint, Theorem};
    use crate::reasoning::{PrimeElement, SemiAxiom};

    /// Helper function to manually evolve a state for testing purposes.
    fn test_evolve(mut state: ChronosaState, event: Cdu) -> ChronosaState {
        if event.metadata.hlc > state.hlc {
            state.hlc = event.metadata.hlc.clone();
        }
        state.log.push(event);
        state
    }

    #[test]
    fn test_reasoning_projector() {
        let mut initial_state = ChronosaState::default();
        let pe1 = PrimeElement::new(
            "pe-1".to_string(),
            "uworld".to_string(),
            1.0,
            "User is present".to_string(),
            "Cannot be decomposed".to_string(),
        );
        initial_state = test_evolve(initial_state, pe1.to_cdu());
        let axiom1 = SemiAxiom::new(
            "axiom-1".to_string(),
            "uworld".to_string(),
            vec!["pe-1".to_string()],
            "If user is present, greet them".to_string(),
        );
        initial_state = test_evolve(initial_state, axiom1.to_cdu());
        let projector = ReasoningProjector::new();
        let input = Cdu::new(b"User says hello".to_vec(), "observation.uworld", vec![]);
        let commands = projector.project(&initial_state, &input);
        assert_eq!(commands.len(), 1);
        assert!(commands[0].name.contains(".command.reasoned"));
        assert_eq!(commands[0].metadata.causes[0], "axiom-1");
    }

    #[test]
    fn test_reasoning_projector_fails_axiom() {
        let mut initial_state = ChronosaState::default();
        let axiom1 = SemiAxiom::new(
            "axiom-1".to_string(),
            "uworld".to_string(),
            vec!["pe-missing".to_string()],
            "If user is present, greet them".to_string(),
        );
        initial_state = test_evolve(initial_state, axiom1.to_cdu());
        let projector = ReasoningProjector::new();
        let input = Cdu::new(b"User says hello".to_vec(), "observation.uworld", vec![]);
        let commands = projector.project(&initial_state, &input);
        assert_eq!(commands.len(), 0);
    }

    #[test]
    fn test_reasoning_projector_inhibits_axiom() {
        let mut initial_state = ChronosaState::default();
        let pe1 = PrimeElement::new(
            "pe-user-present".to_string(),
            "uworld".to_string(),
            1.0,
            "User is present".to_string(),
            "Cannot be decomposed".to_string(),
        );
        initial_state = test_evolve(initial_state, pe1.to_cdu());
        let pe_emergency_context = PrimeElement::new(
            "emergency".to_string(),
            "uworld".to_string(),
            0.9,
            "A state of emergency".to_string(),
            "".to_string(),
        );
        initial_state = test_evolve(initial_state, pe_emergency_context.to_cdu());
        let axiom1 = SemiAxiom::new(
            "axiom-greet-user".to_string(),
            "uworld".to_string(),
            vec!["pe-user-present".to_string()],
            "If user is present, greet them".to_string(),
        );
        initial_state = test_evolve(initial_state, axiom1.to_cdu());
        let constraint = Constraint {
            target_path: vec!["axiom-greet-user".to_string()],
            inhibiting_context: "emergency".to_string(),
            reason: "Do not greet during an emergency".to_string(),
            world: "uworld".to_string(),
        };
        let constraint_cdu =
            Cdu::from_payload(CduPayload::Constraint(constraint), "constraint.uworld", vec![]);
        initial_state = test_evolve(initial_state, constraint_cdu);
        let projector = ReasoningProjector::new();
        let input = Cdu::new(
            b"User shouts for help".to_vec(),
            "observation.emergency",
            vec![],
        );
        let commands = projector.project(&initial_state, &input);
        assert_eq!(commands.len(), 0);
    }

    #[test]
    fn test_reasoning_projector_uses_theorem() {
        let mut initial_state = ChronosaState::default();
        let pe1 = PrimeElement::new(
            "pe-a".to_string(),
            "uworld".to_string(),
            1.0,
            "A".to_string(),
            "".to_string(),
        );
        initial_state = test_evolve(initial_state, pe1.to_cdu());
        let pe2 = PrimeElement::new(
            "pe-b".to_string(),
            "uworld".to_string(),
            1.0,
            "B".to_string(),
            "".to_string(),
        );
        initial_state = test_evolve(initial_state, pe2.to_cdu());
        let theorem = Theorem {
            premises: vec!["pe-a".to_string(), "pe-b".to_string()],
            conclusion: "Conclusion C".to_string(),
            proof_path: vec![],
            confidence_score: 1.0,
        };
        let theorem_cdu = Cdu::from_payload(CduPayload::Theorem(theorem), "theorem.uworld", vec![]);
        initial_state = test_evolve(initial_state, theorem_cdu);
        let axiom1 = SemiAxiom::new(
            "axiom-1".to_string(),
            "uworld".to_string(),
            vec!["pe-a".to_string()],
            "This should not fire".to_string(),
        );
        initial_state = test_evolve(initial_state, axiom1.to_cdu());
        let projector = ReasoningProjector::new();
        let input = Cdu::new(b"trigger".to_vec(), "observation.uworld", vec![]);
        let commands = projector.project(&initial_state, &input);
        assert_eq!(commands.len(), 1);
        assert!(commands[0].name.contains(".command.theorem"));
        assert_eq!(commands[0].metadata.causes[0], "Conclusion C");
    }
}
