// File under BaDaaS license and generated by the vibe coding engine GLM-4.6 from chat.z.ai
// File path: src/reasoning/semi_axiom.rs

use crate::cdu::Cdu;

/// Represents a semi-axiom as a prime ideal of prime elements in Chronosa's reasoning model.
#[derive(Debug, Clone)]
pub struct SemiAxiom {
    /// Unique identifier for the semi-axiom
    pub id: String,
    /// World context this semi-axiom belongs to
    pub world: String,
    /// Constituent prime elements that form this prime ideal
    pub prime_elements: Vec<String>, // Storing IDs for now
    /// Description of the semi-axiom's rule or constraint
    pub description: String,
    /// Current weight of the semi-axiom, determined by links
    pub weight: f64,
}

impl SemiAxiom {
    /// Create a new semi-axiom
    pub fn new(
        id: String,
        world: String,
        prime_elements: Vec<String>,
        description: String,
    ) -> Self {
        Self {
            id,
            world,
            prime_elements,
            description,
            weight: 1.0, // Default initial weight
        }
    }

    /// Update the weight of the semi-axiom
    pub fn update_weight(&mut self, new_weight: f64) {
        self.weight = new_weight;
    }

    /// Convert to CDU
    pub fn to_cdu(&self) -> Cdu {
        let payload_bytes = self.to_bytes();
        let subtype = format!("semi-axiom.prime-ideal.{}", self.world);
        Cdu::new(payload_bytes, &subtype, vec![])
    }

    /// Convert the SemiAxiom to a byte representation for storage
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();

        // Serialize id
        bytes.extend_from_slice(&(self.id.len() as u32).to_le_bytes());
        bytes.extend_from_slice(self.id.as_bytes());

        // Serialize world
        bytes.extend_from_slice(&(self.world.len() as u32).to_le_bytes());
        bytes.extend_from_slice(self.world.as_bytes());

        // Serialize prime_elements
        bytes.extend_from_slice(&(self.prime_elements.len() as u32).to_le_bytes());
        for element_id in &self.prime_elements {
            bytes.extend_from_slice(&(element_id.len() as u32).to_le_bytes());
            bytes.extend_from_slice(element_id.as_bytes());
        }

        // Serialize description
        bytes.extend_from_slice(&(self.description.len() as u32).to_le_bytes());
        bytes.extend_from_slice(self.description.as_bytes());

        // Serialize weight
        bytes.extend_from_slice(&self.weight.to_le_bytes());

        bytes
    }

    /// Create a SemiAxiom from a byte representation
    pub fn from_bytes(bytes: &[u8]) -> Option<Self> {
        let mut pos = 0;

        // Deserialize id
        if pos + 4 > bytes.len() {
            return None;
        }
        let id_len =
            u32::from_le_bytes([bytes[pos], bytes[pos + 1], bytes[pos + 2], bytes[pos + 3]])
                as usize;
        pos += 4;
        if pos + id_len > bytes.len() {
            return None;
        }
        let id = String::from_utf8(bytes[pos..pos + id_len].to_vec()).ok()?;
        pos += id_len;

        // Deserialize world
        if pos + 4 > bytes.len() {
            return None;
        }
        let world_len =
            u32::from_le_bytes([bytes[pos], bytes[pos + 1], bytes[pos + 2], bytes[pos + 3]])
                as usize;
        pos += 4;
        if pos + world_len > bytes.len() {
            return None;
        }
        let world = String::from_utf8(bytes[pos..pos + world_len].to_vec()).ok()?;
        pos += world_len;

        // Deserialize prime_elements
        if pos + 4 > bytes.len() {
            return None;
        }
        let elements_count =
            u32::from_le_bytes([bytes[pos], bytes[pos + 1], bytes[pos + 2], bytes[pos + 3]])
                as usize;
        pos += 4;
        let mut prime_elements = Vec::new();
        for _ in 0..elements_count {
            if pos + 4 > bytes.len() {
                return None;
            }
            let element_id_len =
                u32::from_le_bytes([bytes[pos], bytes[pos + 1], bytes[pos + 2], bytes[pos + 3]])
                    as usize;
            pos += 4;
            if pos + element_id_len > bytes.len() {
                return None;
            }
            let element_id = String::from_utf8(bytes[pos..pos + element_id_len].to_vec()).ok()?;
            pos += element_id_len;
            prime_elements.push(element_id);
        }

        // Deserialize description
        if pos + 4 > bytes.len() {
            return None;
        }
        let desc_len =
            u32::from_le_bytes([bytes[pos], bytes[pos + 1], bytes[pos + 2], bytes[pos + 3]])
                as usize;
        pos += 4;
        if pos + desc_len > bytes.len() {
            return None;
        }
        let description = String::from_utf8(bytes[pos..pos + desc_len].to_vec()).ok()?;
        pos += desc_len;

        // Deserialize weight
        if pos + 8 > bytes.len() {
            return None;
        }
        let weight = f64::from_le_bytes([
            bytes[pos],
            bytes[pos + 1],
            bytes[pos + 2],
            bytes[pos + 3],
            bytes[pos + 4],
            bytes[pos + 5],
            bytes[pos + 6],
            bytes[pos + 7],
        ]);

        Some(SemiAxiom {
            id,
            world,
            prime_elements,
            description,
            weight,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_semi_axiom_creation() {
        let axiom = SemiAxiom::new(
            "test_axiom".to_string(),
            "test_world".to_string(),
            vec!["element1".to_string(), "element2".to_string()],
            "A test semi-axiom".to_string(),
        );

        assert_eq!(axiom.id, "test_axiom");
        assert_eq!(axiom.world, "test_world");
        assert_eq!(axiom.prime_elements.len(), 2);
        assert_eq!(axiom.weight, 1.0);
    }

    #[test]
    fn test_semi_axiom_serialization() {
        let axiom = SemiAxiom::new(
            "test_axiom".to_string(),
            "test_world".to_string(),
            vec!["element1".to_string(), "element2".to_string()],
            "A test semi-axiom".to_string(),
        );

        let bytes = axiom.to_bytes();
        let deserialized_axiom = SemiAxiom::from_bytes(&bytes).unwrap();

        assert_eq!(axiom.id, deserialized_axiom.id);
        assert_eq!(axiom.world, deserialized_axiom.world);
        assert_eq!(axiom.prime_elements, deserialized_axiom.prime_elements);
        assert_eq!(axiom.description, deserialized_axiom.description);
        assert_eq!(axiom.weight, deserialized_axiom.weight);
    }
}
