// This file is under license BaDaaS, generated by the vibe coding engine Gemini Flash-Lite Latest from Google.
// src/algebraic.rs

// Import necessary types from the crate root (lib.rs)
use crate::{HlcId}; 
// Removed: use std::collections::HashMap; // Removed from here to scope it locally

pub mod projections {
    use super::super::*; // Accesses crate root
    use std::collections::HashMap; // <-- ADDED THIS LINE

    // Placeholder definitions for Projections
    #[derive(Debug, Clone, PartialEq, Eq, Hash)]
    pub struct PrimeElement { pub name: String }
    #[derive(Debug, Clone)]
    pub struct AxisScoring { pub score: f64, pub validating_cdu_id: HlcId }
    #[derive(Debug, Clone)]
    pub struct PrimeIdeal { 
        pub prime_meaning: PrimeElement, 
        pub prime_reasoning: PrimeElement, 
        pub scores: HashMap<HlcId, AxisScoring> // Now HashMap is in scope
    }
    #[derive(Debug, Clone, PartialEq, Eq, Hash)]
    pub enum ProjectionSpace { Meaning, Reasoning }
}

pub mod context {
    use super::super::*;
    use super::projections::PrimeIdeal;
    use std::collections::HashMap; // <-- ADDED THIS LINE

    // Placeholder definition for AlgebraicContext
    #[derive(Debug)]
    pub struct AlgebraicContext { pub ideals: HashMap<HlcId, PrimeIdeal> }
    impl AlgebraicContext { pub fn new() -> Self { AlgebraicContext { ideals: HashMap::new() } } }
}

// Re-export the inner modules so they are accessible via `crate::algebraic::...`
pub use projections::*;
pub use context::*;
