// File under BaDaaS license and generated by the vibe coding engine GLM-4.6 from chat.z.ai
// File path: src/cdu.rs

//! The Causal Data Unit (CDU) module.
//!
//! This is the fundamental, atomic unit of memory for the Chronosa agent.

// Import the Hlc struct from our own hlc module using the 'crate' path.
use crate::hlc::Hlc;
// Import the necessary traits for hashing from the sha2 crate.
use sha2::{Digest, Sha256};

/// The mutable metadata associated with a Causal Data Unit.
/// This contains Chronosa's current interpretation and context of the immutable payload.
#[derive(Debug, Clone)]
pub struct CduMetadata {
    /// The Hybrid Logical Clock timestamp for when this CDU was created or last updated.
    pub hlc: Hlc,
    /// A list of CDU names that are the direct causes for this CDU's existence.
    pub causes: Vec<String>,
    /// User-defined tags for querying and classification.
    pub tags: Vec<String>,
}

/// A Causal Data Unit (CDU).
/// It combines an immutable fact (payload) with mutable, evolving context (metadata).
#[derive(Debug, Clone)]
pub struct Cdu {
    /// The unique, content-addressed name of the CDU.
    /// Format: "<payload_hash>.<subtype>.cdu"
    pub name: String,
    /// The immutable, verifiable data payload. This is the "fact" of what happened.
    /// Represented as a raw byte vector to be maximally generic.
    pub payload: Vec<u8>,
    /// The mutable metadata, representing Chronosa's understanding of the payload.
    pub metadata: CduMetadata,
}

/// Represents the structured content within a CDU payload.
/// This enum allows for type-safe handling of different kinds of information.
#[derive(Debug, Clone)]
pub enum CduPayload {
    /// A raw byte payload for maximum flexibility.
    Raw(Vec<u8>),
    /// A prime element in Chronosa's reasoning model.
    PrimeElement(crate::reasoning::PrimeElement),
    /// A semi-axiom as a prime ideal of prime elements.
    SemiAxiom(crate::reasoning::SemiAxiom),
}

impl Cdu {
    /// Creates a new Causal Data Unit.
    ///
    /// The CDU's name is deterministically generated from the SHA-256 hash of its payload,
    /// and its metadata is timestamped with a new Hybrid Logical Clock value.
    pub fn new(payload: Vec<u8>, subtype: &str, causes: Vec<String>) -> Self {
        let mut hasher = Sha256::new();
        hasher.update(&payload);
        let hash_result = hasher.finalize();
        let payload_hash = format!("{:x}", hash_result);
        let name = format!("{}.{}.cdu", payload_hash, subtype);

        let metadata = CduMetadata {
            hlc: Hlc::new(),
            causes,
            tags: vec![],
        };

        Self {
            name,
            payload,
            metadata,
        }
    }

    /// Creates a new CDU from a CduPayload
    pub fn from_payload(payload: CduPayload, subtype: &str, causes: Vec<String>) -> Self {
        let payload_bytes = match payload {
            CduPayload::Raw(bytes) => bytes,
            CduPayload::PrimeElement(element) => element.to_bytes(),
            CduPayload::SemiAxiom(axiom) => axiom.to_bytes(),
        };
        Self::new(payload_bytes, subtype, causes)
    }

    /// Extracts the structured content from the CDU payload
    pub fn extract_payload(&self) -> Option<CduPayload> {
        if self.name.contains("prime.element.") {
            crate::reasoning::PrimeElement::from_bytes(&self.payload).map(CduPayload::PrimeElement)
        } else if self.name.contains("semi-axiom.prime-ideal.") {
            crate::reasoning::SemiAxiom::from_bytes(&self.payload).map(CduPayload::SemiAxiom)
        } else {
            Some(CduPayload::Raw(self.payload.clone()))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cdu_creation_and_naming() {
        let payload = b"Test payload data".to_vec();
        let subtype = "test_event";
        let cdu = Cdu::new(payload.clone(), subtype, vec![]);

        assert!(cdu.name.contains(subtype));
        assert!(cdu.name.ends_with(".cdu"));
        assert_ne!(cdu.name, format!(".{}.cdu", subtype));
        assert_eq!(cdu.payload, payload);
        assert_ne!(cdu.metadata.hlc.timestamp, 0);
    }

    #[test]
    fn test_cdu_causal_link() {
        let cause_cdu = Cdu::new(b"First event".to_vec(), "genesis", vec![]);
        let effect_cdu = Cdu::new(
            b"Second event".to_vec(),
            "response",
            vec![cause_cdu.name.clone()],
        );

        assert_eq!(effect_cdu.metadata.causes.len(), 1);
        assert_eq!(effect_cdu.metadata.causes[0], cause_cdu.name);
        assert!(effect_cdu.metadata.hlc >= cause_cdu.metadata.hlc);
    }
}
