// This file is under license BaDaaS, generated by the vibe coding engine Gemini Flash-Lite Latest from Google.
// src/cdu.rs

use std::collections::HashMap;
use crate::{HlcId, ReasoningPath}; // Import HlcId and ReasoningPath from the crate root

// --- 1. Hybrid Logical Clock ---

/// Tracks the history of a CDU specific to a reasoning path.
#[derive(Debug, Clone)]
pub struct HybridLogicalClock {
    /// The total number of times this CDU was involved in a successful Path replay.
    pub success_count: u64,
    /// The total number of times this CDU was involved in a failed/KO branch.
    pub failure_count: u64,
    /// A map where the key is the ReasoningPath (Concurrent/Cascading) and the value
    /// is the last 'tick' or version number associated with that path's processing.
    pub path_ticks: HashMap<ReasoningPath, u64>,
}

impl HybridLogicalClock {
    pub fn new() -> Self {
        HybridLogicalClock {
            success_count: 0,
            failure_count: 0,
            path_ticks: HashMap::new(),
        }
    }
}

// --- 2. CDU Subtypes (Using HlcId) ---

#[derive(Debug, Clone)]
pub struct AxiomCdu {
    pub id: HlcId,
    pub content: String,
    pub challenge_link: Option<HlcId>,
    pub clock: HybridLogicalClock,
}

#[derive(Debug, Clone)]
pub struct KoCdu {
    pub id: HlcId,
    pub reason: String,
    pub failed_step_id: HlcId,
    pub related_axiom_id: Option<HlcId>,
    pub clock: HybridLogicalClock,
}

#[derive(Debug, Clone)]
pub struct OkCdu {
    pub id: HlcId,
    pub result_data: String,
    pub successful_step_id: HlcId,
    pub clock: HybridLogicalClock,
}

#[derive(Debug, Clone)]
pub struct PathCdu {
    pub id: HlcId,
    pub task_id: HlcId,
    pub branch_summary: String,
    pub ok_links: Vec<HlcId>,
    pub ko_links: Vec<HlcId>,
    pub similarity_vector: Vec<f32>,
    pub clock: HybridLogicalClock,
}

#[derive(Debug, Clone)]
pub struct StepCdu {
    pub id: HlcId,
    pub action_description: String,
    pub parent_task_id: HlcId,
    pub outcome_link: Option<HlcId>,
    pub initial_confidence: f32,
    pub clock: HybridLogicalClock,
}

#[derive(Debug, Clone)]
pub struct TaskCdu {
    pub id: HlcId,
    pub topic: String,
    pub initial_description: String,
    pub similar_path_links: Vec<HlcId>,
    pub defining_ideals: Vec<HlcId>, // Jointure field
    pub clock: HybridLogicalClock,
}

// --- 3. Unified Data Model ---

#[derive(Debug, Clone)]
pub enum CausalDataUnit {
    Task(TaskCdu),
    Step(StepCdu),
    Path(PathCdu),
    Axiom(AxiomCdu),
    Ko(KoCdu),
    Ok(OkCdu),
}

// Helper trait for easy ID generation/retrieval
pub trait Identifiable {
    fn id(&self) -> HlcId;
    fn new_id() -> HlcId;
}

impl Identifiable for CausalDataUnit {
    fn id(&self) -> HlcId {
        match self {
            CausalDataUnit::Task(t) => t.id,
            CausalDataUnit::Step(s) => s.id,
            CausalDataUnit::Path(p) => p.id,
            CausalDataUnit::Axiom(a) => a.id,
            CausalDataUnit::Ko(k) => k.id,
            CausalDataUnit::Ok(o) => o.id,
        }
    }
    fn new_id() -> HlcId { HlcId::new() }
}
