// File under BaDaaS license and generated by the vibe coding engine GLM-4.6 from chat.z.ai
// File path: src/cdu.rs

//! The Causal Data Unit (CDU) module.
//!
//! This is the fundamental, atomic unit of memory for the Chronosa agent.

// Import the Hlc struct from our own hlc module using the 'crate' path.
use crate::hlc::Hlc;
// Import the necessary traits for hashing from the sha2 crate.
use sha2::{Digest, Sha256};

/// The mutable metadata associated with a Causal Data Unit.
/// This contains Chronosa's current interpretation and context of the immutable payload.
#[derive(Debug, Clone)]
pub struct CduMetadata {
    /// The Hybrid Logical Clock timestamp for when this CDU was created or last updated.
    pub hlc: Hlc,
    /// A list of CDU names that are the direct causes for this CDU's existence.
    pub causes: Vec<String>,
    /// User-defined tags for querying and classification.
    pub tags: Vec<String>,
}

/// A Causal Data Unit (CDU).
/// It combines an immutable fact (payload) with mutable, evolving context (metadata).
#[derive(Debug, Clone)]
pub struct Cdu {
    /// The unique, content-addressed name of the CDU.
    /// Format: "<payload_hash>.<subtype>.cdu"
    pub name: String,
    /// The immutable, verifiable data payload. This is the "fact" of what happened.
    /// Represented as a raw byte vector to be maximally generic.
    pub payload: Vec<u8>,
    /// The mutable metadata, representing Chronosa's understanding of the payload.
    pub metadata: CduMetadata,
}

/// Represents the structured content within a CDU payload.
/// This enum allows for type-safe handling of different kinds of information.
#[derive(Debug, Clone)]
pub enum CduPayload {
    /// A raw byte payload for maximum flexibility.
    Raw(Vec<u8>),
    /// A prime element in Chronosa's reasoning model.
    PrimeElement(PrimeElement),
}

/// Represents a prime element in Chronosa's reasoning model.
#[derive(Debug, Clone)]
pub struct PrimeElement {
    /// Unique identifier for the prime element
    pub id: String,
    /// World context this prime element belongs to
    pub world: String,
    /// Mathematical representation as a real number
    pub representation: f64,
    /// Conceptual description
    pub description: String,
    /// Proof of irreducibility
    pub irreducibility_proof: String,
}

impl PrimeElement {
    /// Create a new prime element
    pub fn new(
        id: String,
        world: String,
        representation: f64,
        description: String,
        irreducibility_proof: String,
    ) -> Self {
        Self {
            id,
            world,
            representation,
            description,
            irreducibility_proof,
        }
    }

    /// Convert to CDU
    pub fn to_cdu(&self) -> Cdu {
        // Convert the PrimeElement to bytes for the payload
        let payload_bytes = self.to_bytes();
        let subtype = format!("prime.element.{}", self.world);
        Cdu::new(payload_bytes, &subtype, vec![])
    }

    /// Convert the PrimeElement to a byte representation for storage
    fn to_bytes(&self) -> Vec<u8> {
        // Simple serialization without external dependencies
        let mut bytes = Vec::new();

        // Serialize id
        bytes.extend_from_slice(&(self.id.len() as u32).to_le_bytes());
        bytes.extend_from_slice(self.id.as_bytes());

        // Serialize world
        bytes.extend_from_slice(&(self.world.len() as u32).to_le_bytes());
        bytes.extend_from_slice(self.world.as_bytes());

        // Serialize representation
        bytes.extend_from_slice(&self.representation.to_le_bytes());

        // Serialize description
        bytes.extend_from_slice(&(self.description.len() as u32).to_le_bytes());
        bytes.extend_from_slice(self.description.as_bytes());

        // Serialize irreducibility_proof
        bytes.extend_from_slice(&(self.irreducibility_proof.len() as u32).to_le_bytes());
        bytes.extend_from_slice(self.irreducibility_proof.as_bytes());

        bytes
    }

    /// Create a PrimeElement from a byte representation
    fn from_bytes(bytes: &[u8]) -> Option<Self> {
        let mut pos = 0;

        // Deserialize id
        if pos + 4 > bytes.len() {
            return None;
        }
        let id_len =
            u32::from_le_bytes([bytes[pos], bytes[pos + 1], bytes[pos + 2], bytes[pos + 3]])
                as usize;
        pos += 4;
        if pos + id_len > bytes.len() {
            return None;
        }
        let id = String::from_utf8(bytes[pos..pos + id_len].to_vec()).ok()?;
        pos += id_len;

        // Deserialize world
        if pos + 4 > bytes.len() {
            return None;
        }
        let world_len =
            u32::from_le_bytes([bytes[pos], bytes[pos + 1], bytes[pos + 2], bytes[pos + 3]])
                as usize;
        pos += 4;
        if pos + world_len > bytes.len() {
            return None;
        }
        let world = String::from_utf8(bytes[pos..pos + world_len].to_vec()).ok()?;
        pos += world_len;

        // Deserialize representation
        if pos + 8 > bytes.len() {
            return None;
        }
        let representation = f64::from_le_bytes([
            bytes[pos],
            bytes[pos + 1],
            bytes[pos + 2],
            bytes[pos + 3],
            bytes[pos + 4],
            bytes[pos + 5],
            bytes[pos + 6],
            bytes[pos + 7],
        ]);
        pos += 8;

        // Deserialize description
        if pos + 4 > bytes.len() {
            return None;
        }
        let desc_len =
            u32::from_le_bytes([bytes[pos], bytes[pos + 1], bytes[pos + 2], bytes[pos + 3]])
                as usize;
        pos += 4;
        if pos + desc_len > bytes.len() {
            return None;
        }
        let description = String::from_utf8(bytes[pos..pos + desc_len].to_vec()).ok()?;
        pos += desc_len;

        // Deserialize irreducibility_proof
        if pos + 4 > bytes.len() {
            return None;
        }
        let proof_len =
            u32::from_le_bytes([bytes[pos], bytes[pos + 1], bytes[pos + 2], bytes[pos + 3]])
                as usize;
        pos += 4;
        if pos + proof_len > bytes.len() {
            return None;
        }
        let irreducibility_proof = String::from_utf8(bytes[pos..pos + proof_len].to_vec()).ok()?;

        Some(PrimeElement {
            id,
            world,
            representation,
            description,
            irreducibility_proof,
        })
    }
}

impl Cdu {
    /// Creates a new Causal Data Unit.
    ///
    /// The CDU's name is deterministically generated from the SHA-256 hash of its payload,
    /// and its metadata is timestamped with a new Hybrid Logical Clock value.
    pub fn new(payload: Vec<u8>, subtype: &str, causes: Vec<String>) -> Self {
        // 1. Create a new SHA-256 hasher.
        let mut hasher = Sha256::new();
        // 2. Write the payload data into the hasher.
        hasher.update(&payload);
        // 3. Finalize the hash and get the result as a byte array.
        let hash_result = hasher.finalize();
        // 4. Format the hash as a hexadecimal string.
        let payload_hash = format!("{:x}", hash_result);

        // 5. Construct the full CDU name.
        let name = format!("{}.{}.cdu", payload_hash, subtype);

        // 6. Create the metadata, now with a real HLC timestamp.
        let metadata = CduMetadata {
            hlc: Hlc::new(), // <-- This now calls our functional HLC constructor.
            causes,
            tags: vec![],
        };

        // 7. Return the newly constructed CDU.
        Self {
            name,
            payload,
            metadata,
        }
    }

    /// Creates a new CDU from a CduPayload
    pub fn from_payload(payload: CduPayload, subtype: &str, causes: Vec<String>) -> Self {
        let payload_bytes = match payload {
            CduPayload::Raw(bytes) => bytes,
            CduPayload::PrimeElement(element) => element.to_bytes(),
        };
        Self::new(payload_bytes, subtype, causes)
    }

    /// Extracts the structured content from the CDU payload
    pub fn extract_payload(&self) -> Option<CduPayload> {
        // Try to determine the payload type from the CDU name
        if self.name.contains("prime.element.") {
            PrimeElement::from_bytes(&self.payload).map(CduPayload::PrimeElement)
        } else {
            Some(CduPayload::Raw(self.payload.clone()))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*; // Import everything from the parent module (cdu)

    #[test]
    fn test_cdu_creation_and_naming() {
        // 1. Define a sample payload and subtype.
        let payload = b"Test payload data".to_vec();
        let subtype = "test_event";

        // 2. Create the CDU.
        let cdu = Cdu::new(payload.clone(), subtype, vec![]);

        // 3. Verify the name construction.
        assert!(cdu.name.contains(subtype));
        assert!(cdu.name.ends_with(".cdu"));
        assert_ne!(
            cdu.name,
            format!(".{}.cdu", subtype),
            "Hash part of the name should not be empty."
        );

        // 4. Verify the payload was stored correctly.
        assert_eq!(cdu.payload, payload);

        // 5. Verify that the HLC timestamp is no longer a placeholder.
        assert_ne!(
            cdu.metadata.hlc.timestamp, 0,
            "HLC timestamp should be initialized."
        );
    }

    #[test]
    fn test_cdu_causal_link() {
        // 1. Create a "cause" CDU.
        let cause_cdu = Cdu::new(b"First event".to_vec(), "genesis", vec![]);

        // 2. Create a second CDU that is caused by the first.
        let effect_cdu = Cdu::new(
            b"Second event".to_vec(),
            "response",
            vec![cause_cdu.name.clone()],
        );

        // 3. Verify that the causal link was stored correctly.
        assert_eq!(effect_cdu.metadata.causes.len(), 1);
        assert_eq!(effect_cdu.metadata.causes[0], cause_cdu.name);

        // 4. Verify that the effect's timestamp is greater than or equal to the cause's.
        assert!(effect_cdu.metadata.hlc >= cause_cdu.metadata.hlc);
    }

    #[test]
    fn test_prime_element_serialization() {
        let element = PrimeElement::new(
            "test_element".to_string(),
            "test_world".to_string(),
            42.0,
            "A test element".to_string(),
            "Cannot be decomposed".to_string(),
        );

        let bytes = element.to_bytes();
        let deserialized_element = PrimeElement::from_bytes(&bytes).unwrap();

        assert_eq!(element.id, deserialized_element.id);
        assert_eq!(element.world, deserialized_element.world);
        assert_eq!(element.representation, deserialized_element.representation);
        assert_eq!(element.description, deserialized_element.description);
        assert_eq!(
            element.irreducibility_proof,
            deserialized_element.irreducibility_proof
        );
    }

    #[test]
    fn test_prime_element_cdu() {
        let element = PrimeElement::new(
            "test_element".to_string(),
            "test_world".to_string(),
            42.0,
            "A test element".to_string(),
            "Cannot be decomposed".to_string(),
        );

        let cdu = element.to_cdu();
        assert!(cdu.name.contains("prime.element.test_world"));
        assert!(cdu.name.ends_with(".cdu"));

        let extracted_payload = cdu.extract_payload();
        match extracted_payload {
            Some(CduPayload::PrimeElement(extracted_element)) => {
                assert_eq!(element.id, extracted_element.id);
                assert_eq!(element.world, extracted_element.world);
            }
            _ => panic!("Expected PrimeElement payload"),
        }
    }
}
