// File under BaDaaS license and generated by the vibe coding engine GLM-4.6 from chat.z.ai
// File path: src/engine.rs

//! The CDQN Native Execution Engine.

use crate::cdu::Cdu;
use crate::state::{evolve, ChronosaState};
use crate::storage::{append_events_to_log, rehydrate_from_log};
use std::path::PathBuf;
use std::sync::mpsc;
use std::thread;

/// The Projector is the pure, deterministic "brain" of the agent.
pub trait Projector: Send + Sync {
    fn project(&self, state: &ChronosaState, input: &Cdu) -> Vec<Cdu>;
}

/// The Engine drives the agent's lifecycle.
pub struct Engine {
    state: ChronosaState,
    log_path: PathBuf,
    projector: Box<dyn Projector>,
    // The channel to receive all incoming CDUs.
    input_receiver: mpsc::Receiver<Cdu>,
    // A sender for the input channel, can be cloned and given to Executors.
    pub input_sender: mpsc::Sender<Cdu>,
    // A channel to broadcast command CDUs to Executors.
    pub command_sender: mpsc::Sender<Cdu>,
}

impl Engine {
    pub fn new(log_path: PathBuf, projector: Box<dyn Projector>) -> (Self, mpsc::Receiver<Cdu>) {
        let events = rehydrate_from_log(&log_path).unwrap_or_default();
        let initial_state = events.into_iter().fold(ChronosaState::default(), evolve);

        let (input_sender, input_receiver) = mpsc::channel();
        let (command_sender, command_receiver) = mpsc::channel();

        let engine = Self {
            state: initial_state,
            log_path,
            projector,
            input_receiver,
            input_sender,
            command_sender,
        };

        (engine, command_receiver)
    }

    /// The main run loop. It listens for inputs and drives the state forward.
    pub fn run(mut self) {
        println!("Engine: Running.");
        while let Ok(input_cdu) = self.input_receiver.recv() {
            // 1. Clone necessary data for the new thread.
            let state_snapshot = self.state.clone();
            let projector = self.projector.clone_box(); // We'll add this method to the trait.
            let command_sender = self.command_sender.clone();
            let log_path = self.log_path.clone();

            // 2. Spawn a new thread for the reasoning task.
            thread::spawn(move || {
                // 3. Project the input against the state snapshot to get new events.
                let new_events = projector.project(&state_snapshot, &input_cdu);

                // 4. Persist the input and all new events to the WAL.
                let mut all_events_to_persist = vec![input_cdu];
                all_events_to_persist.extend(new_events);
                append_events_to_log(&all_events_to_persist, &log_path).unwrap();

                // 5. Send commands to the executor.
                for event in &all_events_to_persist {
                    if event.name.contains(".command.") {
                        command_sender.send(event.clone()).unwrap();
                    }
                }
            });
        }
        println!("Engine: Shutting down.");
    }
}

/// Helper trait to allow cloning of a `Box<dyn Projector>`.
pub trait ProjectorClone {
    fn clone_box(&self) -> Box<dyn Projector>;
}

impl<T> ProjectorClone for T
where
    T: 'static + Projector + Clone,
{
    fn clone_box(&self) -> Box<dyn Projector> {
        Box::new(self.clone())
    }
}

impl Clone for Box<dyn Projector> {
    fn clone(&self) -> Box<dyn Projector> {
        self.clone_box()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::ChronosaState;
    use std::fs;
    use std::sync::Arc;
    use std::time::Duration;

    // A mock projector for testing purposes.
    #[derive(Clone)]
    struct TestProjector;
    impl Projector for TestProjector {
        fn project(&self, _state: &ChronosaState, input: &Cdu) -> Vec<Cdu> {
            // Simulate some work
            thread::sleep(Duration::from_millis(10));
            if input.name.contains(".observation.") {
                vec![Cdu::new(
                    b"test command".to_vec(),
                    "command.test",
                    vec![input.name.clone()],
                )]
            } else {
                vec![]
            }
        }
    }

    #[test]
    fn test_concurrent_engine_processing_flow() {
        let temp_log_path = PathBuf::from("concurrent_engine_test.cdqn");
        let _ = fs::remove_file(&temp_log_path);

        // 1. Create the engine and get the command receiver.
        let (mut engine, command_receiver) =
            Engine::new(temp_log_path.clone(), Box::new(TestProjector));
        let input_sender = engine.input_sender.clone();

        // 2. Send multiple inputs rapidly.
        for i in 0..5 {
            let observation = Cdu::new(
                format!("test observation {}", i).into_bytes(),
                "observation",
                vec![],
            );
            input_sender.send(observation).unwrap();
        }

        // 3. Wait for all commands to be processed.
        thread::sleep(Duration::from_millis(100));
        let mut commands = Vec::new();
        while let Ok(command) = command_receiver.try_recv() {
            commands.push(command);
        }

        // 4. Verify that all commands were received.
        assert_eq!(commands.len(), 5);

        // 5. Clean up.
        let _ = fs::remove_file(&temp_log_path);
    }
}
