// This file is under license BaDaaS, generated by the vibe coding engine Gemini Flash-Lite Latest from Google.
// src/id.rs

use std::time::{SystemTime, UNIX_EPOCH};
use std::hash::{Hash, Hasher};
use rand::Rng;

/// A unique identifier based on the Hybrid Logical Clock concept.
/// Internally, it's a u128 composed of a time component and a random/sequence component.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HlcId(u128);

impl HlcId {
    /// Generates a new HlcId using the system time and a random component.
    pub fn new() -> Self {
        // Time Component: System time since UNIX_EPOCH in milliseconds.
        let time_since_epoch = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        // Entropy/Sequence Component: Generate a random 64-bit number.
        let entropy: u64 = rand::thread_rng().gen();

        // Combine: Shift time to upper 64 bits and OR with entropy.
        let id_value = (time_since_epoch as u128) << 64 | (entropy as u128);
        
        HlcId(id_value)
    }
    
    pub fn from_u128(value: u128) -> Self { HlcId(value) }
    pub fn as_u128(&self) -> u128 { self.0 }
}

// Implement Hash so HlcId can be used as a key in HashMap
impl Hash for HlcId {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

// Implement Default for convenience (zero value)
impl Default for HlcId {
    fn default() -> Self { HlcId(0) }
}
