// This file is under license BaDaaS, generated by the vibe coding engine Gemini Flash-Lite Latest from Google.
// src/lib.rs

// --- Module Declarations ---
pub mod id;
pub mod cdu;
pub mod reasoning;
pub mod algebraic;
pub mod agent;

// --- Public Re-exports ---
pub use id::HlcId;
pub use cdu::{CausalDataUnit, HybridLogicalClock, Identifiable};
pub use reasoning::result::{ReasoningResult, ReasoningPath, CombinationTreeSummary};
pub use reasoning::query::CausalQuery;
pub use algebraic::projections::{PrimeElement, AxisScoring, PrimeIdeal, ProjectionSpace};
pub use algebraic::context::AlgebraicContext;
pub use agent::ChronosAgent;
