// This file is under license BaDaaS, generated by the vibe coding engine Gemini Flash-Lite Latest from Google.
// src/main.rs
 
// Import everything needed from the library crate 'cdqn'
use cdqn::{
    HlcId, CausalDataUnit, ChronosAgent, AxiomCdu, HybridLogicalClock, 
    CausalQuery, ReasoningResult, ReasoningPath
};

fn main() {
    println!("--- CDQN Validation Test: Pure Axiomatic Matcher ---");

    // 1. Setup: Instantiate the Agent and its Memory
    let mut agent = ChronosAgent::new();
    
    // 2. Setup: Create a sample Axiom.CDU
    let axiom_content = "All tasks must start with a Task.CDU.";
    let axiom_id = HlcId::new();
    
    let sample_axiom = CausalDataUnit::Axiom(AxiomCdu {
        id: axiom_id,
        content: axiom_content.to_string(),
        challenge_link: None,
        clock: HybridLogicalClock::new(),
    });
    
    // Save the axiom to the agent's memory store
    agent.memory.memory.insert(axiom_id, sample_axiom);
    println!("Axiom saved to memory with ID: {:?}", axiom_id.as_u128());

    // 3. Test Setup: Create a Query that should match the axiom
    let query_task_id = HlcId::new();
    let matching_query = CausalQuery {
        task_id: query_task_id,
        question: format!("How should I begin? The rule is: {}", axiom_content),
    };
    
    // 4. Execution: Run the PURE function
    let matches = ChronosAgent::pure_find_all_axiom_matches(
        &agent.memory, 
        &matching_query
    );

    // 5. Assertion/Validation
    println!("\n--- Validation Results ---");
    
    if matches.len() == 1 {
        let result = &matches[0];
        println!("SUCCESS: Found exactly one match.");
        
        // Assertions based on design:
        assert_eq!(result.confidence, 0.99);
        assert_eq!(result.compute_cost, 10);
        assert_eq!(result.source_path, ReasoningPath::Cascading);
        
        if let CausalDataUnit::Axiom(axiom_data) = &result.solution_data {
            assert_eq!(axiom_data.content, axiom_content);
            println!("SUCCESS: Result data matches the original axiom content.");
        } else {
            panic!("FAILURE: Result data was not an Axiom.CDU.");
        }
        
        println!("Validation Passed: Confidence (0.99) and Compute Cost (10) match design.");
        
    } else {
        println!("FAILURE: Expected 1 match, found {} matches.", matches.len());
        panic!("Validation Failed: Axiomatic matcher did not return the expected single result.");
    }
}
