// src/main.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! The main entry point for the CDQN Node.
//!
//! This file initializes the sovereign CDQN Runtime (the Guardrail) and starts the Chronosa
//! cognitive engine.

use cdqn_runtime::CdqnRuntime;
use cdqn_cdu::Cdu;
use std::path::PathBuf;
use std::thread;
use std::time::Duration;

// NOTE: This is the main entry point for the entire CDQN Node.
fn main() {
    // 1. Setup the Manifold Storage Path
    // Use a temporary directory for testing, or a persistent path for production.
    let storage_path = PathBuf::from("./data/manifold");
    
    // 2. Initialize the CDQN Runtime (The Guardrail)
    let runtime = CdqnRuntime::new(storage_path);

    // 3. Start the Runtime (Spawns Agent Threads)
    let runtime_handle = thread::spawn(move || {
        runtime.run_forever();
    });

    // --- Simulation: Injecting a CDU into the Dispatcher ---
    // This simulates an external event (e.g., a user command or a network message).
    
    // NOTE: We must wait briefly for the VerifierAgent thread to start its polling loop.
    thread::sleep(Duration::from_millis(100));
    
    println!("\n--- SIMULATION: Injecting Test CDU ---");
    
    // Create a simple, valid CDU (Axiom)
    let valid_cdu = create_test_cdu("Valid Axiom", 2.5);
    
    // Inject the CDU into the Dispatcher
    match runtime.dispatcher.publish(valid_cdu) {
        Ok(_) => println!("SIMULATION: Successfully published Valid CDU."),
        Err(e) => eprintln!("SIMULATION ERROR: Failed to publish CDU: {}", e),
    }

    // Create a contradictory CDU (Impossibility Zone)
    let contradictory_cdu = create_test_cdu("Contradictory Fact", 0.5);
    
    // Inject the contradictory CDU
    match runtime.dispatcher.publish(contradictory_cdu) {
        Ok(_) => println!("SIMULATION: Successfully published Contradictory CDU."),
        Err(e) => eprintln!("SIMULATION ERROR: Failed to publish CDU: {}", e),
    }

    // Give the Verifier Agent time to process the messages
    thread::sleep(Duration::from_millis(100));
    
    // --- End Simulation ---
    
    // The runtime will continue to run until manually stopped (Ctrl+C) or until all threads panic.
    runtime_handle.join().expect("CDQN Runtime thread panicked.");
}

// Helper function to create a test CDU for the simulation
fn create_test_cdu(statement: &str, r_coordinate: f64) -> Cdu {
    use cdqn_hlc::HybridLogicalClock;
    use cdqn_cryptocore::hash_sha3_256;
    use cdqn_cdu::payloads::AxiomPayload;
    use cdqn_cdu::World;
    
    let hlc = HybridLogicalClock::new();
    let node_id = hash_sha3_256(b"sim_node").to_vec();
    
    let axiom_payload = AxiomPayload {
        statement: statement.to_string(),
    };
    let payload = axiom_payload.into_payload();

    let metadata = cdqn_cdu::Metadata {
        author_node: node_id.clone(),
        context_refs: vec![],
        state: "draft".to_string(),
        weight: 1.0,
        r_coordinate,
        world_context: World::UserWorld,
        hlc_timestamp: hlc.new_timestamp(),
        symmetric_counterpart: None,
        validated_worlds: std::collections::HashSet::new(),
    };

    // NOTE: We skip the full signing process for simplicity in main.rs
    let cdu = Cdu::new(payload, metadata, &hlc, &node_id);
    cdu
}
