// File under BaDaaS license and generated by the vibe coding engine GLM-4.6 from chat.z.ai
// File path: src/projector.rs

//! Defines projectors, the deterministic "brains" of the agent.

use crate::cdu::Cdu;
use crate::engine::Projector;
use crate::state::ChronosaState;

// --- FIX: Define type aliases for complex function traits ---
// Added `Sync` to make them thread-safe for sharing.
pub type Predicate = Box<dyn Fn(&ChronosaState, &Cdu) -> bool + Send + Sync>;
pub type Mapper = Box<dyn Fn(&Cdu) -> Vec<Cdu> + Send + Sync>;

/// A single, stateless rule for the projector to evaluate.
#[derive(Clone)]
pub struct Rule {
    /// The predicate: a function that checks if the rule should fire.
    pub predicate: Predicate,
    /// The mapper: a function that creates the resulting command CDUs if the predicate is true.
    pub mapper: Mapper,
}

// Manual implementation of Clone for Rule.
// Since functions are just pointers, we can create new Boxes pointing to the same function.
impl Clone for Rule {
    fn clone(&self) -> Self {
        Self {
            predicate: Box::new((&*self.predicate)),
            mapper: Box::new((&*self.mapper)),
        }
    }
}

/// A projector that uses a list of rules to make decisions.
#[derive(Clone)]
pub struct RuleBasedProjector {
    rules: Vec<Rule>,
}

impl RuleBasedProjector {
    pub fn new(rules: Vec<Rule>) -> Self {
        Self { rules }
    }
}

impl Projector for RuleBasedProjector {
    /// Iterates through its rules and executes the first one whose predicate matches.
    fn project(&self, state: &ChronosaState, input: &Cdu) -> Vec<Cdu> {
        for rule in &self.rules {
            if (rule.predicate)(state, input) {
                return (rule.mapper)(input);
            }
        }
        // If no rules match, produce no new events.
        vec![]
    }
}
