// File under BaDaaS license and generated by the vibe coding engine GLM-4.6 from chat.z.ai
// File path: src/state.rs

//! Defines the in-memory state of Chronosa and the pure function to evolve it.

use crate::cdu::Cdu;
use crate::hlc::Hlc;
use std::sync::{Arc, RwLock};

/// The in-memory state of a Chronosa instance.
/// This is a pure projection of the event log.
/// This struct is now immutable and can be safely shared.
#[derive(Debug, Clone, Default)]
pub struct ChronosaState {
    pub(crate) hlc: Hlc,
    pub(crate) log: Vec<Cdu>,
}

/// A thread-safe, shared handle to the ChronosaState.
pub type SharedState = Arc<RwLock<ChronosaState>>;

impl ChronosaState {
    /// Returns a slice providing read-only access to the entire CDU log.
    pub fn log(&self) -> &[Cdu] {
        &self.log
    }

    /// Returns the number of CDUs currently in the log.
    pub fn len(&self) -> usize {
        self.log.len()
    }

    /// Returns `true` if the log contains no CDUs.
    pub fn is_empty(&self) -> bool {
        self.log.is_empty()
    }

    /// Finds the most recent CDU in the log that matches a given subtype.
    pub fn find_last_by_subtype(&self, subtype: &str) -> Option<&Cdu> {
        let pattern = format!(".{}.cdu", subtype);
        self.log
            .iter()
            .rev()
            .find(|cdu| cdu.name.contains(&pattern))
    }
}

/// The "Evolver" or "Reducer" function.
/// This function now takes a write lock to mutate the shared state.
pub fn evolve_shared_state(state: &SharedState, event: Cdu) {
    if let Ok(mut state_guard) = state.write() {
        // Ensure the state's clock is always up-to-date.
        if event.metadata.hlc > state_guard.hlc {
            state_guard.hlc = event.metadata.hlc.clone();
        }
        state_guard.log.push(event);
    } else {
        // This would happen if another thread panicked while holding the lock.
        // In a real system, we might want more robust error handling here.
        eprintln!("Failed to acquire write lock to evolve state.");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cdu::Cdu;

    #[test]
    fn test_shared_state_evolution() {
        let initial_state = ChronosaState::default();
        let shared_state = Arc::new(RwLock::new(initial_state));
        assert!(shared_state.read().unwrap().is_empty());

        let event1 = Cdu::new(b"event 1".to_vec(), "type1", vec![]);
        evolve_shared_state(&shared_state, event1);

        assert_eq!(shared_state.read().unwrap().len(), 1);
        assert_eq!(
            shared_state.read().unwrap().log()[0].payload,
            b"event 1".to_vec()
        );

        let event2 = Cdu::new(b"event 2".to_vec(), "type2", vec![]);
        evolve_shared_state(&shared_state, event2);
        assert_eq!(shared_state.read().unwrap().len(), 2);
    }
}
