// cdqn/crates/common/src/lib.rs
// File under the BaDaaS license, code generated by ai assistant: Gemini 2.5 Pro, Google

// --- THE CRITICAL FIX ---
// The `#![no_std]` and `extern crate alloc` attributes have been removed.
// While well-intentioned for minimalism, they created a conflict with the standard
// library features required by downstream crates. Building this crate against the
// standard library (`std`) ensures compatibility without adding any dependencies.
use std::vec::Vec;

/// A simple, lightweight error type for our custom serialization.
#[derive(Debug)]
pub enum Error {
    /// Represents a failure during the serialization process.
    SerializationFailed,
}

/// A specialized Result type for serialization operations.
pub type Result<T> = core::result::Result<T, Error>;

/// A trait for converting a data structure into a stable, canonical byte representation.
///
/// This is the cornerstone of our dependency-free strategy. Any object that needs to be
/// hashed or signed MUST implement this trait. The implementation MUST be deterministic:
/// the same object must always produce the exact same byte vector.
pub trait ToCanonicalBytes {
    /// Converts the object into its canonical byte form.
    ///
    /// # Returns
    /// A `Result` containing the byte vector on success, or an `Error` on failure.
    fn to_canonical_bytes(&self) -> Result<Vec<u8>>;
}
