// This file is under license BaDaaS, generated by the vibe coding engine Gemini Flash-Lite Latest from Google.
// src/data_model/id.rs

use std::time::{SystemTime, UNIX_EPOCH};
use std::hash::{Hash, Hasher};
use rand::Rng; // We need the rand crate for the entropy part

/// A unique identifier based on the Hybrid Logical Clock concept.
/// Internally, it's a u128 composed of a time component and a random/sequence component.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HlcId(u128);

impl HlcId {
    /// Generates a new HlcId using the system time and a random component.
    /// This is the primary constructor for new entities.
    pub fn new() -> Self {
        // 1. Time Component: Get the system time since the UNIX epoch in milliseconds.
        let time_since_epoch = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        // 2. Entropy/Sequence Component: Generate a random 64-bit number.
        let entropy: u64 = rand::thread_rng().gen();

        // 3. Combine: Shift the time component to the upper 64 bits and OR with entropy.
        // This ensures IDs generated close in time are close numerically, and randomness
        // prevents collisions if multiple IDs are generated in the same millisecond.
        let id_value = (time_since_epoch as u128) << 64 | (entropy as u128);
        
        HlcId(id_value)
    }
    
    /// Creates an HlcId from a known u128 value (useful for loading from memory).
    pub fn from_u128(value: u128) -> Self {
        HlcId(value)
    }
    
    /// Converts the ID to its raw u128 representation.
    pub fn as_u128(&self) -> u128 {
        self.0
    }
}

// --- Trait Implementations for Usability ---

// Implement Hash so HlcId can be used as a key in HashMap
impl Hash for HlcId {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

// Implement Default so we can easily create a default/empty ID if needed
impl Default for HlcId {
    fn default() -> Self {
        // A default ID is often the zero value, which should be avoided for actual entities.
        HlcId(0) 
    }
}
