// crates/cdu/src/payloads/axiom.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use crate::types::Payload;
use serde::{Deserialize, Serialize};

/// Payload for a Semi-Axiom CDU, representing a foundational rule.
/// The origin world is now handled in the Metadata to avoid ownership issues
/// and to better separate data from its contextual metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AxiomPayload {
    /// The statement of the axiom.
    pub statement: String,
}

impl AxiomPayload {
    /// Converts the `AxiomPayload` into a generic `Payload` with an "axiom/v1" type.
    #[must_use]
    pub fn into_payload(self) -> Payload {
        let json = serde_json::to_string(&self).expect("AxiomPayload should be serializable");
        Payload {
            data: json.into_bytes(),
            payload_type: "axiom/v1".to_string(),
        }
    }
}
