// crates/cdu/src/payloads/axiom.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use crate::types::Payload;
use crate::worlds::World;
use serde::{Deserialize, Serialize};

/// Payload for a Semi-Axiom CDU, representing a foundational rule within a specific World.
/// It becomes a full Axiom once validated in the UserWorld and at least two other worlds.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AxiomPayload {
    /// The statement of the semi-axiom.
    pub statement: String,
    /// The world where this semi-axiom originates.
    pub origin_world: World,
}

impl AxiomPayload {
    /// Converts the `AxiomPayload` into a generic `Payload` with an "axiom/v1" type.
    #[must_use]
    pub fn into_payload(self) -> Payload {
        let json = serde_json::to_string(&self).expect("AxiomPayload should be serializable");
        Payload {
            data: json.into_bytes(),
            payload_type: "axiom/v1".to_string(),
        }
    }
}
