// crates/cdu/src/payloads/bot_state.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

use crate::types::Payload;
use serde::{Deserialize, Serialize};

/// Payload for a BotState CDU, representing the deterministic, persistent state
/// of a long-running workflow (Temporal-inspired).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BotStatePayload {
    /// The unique ID of the Bot/Task that created this state record.
    pub causal_task_id: String,
    /// The last step completed in the Bot's workflow (e.g., "VERIFIED_CAUSALITY").
    pub last_step_completed: String,
    /// A hash of the final result or a summary of the state at this step.
    pub state_hash: [u8; 32],
}

impl BotStatePayload {
    /// Converts the `BotStatePayload` into a generic `Payload` with a "bot-state/v1" type.
    #[must_use]
    pub fn into_payload(self) -> Payload {
        let json = serde_json::to_string(&self).expect("BotStatePayload should be serializable");
        Payload {
            data: json.into_bytes(),
            payload_type: "bot-state/v1".to_string(),
        }
    }
}
