// crates/cdu/src/payloads/config.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use crate::types::Payload;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Payload for a configuration CDU, holding arbitrary key-value settings.
/// This allows for flexible, user-defined or node-specific configurations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfigPayload {
    /// A map of configuration keys to their JSON values.
    pub settings: HashMap<String, serde_json::Value>,
}

impl ConfigPayload {
    /// Converts the `ConfigPayload` into a generic `Payload` with a "config/v1" type.
    #[must_use]
    pub fn into_payload(self) -> Payload {
        let json = serde_json::to_string(&self).expect("ConfigPayload should be serializable");
        Payload {
            data: json.into_bytes(),
            payload_type: "config/v1".to_string(),
        }
    }
}
