// crates/cdu/src/payloads/genesis.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use crate::types::Payload;
use serde::{Deserialize, Serialize};

/// Special payload type for the Genesis CDU, containing a node's identity.
/// Using `serde` ensures robust serialization without manual string formatting errors.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenesisPayload {
    /// A unique fingerprint of the node's hardware.
    pub hardware_fingerprint: [u8; 32],
    /// The operating system identifier.
    pub os: String,
    /// The creation timestamp.
    pub timestamp: u64,
    /// The physical location of the node.
    pub location: String,
}

impl GenesisPayload {
    /// Converts the `GenesisPayload` into a generic `Payload` with a "genesis/v1" type.
    /// This method is now safer and more maintainable using `serde_json`.
    #[must_use]
    pub fn into_payload(self) -> Payload {
        let json = serde_json::to_string(&self).expect("GenesisPayload should be serializable");
        Payload {
            data: json.into_bytes(),
            payload_type: "genesis/v1".to_string(),
        }
    }
}
