// crates/cdu/src/payloads/impossibility_deferral.rs
// File under the BaDaaS license, code generated by the ai model: Claude 3.5 Sonnet, Anthropic

use crate::types::Payload;
use crate::worlds::World;
use serde::{Deserialize, Serialize};

/// Payload for deferring an unresolvable impossibility to the waiting zone.
/// The CDU will be re-checked when new axioms/semi-axioms appear in its world.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImpossibilityDeferralPayload {
    /// The CDU that contains the unresolvable contradiction
    pub source_cdu_id: Vec<u8>,
    
    /// The specific contradiction or error encountered
    pub contradiction_description: String,
    
    /// The world where we're waiting for new axioms
    pub waiting_in_world: World,
    
    /// What kind of axioms might help resolve this
    pub needed_axiom_hint: String,
    
    /// Number of resolution attempts so far
    pub attempt_count: u32,
    
    /// HLC timestamp of when to retry (exponential backoff)
    pub retry_after_timestamp: u64,
}

impl ImpossibilityDeferralPayload {
    /// Converts the payload into a generic `Payload` with "impossibility-deferral/v1" type.
    #[must_use]
    pub fn into_payload(self) -> Payload {
        let json = serde_json::to_string(&self).expect("ImpossibilityDeferralPayload should be serializable");
        Payload {
            data: json.into_bytes(),
            payload_type: "impossibility-deferral/v1".to_string(),
        }
    }
}
