// crates/cdu/src/payloads/mod.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

// Declare the payload submodules.
pub mod genesis;
pub mod config;
pub mod axiom;

// Re-export the payload types for convenience.
pub use genesis::GenesisPayload;
pub use config::ConfigPayload;
pub use axiom::AxiomPayload;
