// crates/cdu/src/payloads/mod.rs
// File under the BaDaaS license, code generated by the ai model: ppl-sonar-pro-high, Perplexity

// Declare the payload submodules that exist
pub mod genesis;
pub mod config;
pub mod axiom;
pub mod bot_state;
pub mod theorem;
pub mod impossibility_deferral;

// Re-export the payload types for convenience
pub use genesis::GenesisPayload;
pub use config::ConfigPayload;
pub use axiom::AxiomPayload;
pub use bot_state::BotStatePayload;
pub use theorem::{TheoremPayload, ReasoningStep};
pub use impossibility_deferral::ImpossibilityDeferralPayload;
