// crates/cdu/src/payloads/mod.rs
// File under the BaDaaS license, code generated by the ai model: O3-search, OpenAi

// ---------- sub-modules ----------
pub mod genesis;
pub mod config;
pub mod axiom;
pub mod bot_state;
pub mod theorem;
pub mod btheorem;
pub mod trade_certificate;
pub mod action_refusal;
pub mod impossibility_deferral;          // <-- if you placed it under this name

// ---------- re-exports ----------
pub use genesis::GenesisPayload;
pub use config::ConfigPayload;
pub use axiom::AxiomPayload;
pub use bot_state::BotStatePayload;

pub use theorem::{TheoremPayload, ReasoningStep};
pub use btheorem::BTheoremPayload;
pub use trade_certificate::TradeCertificatePayload;
pub use action_refusal::ActionRefusalPayload;
pub use impossibility_deferral::ImpossibilityDeferralPayload; // <-- add this
