// crates/cdu/src/payloads/theorem.rs
// File under the BaDaaS license, code generated by the ai model: Claude-Opus-4-search, Anthropic

use crate::types::Payload;
use crate::worlds::World;
use serde::{Deserialize, Serialize};

/// Payload for a Theorem CDU, representing a reusable reasoning path.
/// A Theorem is a verified playbook from axioms/semi-axioms to a goal,
/// enabling faster reasoning in similar contexts (inspired by category theory).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TheoremPayload {
    /// The foundational axioms/semi-axioms this theorem builds upon
    pub foundation_axiom_ids: Vec<Vec<u8>>,
    
    /// The logical steps/transformations that lead from foundations to goal
    pub reasoning_path: Vec<ReasoningStep>,
    
    /// The goal or conclusion this theorem reaches
    pub goal_statement: String,
    
    /// The category/pattern this theorem applies to (for pattern matching)
    pub category_signature: String,
    
    /// The world(s) where this theorem is valid
    pub valid_in_worlds: Vec<World>,
    
    /// Confidence score based on how many times successfully applied
    pub reuse_count: u32,
    
    /// Average time saved when applying this theorem vs. first-principles reasoning
    pub efficiency_gain_ns: Option<u64>,
}

/// A single step in the theorem's reasoning path
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReasoningStep {
    /// Description of this logical transformation
    pub transformation: String,
    
    /// The rule or axiom applied at this step
    pub applied_rule_id: Option<Vec<u8>>,
    
    /// Input pattern for this step
    pub input_pattern: String,
    
    /// Output pattern after transformation
    pub output_pattern: String,
}

impl TheoremPayload {
    /// Converts the `TheoremPayload` into a generic `Payload` with a "theorem/v1" type.
    #[must_use]
    pub fn into_payload(self) -> Payload {
        let json = serde_json::to_string(&self).expect("TheoremPayload should be serializable");
        Payload {
            data: json.into_bytes(),
            payload_type: "theorem/v1".to_string(),
        }
    }

    /// Checks if this theorem matches a given context/category
    pub fn matches_category(&self, context_signature: &str) -> bool {
        // Simple string matching for now, could be more sophisticated
        self.category_signature == context_signature || 
        self.category_signature.contains(context_signature)
    }
}
