// crates/cdu/src/lib.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

//! Causal Data Unit (CDU): the unified, encrypted, verifiable atom of knowledge.
//!
//! This crate defines the core CDU structure and its various subtypes.
//! We use the `serde` crate for robust and verifiable serialization of payloads,
//! ensuring data integrity and maintainability as the system evolves.
//!
//! Performance-critical constructors are written to avoid unnecessary allocations,
//! as they may be called millions of times concurrently.

// Declare the submodules
mod types; // <-- FIX: Now a module containing core, constructors, integrity
mod payloads;
mod utils;
mod worlds;

// Move all tests into a separate module for better organization.
#[cfg(test)]
mod tests;

// Re-export the core public types so that users of this crate don't need to know our internal module structure.
pub use types::{Cdu, Metadata, Payload, Signature};
pub use payloads::{ConfigPayload, GenesisPayload, AxiomPayload};
pub use worlds::World;
