// crates/cdu/src/lib.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

// ... (rest of the file is the same) ...

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    /// This test validates the creation of a Genesis CDU, which is the root of trust
    /// for a CDQN node. It ensures that a unique ID and NodeId can be generated
    /// based on environmental factors.
    ///
    /// NOTE: We use `eprintln!` instead of `println!` to ensure the output is
    /// immediately visible in CI logs, as `stdout` is buffered when redirected.
    #[test]
    fn genesis_cdu_smoke() {
        let os_name = std::env::consts::OS;
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let seed = format!("cdqn-genesis-{}-{}-{}", env!("CARGO_PKG_NAME"), os_name, timestamp);
        let hardware_fp = cdqn_cryptocore::hash_sha3_256(seed.as_bytes());
        let node_id = hardware_fp.to_vec();

        let genesis_payload = GenesisPayload {
            hardware_fingerprint: hardware_fp,
            os: os_name.to_string(),
            timestamp: (timestamp / 1_000_000_000) as u64,
            location: "CI Runner".to_string(),
        };

        let payload = genesis_payload.into_payload();
        let metadata = Metadata {
            author_node: node_id.clone(),
            context_refs: vec![],
            state: "active".to_string(),
            weight: 1.0,
            r_coordinate: 0.0,
            world_context: "NodeWorld".to_string(),
            hlc_timestamp: HlcTimestamp::new(0, 0),
        };

        let hlc = HybridLogicalClock::new();
        let genesis_cdu = Cdu::new(payload, metadata, &hlc, &node_id);

        eprintln!("OS: {}", os_name);
        eprintln!("NodeId (hex): {}", hex_encode(&node_id));
        eprintln!("PayloadHash (hex): {}", hex_encode(&genesis_cdu.payload_hash));
        eprintln!("GenesisCDU ID (hex): {}", hex_encode(&genesis_cdu.id_hlc));
        eprintln!("Status: SUCCESS");

        // Add a final assertion to guarantee the test ran to completion.
        assert!(!genesis_cdu.id_hlc.is_empty(), "Genesis CDU ID should not be empty");
    }

    /// This test validates the creation and interpretation of a ConfigCDU.
    /// It ensures that configuration data can be stored within a CDU and
    /// correctly retrieved later.
    #[test]
    fn config_cdu_creation_and_interpretation() {
        let hlc = HybridLogicalClock::new();
        let node_id = vec![1, 2, 3, 4];

        // Define some configuration settings
        let mut settings = HashMap::new();
        settings.insert("log_level".to_string(), serde_json::Value::String("debug".to_string()));
        settings.insert("max_connections".to_string(), serde_json::Value::Number(serde_json::Number::from(100)));

        // Create the ConfigCDU using the convenience constructor
        let config_cdu = Cdu::new_config(settings.clone(), node_id.clone(), &hlc);

        // Verify the CDU's metadata
        assert_eq!(config_cdu.metadata.author_node, node_id);
        assert_eq!(config_cdu.payload.payload_type, "config/v1");

        // Use the helper method to interpret the CDU as a ConfigCDU
        let retrieved_payload = config_cdu.as_config().expect("Should be a valid ConfigCDU");

        // Verify that the retrieved settings match the original
        assert_eq!(retrieved_payload.settings.get("log_level").unwrap().as_str(), Some("debug"));
        assert_eq!(
            retrieved_payload.settings.get("max_connections").unwrap().as_u64(),
            Some(100)
        );
    }
}
