// crates/cdu/src/tests.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use crate::types::{Cdu, Metadata};
use crate::payloads::GenesisPayload;
use crate::utils::{hex_encode, verify_causal_chain};
use cdqn_hlc::{HlcTimestamp, HybridLogicalClock};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

/// Finds the absolute path to the workspace root by traversing up from the
/// current file's location until it finds the workspace `Cargo.toml`.
fn find_workspace_root() -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    
    // Traverse up from `crates/cdu` to the project root.
    while !path.join("Cargo.toml").exists() || path.join("crates").exists() {
        path = match path.parent() {
            Some(parent) => parent.to_path_buf(),
            None => panic!("Could not find workspace root. Please run from within the workspace."),
        };
    }
    path
}

/// This is an integrated test that simulates the full lifecycle of a node's
/// first two CDUs, ensuring their logical and causal integrity.
///
/// 1. It creates a sovereign Genesis CDU, the root of trust.
/// 2. It creates a child ConfigCDU, correctly linking it to the Genesis CDU.
/// 3. It verifies that the causal chain from the child traces back to the Genesis.
/// 4. It writes the unique identifiers from the Genesis CDU to a file for CI.
#[test]
fn test_node_lifecycle_and_causal_integrity() {
    // --- Setup ---
    let project_root = find_workspace_root();
    let log_dir = project_root.join("ci-logs");
    fs::create_dir_all(&log_dir).expect("Should be able to create ci-logs directory");

    let hlc = HybridLogicalClock::new();
    let os_name = std::env::consts::OS;
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let seed = format!("cdqn-genesis-{}-{}-{}", env!("CARGO_PKG_NAME"), os_name, timestamp);
    let hardware_fp = cdqn_cryptocore::hash_sha3_256(seed.as_bytes());
    let node_id = hardware_fp.to_vec();

    // --- Step 1: Create the Genesis CDU ---
    let genesis_payload = GenesisPayload {
        hardware_fingerprint: hardware_fp,
        os: os_name.to_string(),
        timestamp: (timestamp / 1_000_000_000) as u64,
        location: "CI Runner".to_string(),
    };
    let payload = genesis_payload.into_payload();
    let metadata = Metadata {
        author_node: node_id.clone(),
        context_refs: vec![], // Genesis has no parents.
        state: "active".to_string(),
        weight: 1.0,
        r_coordinate: 0.0,
        world_context: "NodeWorld".to_string(),
        hlc_timestamp: HlcTimestamp::new(0, 0),
    };
    let genesis_cdu = Cdu::new(payload, metadata, &hlc, &node_id);

    assert!(genesis_cdu.is_genesis(), "The first CDU created must be a Genesis CDU");

    // --- Step 2: Create a child ConfigCDU, linked to the Genesis ---
    let mut settings = HashMap::new();
    settings.insert("log_level".to_string(), serde_json::Value::String("info".to_string()));
    
    // The new CDU uses the same node_id and links to the Genesis CDU's ID.
    // We pass a reference to the Genesis ID, avoiding any clone.
    let config_cdu = Cdu::new_config(settings, node_id.clone(), &hlc, &genesis_cdu.id_hlc);
    
    assert!(!config_cdu.is_genesis(), "The second CDU must not be a Genesis CDU");
    
    // Assert that the child's first context reference is a reference to the Genesis ID.
    // This avoids creating a new Vec and moving the Genesis ID.
    assert_eq!(
        config_cdu.metadata.context_refs.first(),
        Some(&genesis_cdu.id_hlc)
    );

    // --- Step 3: Verify the causal chain ---
    let all_cdus = vec![&genesis_cdu, &config_cdu];
    let is_chain_valid = verify_causal_chain(&config_cdu, &all_cdus, &genesis_cdu.id_hlc);
    assert!(is_chain_valid, "The causal chain from the child to the Genesis CDU must be valid");

    // --- Step 4: Report the unique Genesis identifiers for CI verification ---
    let output = format!(
        "OS: {}\nNodeId (hex): {}\nPayloadHash (hex): {}\nGenesisCDU ID (hex): {}\nStatus: SUCCESS\n",
        os_name,
        hex_encode(&node_id),
        hex_encode(&genesis_cdu.payload_hash),
        hex_encode(&genesis_cdu.id_hlc)
    );

    let path = log_dir.join("genesis_report.txt");
    println!("TEST DEBUG: Writing genesis report to: {}", path.display());
    fs::write(&path, output).expect("Unable to write genesis report file");
}
