// crates/cdu/src/tests.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use crate::types::{Cdu, Metadata};
use crate::payloads::GenesisPayload;
use crate::utils::{hex_encode, verify_causal_chain};
use cdqn_hlc::{HlcTimestamp, HybridLogicalClock};
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

/// This test validates the creation of a Genesis CDU, which is the root of trust
/// for a CDQN node. It ensures that a unique ID and NodeId can be generated
/// based on environmental factors.
///
/// NOTE: We write output to a file using the project root to ensure it is
/// reliably found by the CI script, regardless of the test's working directory.
#[test]
fn genesis_cdu_smoke() {
    // Construct an absolute path to the ci-logs directory in the project root.
    // This ensures the test and the CI script agree on the file location.
    let project_root = env!("CARGO_MANIFEST_DIR");
    let log_dir = PathBuf::from(project_root).join("ci-logs");
    fs::create_dir_all(&log_dir).expect("Should be able to create ci-logs directory");

    let os_name = std::env::consts::OS;
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let seed = format!("cdqn-genesis-{}-{}-{}", env!("CARGO_PKG_NAME"), os_name, timestamp);
    let hardware_fp = cdqn_cryptocore::hash_sha3_256(seed.as_bytes());
    let node_id = hardware_fp.to_vec();

    let genesis_payload = GenesisPayload {
        hardware_fingerprint: hardware_fp,
        os: os_name.to_string(),
        timestamp: (timestamp / 1_000_000_000) as u64,
        location: "CI Runner".to_string(),
    };

    let payload = genesis_payload.into_payload();
    let metadata = Metadata {
        author_node: node_id.clone(),
        context_refs: vec![],
        state: "active".to_string(),
        weight: 1.0,
        r_coordinate: 0.0,
        world_context: "NodeWorld".to_string(),
        hlc_timestamp: HlcTimestamp::new(0, 0),
    };

    let hlc = HybridLogicalClock::new();
    let genesis_cdu = Cdu::new(payload, metadata, &hlc, &node_id);

    let output = format!(
        "OS: {}\nNodeId (hex): {}\nPayloadHash (hex): {}\nGenesisCDU ID (hex): {}\nStatus: SUCCESS\n",
        os_name,
        hex_encode(&node_id),
        hex_encode(&genesis_cdu.payload_hash),
        hex_encode(&genesis_cdu.id_hlc)
    );

    // Write the output to a file that the CI script can read.
    let path = log_dir.join("genesis_report.txt");
    fs::write(&path, output).expect("Unable to write genesis report file");

    assert!(!genesis_cdu.id_hlc.is_empty(), "Genesis CDU ID should not be empty");
}

/// This test validates the creation and interpretation of a ConfigCDU.
/// It ensures that configuration data can be stored within a CDU and
/// correctly retrieved later.
#[test]
fn config_cdu_creation_and_interpretation() {
    let hlc = HybridLogicalClock::new();
    let node_id = vec![1, 2, 3, 4];

    // Define some configuration settings
    let mut settings = HashMap::new();
    settings.insert("log_level".to_string(), serde_json::Value::String("debug".to_string()));
    settings.insert("max_connections".to_string(), serde_json::Value::Number(serde_json::Number::from(100)));

    // Create the ConfigCDU using the convenience constructor
    let config_cdu = Cdu::new_config(settings.clone(), node_id.clone(), &hlc, &[]);

    // Verify the CDU's metadata
    assert_eq!(config_cdu.metadata.author_node, node_id);
    assert_eq!(config_cdu.payload.payload_type, "config/v1");

    // Use the helper method to interpret the CDU as a ConfigCDU
    let retrieved_payload = config_cdu.as_config().expect("Should be a valid ConfigCDU");

    // Verify that the retrieved settings match the original
    assert_eq!(retrieved_payload.settings.get("log_level").unwrap().as_str(), Some("debug"));
    assert_eq!(
        retrieved_payload.settings.get("max_connections").unwrap().as_u64(),
        Some(100)
    );
}

/// This test validates the core principle of causal integrity.
/// It creates a Genesis CDU and then a child CDU, and verifies that the
/// child's causal chain can be traced back to the Genesis.
#[test]
fn test_causal_integrity_chain() {
    let hlc = HybridLogicalClock::new();
    let node_id = vec![9, 8, 7, 6];

    // 1. Create a Genesis CDU
    let genesis_payload = GenesisPayload {
        hardware_fingerprint: [0; 32],
        os: "test_os".to_string(),
        timestamp: 0,
        location: "test_location".to_string(),
    };
    let payload = genesis_payload.into_payload();
    let metadata = Metadata {
        author_node: node_id.clone(),
        context_refs: vec![],
        state: "active".to_string(),
        weight: 1.0,
        r_coordinate: 0.0,
        world_context: "NodeWorld".to_string(),
        hlc_timestamp: HlcTimestamp::new(0, 0),
    };
    let genesis_cdu = Cdu::new(payload, metadata, &hlc, &node_id);

    // 2. Create a child ConfigCDU, linking it to the Genesis
    let mut settings = HashMap::new();
    settings.insert("key".to_string(), serde_json::Value::String("value".to_string()));
    let child_cdu = Cdu::new_config(settings, node_id, &hlc, &genesis_cdu.id_hlc);

    // 3. Verify the chain
    let all_cdus = vec![&genesis_cdu, &child_cdu];
    let is_valid = verify_causal_chain(&child_cdu, &all_cdus, &genesis_cdu.id_hlc);

    assert!(is_valid, "The causal chain should be valid and traceable to the Genesis CDU");
}
