// crates/cdu/src/tests.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use crate::types::{Cdu, Metadata};
use crate::payloads::GenesisPayload;
use crate::utils::{hex_encode, verify_causal_chain};
use crate::worlds::World;
use cdqn_hlc::{HlcTimestamp, HybridLogicalClock};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

/// Finds the absolute path to the workspace root.
fn find_workspace_root() -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        if path.join("Cargo.toml").exists() && path.join("crates").exists() {
            return path;
        }
        path = match path.parent() {
            Some(parent) => parent.to_path_buf(),
            None => panic!("Could not find workspace root."),
        };
    }
}

/// Helper to print a summary of a CDU for debugging.
fn print_cdu_summary(name: &str, cdu: &Cdu) {
    eprintln!("--- {} ---", name);
    eprintln!("  Type: {}", cdu.payload.payload_type);
    eprintln!("  ID (hex): {}", hex_encode(&cdu.id_hlc));
    eprintln!("  World: {:?}", cdu.metadata.world_context);
    if !cdu.metadata.context_refs.is_empty() {
        eprintln!("  Parents (hex):");
        for parent_id in &cdu.metadata.context_refs {
            eprintln!("    - {}", hex_encode(parent_id));
        }
    } else {
        eprintln!("  Parents: None");
    }
    if let Some(axiom_payload) = cdu.as_axiom() {
        eprintln!("  Statement: {}", axiom_payload.statement);
    }
    eprintln!("  Is Axiom: {}", cdu.is_axiom());
    eprintln!("-----------------");
}

/// This is an integrated test that simulates the full lifecycle of a node's
/// first two CDUs, ensuring their logical and causal integrity.
#[test]
fn test_node_lifecycle_and_causal_integrity() {
    // --- Setup ---
    let project_root = find_workspace_root();
    let log_dir = project_root.join("ci-logs");
    fs::create_dir_all(&log_dir).expect("Should be able to create ci-logs directory");

    let hlc = HybridLogicalClock::new();
    let os_name = std::env::consts::OS;
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let seed = format!("cdqn-genesis-{}-{}-{}", env!("CARGO_PKG_NAME"), os_name, timestamp);
    let hardware_fp = cdqn_cryptocore::hash_sha3_256(seed.as_bytes());
    let node_id = hardware_fp.to_vec();

    // --- Step 1: Create the Genesis CDU ---
    let genesis_payload = GenesisPayload {
        hardware_fingerprint: hardware_fp,
        os: os_name.to_string(),
        timestamp: (timestamp / 1_000_000_000) as u64,
        location: "CI Runner".to_string(),
    };
    let payload = genesis_payload.into_payload();
    let metadata = Metadata {
        author_node: node_id.clone(),
        context_refs: vec![], // Genesis has no parents.
        state: "active".to_string(),
        weight: 1.0,
        r_coordinate: 0.0,
        world_context: World::CdqnWorld,
        hlc_timestamp: HlcTimestamp::new(0, 0),
        symmetric_counterpart: None,
        validated_worlds: HashSet::new(),
    };
    let genesis_cdu = Cdu::new(payload, metadata, &hlc, &node_id);
    print_cdu_summary("Genesis CDU", &genesis_cdu);

    assert!(genesis_cdu.is_genesis(), "The first CDU created must be a Genesis CDU");

    // --- Step 2: Create a child ConfigCDU, linked to the Genesis ---
    let mut settings = HashMap::new();
    settings.insert("log_level".to_string(), serde_json::Value::String("info".to_string()));
    
    let config_cdu = Cdu::new_config(settings, node_id.clone(), &hlc, &genesis_cdu.id_hlc);
    print_cdu_summary("Child Config CDU", &config_cdu);
    
    assert!(!config_cdu.is_genesis(), "The second CDU must not be a Genesis CDU");
    assert_eq!(
        config_cdu.metadata.context_refs.first(),
        Some(&genesis_cdu.id_hlc)
    );

    // --- Step 3: Verify the causal chain ---
    let all_cdus = vec![&genesis_cdu, &config_cdu];
    let is_chain_valid = verify_causal_chain(&config_cdu, &all_cdus, &genesis_cdu.id_hlc);
    assert!(is_chain_valid, "The causal chain from the child to the Genesis CDU must be valid");

    // --- Step 4: Report the unique Genesis identifiers for CI verification ---
    let output = format!(
        "OS: {}\nNodeId (hex): {}\nPayloadHash (hex): {}\nGenesisCDU ID (hex): {}\nStatus: SUCCESS\n",
        os_name,
        hex_encode(&node_id),
        hex_encode(&genesis_cdu.payload_hash),
        hex_encode(&genesis_cdu.id_hlc)
    );

    let path = log_dir.join("genesis_report.txt");
    println!("TEST DEBUG: Writing genesis report to: {}", path.display());
    fs::write(&path, output).expect("Unable to write genesis report file");
}

/// This test validates the correct lifecycle: Genesis -> Foundational Axiom.
/// The Genesis CDU itself is not an axiom, but it gives birth to a child Axiom CDU.
#[test]
fn test_genesis_creates_foundational_axiom() {
    let hlc = HybridLogicalClock::new();
    let node_id = vec![3, 3, 3, 3];

    // 1. Create the Genesis CDU.
    let genesis_payload = GenesisPayload {
        hardware_fingerprint: [0; 32],
        os: "test_os".to_string(),
        timestamp: 0,
        location: "test_location".to_string(),
    };
    let genesis_cdu = Cdu::create_genesis_cdu(genesis_payload, node_id.clone(), &hlc);
    print_cdu_summary("Genesis CDU", &genesis_cdu);

    // 2. Create the foundational Axiom, which is a child of the Genesis CDU.
    let foundational_axiom = Cdu::create_foundational_axiom_for(&genesis_cdu.id_hlc, node_id, &hlc);
    print_cdu_summary("Foundational Axiom", &foundational_axiom);

    // --- Assertions ---
    assert!(!genesis_cdu.is_axiom(), "The Genesis CDU itself must not be an Axiom.");
    assert!(foundational_axiom.is_axiom(), "The child foundational axiom must be an Axiom at birth.");
    assert_eq!(
        foundational_axiom.metadata.context_refs,
        vec![genesis_cdu.id_hlc.clone()]
    );
    assert!(foundational_axiom.metadata.validated_worlds.contains(&World::UserWorld));
    assert!(foundational_axiom.metadata.validated_worlds.contains(&World::LangCodingWorld));
    assert!(foundational_axiom.metadata.validated_worlds.contains(&World::CdqnWorld));
}

/// This test validates the lifecycle of a regular Semi-Axiom becoming an Axiom.
#[test]
fn test_semi_axiom_to_axiom_promotion() {
    let hlc = HybridLogicalClock::new();
    let node_id = vec![2, 2, 2, 2];

    // 1. Create a Semi-Axiom in the UserWorld.
    let mut semi_axiom = Cdu::new_semi_axiom(
        "The concept of addition.".to_string(),
        World::UserWorld,
        node_id,
        &hlc,
    );
    print_cdu_summary("Initial Semi-Axiom", &semi_axiom);

    // 2. Initially, it's only validated in its own world, so it's not an Axiom.
    assert!(!semi_axiom.is_axiom(), "A semi-axiom should not be an axiom initially.");
    assert_eq!(semi_axiom.metadata.validated_worlds.len(), 1);

    // 3. The Verifier role validates it in two other worlds.
    semi_axiom.validate_in_world(World::RWorld);
    semi_axiom.validate_in_world(World::LangCodingWorld);
    print_cdu_summary("Promoted Semi-Axiom", &semi_axiom);

    // 4. Now it is validated in UserWorld and two others, so it must be an Axiom.
    assert!(semi_axiom.is_axiom(), "A semi-axiom validated in 3 worlds must be an axiom.");
    assert_eq!(semi_axiom.metadata.validated_worlds.len(), 3);
}
