// crates/cdu/src/types.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use crate::payloads::{ConfigPayload, GenesisPayload, AxiomPayload};
use crate::worlds::World;
use cdqn_cryptocore::hash_sha3_256;
use cdqn_hlc::{HlcTimestamp, HybridLogicalClock};
use serde::{Deserialize, Serialize};
use std::collections::HashSet;

/// The immutable core content of a CDU.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Payload {
    /// The raw byte data of the payload.
    pub data: Vec<u8>,
    /// A string identifier for the payload's type (e.g., "genesis/v1").
    pub payload_type: String,
}

impl Payload {
    /// Computes the SHA3-256 hash of the payload's canonical representation.
    #[must_use]
    pub fn hash(&self) -> [u8; 32] {
        let mut canonical = self.payload_type.as_bytes().to_vec();
        canonical.extend_from_slice(&self.data);
        hash_sha3_256(&canonical)
    }
}

/// The mutable context surrounding a CDU's payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Metadata {
    /// The ID of the node that created the CDU.
    pub author_node: Vec<u8>,
    /// A list of `id_hlc`s of causal parent CDUs.
    pub context_refs: Vec<Vec<u8>>,
    /// The current state of the CDU (e.g., "active", "merged").
    pub state: String,
    /// The influence and trustworthiness score of the CDU.
    pub weight: f64,
    /// The CDU's position in the RWorld mathematical space.
    pub r_coordinate: f64,
    /// The logical partition (e.g., UserWorld) the CDU belongs to.
    pub world_context: World,
    /// The raw HLC timestamp used for ID generation.
    pub hlc_timestamp: HlcTimestamp,
    /// Optional field to link to a symmetric counterpart, used for Semi-Axioms.
    pub symmetric_counterpart: Option<Vec<u8>>,
    /// A set of worlds where this CDU has been validated as a semi-axiom.
    pub validated_worlds: HashSet<World>,
}

/// An entry in the append-only signature log of a CDU.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signature {
    /// The identifier of the entity that signed the CDU.
    pub signer_entity: String,
    /// The timestamp of when the signature was created.
    pub timestamp: HlcTimestamp,
    /// The raw signature bytes.
    pub signature: Vec<u8>,
}

/// The complete Causal Data Unit, the atom of knowledge.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Cdu {
    /// The unique, deterministic, and permanent identifier.
    pub id_hlc: Vec<u8>,
    /// The immutable core content.
    pub payload: Payload,
    /// The cryptographic hash of the payload's canonical bytes.
    pub payload_hash: [u8; 32],
    /// The mutable context.
    pub metadata: Metadata,
    /// An append-only log of signatures.
    pub signatures: Vec<Signature>,
}

/// A collection of helper functions to construct and interpret specific CDU subtypes.
impl Cdu {
    /// Creates a new CDU with a given payload and metadata, generating its ID.
    #[must_use]
    pub fn new(
        payload: Payload,
        mut metadata: Metadata,
        hlc: &HybridLogicalClock,
        node_id: &[u8],
    ) -> Self {
        let payload_hash = payload.hash();
        let hlc_ts = hlc.new_timestamp();
        metadata.hlc_timestamp = hlc_ts;

        let mut id_input = hlc_ts.as_u64().to_be_bytes().to_vec();
        id_input.extend_from_slice(node_id);
        id_input.extend_from_slice(&payload_hash);

        let id_hlc = hash_sha3_256(&id_input).to_vec();

        Self {
            id_hlc,
            payload_hash,
            payload,
            metadata,
            signatures: Vec::new(),
        }
    }

    /// Creates the sovereign Genesis CDU for a node.
    /// This CDU is a special case: it is a Semi-Axiom that is immediately
    /// validated in `CdqnWorld`, `UserWorld`, and `LangCodingWorld`, thus
    /// making it a full Axiom at birth.
    #[must_use]
    pub fn create_genesis_cdu(
        genesis_payload: GenesisPayload,
        author_node: Vec<u8>,
        hlc: &HybridLogicalClock,
    ) -> Self {
        let payload = genesis_payload.into_payload();
        let mut validated_worlds = HashSet::new();
        validated_worlds.insert(World::CdqnWorld);
        validated_worlds.insert(World::UserWorld);
        validated_worlds.insert(World::LangCodingWorld);

        let metadata = Metadata {
            author_node: author_node.clone(), // Clone to allow later use
            context_refs: vec![],
            state: "active".to_string(),
            weight: 1.0,
            r_coordinate: 0.0,
            world_context: World::CdqnWorld,
            hlc_timestamp: HlcTimestamp::new(0, 0),
            symmetric_counterpart: None,
            validated_worlds,
        };

        Self::new(payload, metadata, hlc, &author_node)
    }

    /// Creates a new Semi-Axiom CDU.
    /// The semi-axiom is initially only validated in its own world.
    #[must_use]
    pub fn new_semi_axiom(
        statement: String,
        origin_world: World,
        author_node: Vec<u8>,
        hlc: &HybridLogicalClock,
    ) -> Self {
        let axiom_payload = AxiomPayload { statement, origin_world };
        let payload = axiom_payload.into_payload();
        let payload_hash = payload.hash();
        let hlc_ts = hlc.new_timestamp();

        let mut id_input = hlc_ts.as_u64().to_be_bytes().to_vec();
        id_input.extend_from_slice(&author_node);
        id_input.extend_from_slice(&payload_hash);
        let id_hlc = hash_sha3_256(&id_input).to_vec();

        let mut validated_worlds = HashSet::new();
        // We can't use `origin_world` here, so we get it from the payload after creation.
        // This is a small workaround to avoid cloning.
        let deserialized_payload: AxiomPayload = serde_json::from_slice(&payload.data)
            .expect("Payload should be valid AxiomPayload");
        validated_worlds.insert(deserialized_payload.origin_world);

        let metadata = Metadata {
            author_node, // Move, no clone.
            context_refs: vec![],
            state: "active".to_string(),
            weight: 1.0,
            r_coordinate: 0.0,
            world_context: deserialized_payload.origin_world,
            hlc_timestamp: hlc_ts,
            symmetric_counterpart: None,
            validated_worlds,
        };

        Self {
            id_hlc,
            payload_hash,
            payload,
            metadata,
            signatures: Vec::new(),
        }
    }

    /// A performance-oriented convenience constructor for creating a `ConfigCDU`.
    /// This function is written to avoid any memory allocations by reordering
    /// operations to prevent cloning the `author_node`.
    #[must_use]
    pub fn new_config(
        settings: std::collections::HashMap<String, serde_json::Value>,
        author_node: Vec<u8>,
        hlc: &HybridLogicalClock,
        parent_id: &[u8], // The ID of the parent CDU to link to.
    ) -> Self {
        let config_payload = ConfigPayload { settings };
        let payload = config_payload.into_payload();
        let payload_hash = payload.hash();
        let hlc_ts = hlc.new_timestamp();

        // Generate the ID while we can still borrow `author_node`.
        let mut id_input = hlc_ts.as_u64().to_be_bytes().to_vec();
        id_input.extend_from_slice(&author_node);
        id_input.extend_from_slice(&payload_hash);
        let id_hlc = hash_sha3_256(&id_input).to_vec();

        // Now that hashing is done, we can move `author_node` into the metadata.
        let metadata = Metadata {
            author_node, // Move, no clone.
            context_refs: vec![parent_id.to_vec()], // Link to the parent.
            state: "active".to_string(),
            weight: 1.0,
            r_coordinate: 0.0,
            world_context: World::UserWorld,
            hlc_timestamp: hlc_ts,
            symmetric_counterpart: None, // Default for non-Axioms.
            validated_worlds: HashSet::new(), // Default for non-Axioms.
        };

        Self {
            id_hlc,
            payload_hash,
            payload,
            metadata,
            signatures: Vec::new(),
        }
    }

    /// Validates this Semi-Axiom CDU in another world.
    /// This would be called by the `Verifier` role in Chronosa.
    /// Returns `true` if the world was newly added, `false` if it was already present.
    pub fn validate_in_world(&mut self, world: World) -> bool {
        self.metadata.validated_worlds.insert(world)
    }

    /// Determines if a Semi-Axiom CDU has achieved the status of a full Axiom.
    /// An Axiom is a Semi-Axiom that is validated in the UserWorld and at least
    /// two other worlds.
    #[must_use]
    pub fn is_axiom(&self) -> bool {
        if self.payload.payload_type != "axiom/v1" {
            return false;
        }
        let is_valid_in_user_world = self.metadata.validated_worlds.contains(&World::UserWorld);
        let count_other_worlds = self.metadata.validated_worlds.len()
            - if is_valid_in_user_world { 1 } else { 0 };

        is_valid_in_user_world && count_other_worlds >= 2
    }

    /// Returns true if this CDU is the Genesis CDU of the node.
    #[must_use]
    pub fn is_genesis(&self) -> bool {
        self.payload.payload_type == "genesis/v1"
    }

    /// Attempts to interpret the CDU as a `ConfigCDU`.
    pub fn as_config(&self) -> Option<ConfigPayload> {
        if self.payload.payload_type != "config/v1" {
            return None;
        }
        serde_json::from_slice(&self.payload.data).ok()
    }

    /// Attempts to interpret the CDU as an `AxiomCDU`.
    pub fn as_axiom(&self) -> Option<AxiomPayload> {
        if self.payload.payload_type != "axiom/v1" {
            return None;
        }
        serde_json::from_slice(&self.payload.data).ok()
    }
}
