// crates/cdu/src/utils.rs
// File under the BaDaaS license, code generated by the ai assistant: Gemini Flash Latest, Google

// NOTE: All test-only utilities (hex_encode, verify_causal_chain) have been moved
// to the `tests` module where they are actually used, to satisfy Clippy's dead_code warning.
// This file is now minimal.
