// crates/cdu/src/utils.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use crate::types::Cdu;

/// A simple utility to encode bytes as a hexadecimal string.
#[allow(dead_code)] // Currently only used in tests, but is a general utility.
pub fn hex_encode(bytes: &[u8]) -> String {
    const HEX_CHARS: &[u8] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for &b in bytes {
        output.push(HEX_CHARS[(b >> 4) as usize] as char);
        output.push(HEX_CHARS[(b & 0x0F) as usize] as char);
    }
    output
}

/// A simple, in-memory verification function for testing causal chains.
/// In a real implementation, this would be part of the `Manifold` crate and
/// would load CDUs from persistent storage.
#[allow(dead_code)] // Currently only used in tests, but will be part of the Manifold.
pub fn verify_causal_chain(
    cdu: &Cdu,
    all_cdus: &[&Cdu],
    expected_genesis_id: &[u8],
) -> bool {
    if cdu.is_genesis() {
        return cdu.id_hlc == expected_genesis_id;
    }

    for parent_id in &cdu.metadata.context_refs {
        if let Some(parent_cdu) = all_cdus.iter().find(|&p| p.id_hlc == *parent_id) {
            if !verify_causal_chain(parent_cdu, all_cdus, expected_genesis_id) {
                return false;
            }
        } else {
            // Parent not found in the provided set, chain is broken.
            return false;
        }
    }
    true
}
