// crates/cdu/src/worlds.rs
// File under the BaDaaS license, code generated by the ai assistant: GML-4.6, chat.z.ai

use serde::{Deserialize, Serialize};

/// Defines the logical partitions (Worlds) within the CDQN ecosystem.
/// The hierarchy is implicit in the relationships between the variants.
/// Adding `Copy` makes this simple enum cheap and easy to use without ownership issues.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Copy)]
pub enum World {
    /// The top-level world, representing the entirety of the real numbers and all
    /// that can be reasoned about.
    RWorld,
    /// A subset of RWorld, representing the user's perspective and what they can see.
    UserWorld,
    /// A subset of UserWorld, representing the world of programming languages.
    LangCodingWorld,
    /// A subset of UserWorld, representing the CDQN ecosystem itself.
    CdqnWorld,
    /// A context for fictional or hypothetical reasoning, where consistency with
    /// reality-based worlds is suspended.
    FicWorld,
    /// A high-security context for analyzing potential threats.
    HalWorld,
}

impl World {
    /// Checks if this world is a direct or indirect parent of another.
    /// For example, UserWorld is a parent of CdqnWorld.
    pub fn is_parent_of(&self, child: &World) -> bool {
        match (self, child) {
            (World::RWorld, _) => *child != World::RWorld,
            (World::UserWorld, World::CdqnWorld | World::LangCodingWorld) => true,
            _ => false,
        }
    }
}
